// lib/features/family/presentation/services/graph_export_service.dart
//
// DAXELO KINREL — Graph Share / Export (Step 5).
//
// Captures a RepaintBoundary (the on-screen graph) to PNG, PDF, or SVG
// and shares it via the OS share sheet.
//
// v91: PDF and SVG exports are now fully implemented.
//   - PDF: captures PNG at retina, embeds it in an A4-landscape PDF
//     page via the `pdf` package, shares as application/pdf.
//   - SVG: generates a real SVG document by walking graph nodes/edges.
//     No rasterization — true vector output editable in design tools.

import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart' as share_plus;

/// Output formats for graph export.
enum GraphExportFormat { png, pdf, svg }

/// A node for SVG generation (minimal data needed to draw a circle + label).
class GraphSvgNode {
  const GraphSvgNode({
    required this.id,
    required this.x,
    required this.y,
    required this.label,
    this.color = '#E8612A',
    this.radius = 30.0,
  });
  final String id;
  final double x;
  final double y;
  final String label;
  final String color;
  final double radius;
}

/// An edge for SVG generation.
class GraphSvgEdge {
  const GraphSvgEdge({
    required this.fromId,
    required this.toId,
    this.color = '#C9B4A8',
    this.dashed = false,
  });
  final String fromId;
  final String toId;
  final String color;
  final bool dashed;
}

/// Captures and shares a graph rendered under a keyed [RepaintBoundary].
class GraphExportService {
  const GraphExportService._();

  /// Captures the [RepaintBoundary] identified by [boundaryKey] to PNG bytes.
  ///
  /// Returns null if the boundary isn't mounted/painted yet. [pixelRatio]
  /// trades file size for sharpness (3.0 ≈ retina).
  static Future<Uint8List?> capturePngBytes(
    GlobalKey boundaryKey, {
    double pixelRatio = 3.0,
  }) async {
    final renderObject = boundaryKey.currentContext?.findRenderObject();
    if (renderObject is! RenderRepaintBoundary) return null;

    // If the layer is still dirty, give it one frame to settle.
    if (renderObject.debugNeedsPaint) {
      await Future<void>.delayed(const Duration(milliseconds: 20));
    }

    final ui.Image image = await renderObject.toImage(pixelRatio: pixelRatio);
    try {
      final byteData =
          await image.toByteData(format: ui.ImageByteFormat.png);
      return byteData?.buffer.asUint8List();
    } finally {
      image.dispose();
    }
  }

  /// Captures the graph as PNG bytes, then embeds them in an A4-landscape
  /// PDF page. Returns the PDF bytes, or null if the capture failed.
  static Future<Uint8List?> capturePdfBytes(
    GlobalKey boundaryKey, {
    double pixelRatio = 3.0,
    String title = 'Family Graph',
  }) async {
    final pngBytes = await capturePngBytes(boundaryKey, pixelRatio: pixelRatio);
    if (pngBytes == null) return null;

    final pdf = pw.Document();
    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4.landscape,
        margin: const pw.EdgeInsets.all(28),
        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                title,
                style: pw.TextStyle(
                  fontSize: 18,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 12),
              pw.Expanded(
                child: pw.Center(
                  child: pw.Image(
                    pw.MemoryImage(pngBytes),
                    fit: pw.BoxFit.contain,
                  ),
                ),
              ),
              pw.SizedBox(height: 8),
              pw.Align(
                alignment: pw.Alignment.centerRight,
                child: pw.Text(
                  'Generated by Kinrel • ${DateTime.now().toLocal().toString().split('.').first}',
                  style: pw.TextStyle(fontSize: 9, color: PdfColors.grey),
                ),
              ),
            ],
          );
        },
      ),
    );

    return pdf.save();
  }

  /// Generates an SVG document string from graph nodes and edges.
  ///
  /// The SVG uses true vector elements:
  ///   - `<line>` for edges (with `stroke-dasharray` when dashed)
  ///   - `<circle>` + `<text>` for nodes
  ///
  /// Returns the SVG as a UTF-8 byte buffer.
  static Uint8List generateSvgBytes({
    required List<GraphSvgNode> nodes,
    required List<GraphSvgEdge> edges,
    String title = 'Family Graph',
  }) {
    if (nodes.isEmpty) {
      return Uint8List.fromList(
        '<svg xmlns="http://www.w3.org/2000/svg" width="400" height="200">'
        '<text x="200" y="100" text-anchor="middle" fill="#888">No data</text>'
        '</svg>'
            .codeUnits,
      );
    }

    // Compute bounding box
    double minX = double.infinity, minY = double.infinity;
    double maxX = double.negativeInfinity, maxY = double.negativeInfinity;
    for (final n in nodes) {
      minX = minX < n.x - n.radius ? minX : n.x - n.radius;
      minY = minY < n.y - n.radius ? minY : n.y - n.radius;
      maxX = maxX > n.x + n.radius ? maxX : n.x + n.radius;
      maxY = maxY > n.y + n.radius ? maxY : n.y + n.radius;
    }
    const padding = 40.0;
    final width = (maxX - minX) + padding * 2;
    final height = (maxY - minY) + padding * 2;
    final offsetX = -minX + padding;
    final offsetY = -minY + padding;

    final buf = StringBuffer();
    buf.writeln(
      '<svg xmlns="http://www.w3.org/2000/svg" '
      'width="${width.toStringAsFixed(1)}" '
      'height="${height.toStringAsFixed(1)}" '
      'viewBox="0 0 ${width.toStringAsFixed(1)} ${height.toStringAsFixed(1)}">',
    );
    buf.writeln('  <title>$title</title>');
    buf.writeln(
      '  <rect width="100%" height="100%" fill="#13141E"/>',
    );

    // Build node ID → position map for edges
    final nodeMap = {for (final n in nodes) n.id: n};

    // Edges
    for (final e in edges) {
      final from = nodeMap[e.fromId];
      final to = nodeMap[e.toId];
      if (from == null || to == null) continue;
      final dash = e.dashed ? ' stroke-dasharray="6,4"' : '';
      buf.writeln(
        '  <line x1="${(from.x + offsetX).toStringAsFixed(1)}" '
        'y1="${(from.y + offsetY).toStringAsFixed(1)}" '
        'x2="${(to.x + offsetX).toStringAsFixed(1)}" '
        'y2="${(to.y + offsetY).toStringAsFixed(1)}" '
        'stroke="${e.color}" stroke-width="2"$dash/>',
      );
    }

    // Nodes
    for (final n in nodes) {
      final cx = n.x + offsetX;
      final cy = n.y + offsetY;
      buf.writeln(
        '  <circle cx="${cx.toStringAsFixed(1)}" '
        'cy="${cy.toStringAsFixed(1)}" '
        'r="${n.radius.toStringAsFixed(1)}" '
        'fill="${n.color}" stroke="#FFFFFF" stroke-width="1.5"/>',
      );
      // Label (escape XML special chars)
      final label = n.label
          .replaceAll('&', '&amp;')
          .replaceAll('<', '&lt;')
          .replaceAll('>', '&gt;');
      buf.writeln(
        '  <text x="${cx.toStringAsFixed(1)}" '
        'y="${(cy + 4).toStringAsFixed(1)}" '
        'text-anchor="middle" fill="#FFFFFF" '
        'font-family="Arial,sans-serif" font-size="12" font-weight="600">'
        '$label</text>',
      );
    }

    // Footer
    buf.writeln(
      '  <text x="${(width - 10).toStringAsFixed(1)}" '
      'y="${(height - 10).toStringAsFixed(1)}" '
      'text-anchor="end" fill="#888" font-family="Arial,sans-serif" font-size="9">'
      'Generated by Kinrel • ${DateTime.now().toLocal().toString().split('.').first}'
      '</text>',
    );

    buf.writeln('</svg>');
    return Uint8List.fromList(buf.toString().codeUnits);
  }

  /// Captures the graph and opens the OS share sheet with the image/PDF/SVG attached.
  ///
  /// [format] defaults to PNG. For PDF, captures PNG then wraps in a PDF page.
  /// For SVG, requires [svgNodes] and [svgEdges] to be provided.
  static Future<bool> shareGraph(
    GlobalKey boundaryKey, {
    String subject = 'My family graph',
    String fileName = 'kinrel_family_graph.png',
    double pixelRatio = 3.0,
    GraphExportFormat format = GraphExportFormat.png,
    List<GraphSvgNode>? svgNodes,
    List<GraphSvgEdge>? svgEdges,
    String title = 'Family Graph',
  }) async {
    switch (format) {
      case GraphExportFormat.pdf:
        final bytes = await capturePdfBytes(
          boundaryKey,
          pixelRatio: pixelRatio,
          title: title,
        );
        if (bytes == null) return false;
        final xfile = share_plus.XFile.fromData(
          bytes,
          name: fileName.endsWith('.png')
              ? fileName.replaceAll('.png', '.pdf')
              : (fileName.endsWith('.pdf') ? fileName : '$fileName.pdf'),
          mimeType: 'application/pdf',
        );
        await share_plus.Share.shareXFiles(<share_plus.XFile>[xfile],
            subject: subject);
        return true;

      case GraphExportFormat.svg:
        if (svgNodes == null) return false;
        final bytes = generateSvgBytes(
          nodes: svgNodes,
          edges: svgEdges ?? const [],
          title: title,
        );
        final svgName = fileName.endsWith('.png')
            ? fileName.replaceAll('.png', '.svg')
            : (fileName.endsWith('.svg') ? fileName : '$fileName.svg');
        final xfile = share_plus.XFile.fromData(
          bytes,
          name: svgName,
          mimeType: 'image/svg+xml',
        );
        await share_plus.Share.shareXFiles(<share_plus.XFile>[xfile],
            subject: subject);
        return true;

      case GraphExportFormat.png:
      default:
        final bytes = await capturePngBytes(boundaryKey, pixelRatio: pixelRatio);
        if (bytes == null) return false;
        final xfile = share_plus.XFile.fromData(
          bytes,
          name: fileName,
          mimeType: 'image/png',
        );
        await share_plus.Share.shareXFiles(<share_plus.XFile>[xfile],
            subject: subject);
        return true;
    }
  }
}
