// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class SEn extends S {
  SEn([String locale = 'en']) : super(locale);

  @override
  String get appName => 'Kinrel';

  @override
  String get appTagline => 'Map your family with AI';

  @override
  String get homeTitle => 'Home';

  @override
  String get kinshipTitle => 'Kinship';

  @override
  String get graphTitle => 'Graph';

  @override
  String get alertsTitle => 'Alerts';

  @override
  String get profileTitle => 'Me';

  @override
  String get notificationsTitle => 'Notifications';

  @override
  String get eventsTitle => 'Events & Celebrations';

  @override
  String get memoriesTitle => 'Memories & Timeline';

  @override
  String get chatTitle => 'Family Chat';

  @override
  String get documentsTitle => 'Document Vault';

  @override
  String get achievementsTitle => 'Achievements';

  @override
  String get shareTitle => 'Share & Invite';

  @override
  String get settingsTitle => 'Settings';

  @override
  String get signInTitle => 'Sign In';

  @override
  String get signUpTitle => 'Sign Up';

  @override
  String get onboardingTitle1 => 'Your Family, Your Story';

  @override
  String get onboardingBody1 =>
      'Kinrel maps every relationship in your family — from your grandparents to your grandchildren, in the language you grew up with.';

  @override
  String get onboardingTitle2 => 'Names That Feel Like Home';

  @override
  String get onboardingBody2 =>
      'Not just \'uncle\' and \'aunt\' — Kinrel knows the difference between your Chacha, Mama, Fufa, and Tauji.';

  @override
  String get onboardingTitle3 => 'See the Big Picture';

  @override
  String get onboardingBody3 =>
      'Your entire family as a beautiful, interactive graph. Zoom in, explore connections, discover relationships you never knew existed.';

  @override
  String get onboardingTitle4 => 'Find Any Relationship Instantly';

  @override
  String get onboardingBody4 =>
      'Select any two family members — Kinrel\'s AI calculates the exact relationship name in your language.';

  @override
  String get addMember => 'Add Member';

  @override
  String get shareFamily => 'Share Family';

  @override
  String get findPath => 'Find Path';

  @override
  String get viewFullGraph => 'View Full Graph';

  @override
  String get recentActivity => 'Recent Activity';

  @override
  String get familyInsights => 'Family at a Glance';

  @override
  String get noNotifications => 'All caught up! No new notifications.';

  @override
  String get noEvents =>
      'No events yet. Birthdays and anniversaries from your family will appear here automatically.';

  @override
  String get noMemories =>
      'No memories yet. Add your first family memory to begin.';

  @override
  String get noDocuments =>
      'No documents yet. Securely store your family\'s important documents.';

  @override
  String get createFamily => 'Create Family';

  @override
  String get joinFamily => 'Join Family';

  @override
  String get searchHint => 'Search relationships';

  @override
  String birthdayTomorrow(String name) {
    return '$name\'s birthday is tomorrow!';
  }

  @override
  String anniversarySoon(String name, String name2, int days) {
    return '$name & $name2\'s anniversary is in $days days!';
  }

  @override
  String get sendWishes => 'Send wishes?';

  @override
  String streakDays(int count) {
    return '$count Day Streak';
  }

  @override
  String profileCompletion(int percent) {
    return '$percent% Complete';
  }

  @override
  String treeCompleteness(int percent) {
    return 'Your tree is $percent% complete';
  }

  @override
  String get encryptNotice => 'Encrypted with AES-256';

  @override
  String get generatedByKinrel => 'Generated by Kinrel';

  @override
  String get madeByDaxelo => 'Made with love by Daxelo';

  @override
  String get welcomeBack => 'Welcome back';

  @override
  String get goodMorning => 'Good morning';

  @override
  String get goodAfternoon => 'Good afternoon';

  @override
  String get goodEvening => 'Good evening';

  @override
  String get goodNight => 'Good night';

  @override
  String get languageName => 'English';
}
