// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class SEn extends S {
  SEn([String locale = 'en']) : super(locale);

  @override
  String get appName => 'Kinrel';

  @override
  String get appTagline => 'Map your family with AI';

  @override
  String get homeTitle => 'Home';

  @override
  String get kinshipTitle => 'Kinship';

  @override
  String get graphTitle => 'Graph';

  @override
  String get alertsTitle => 'Alerts';

  @override
  String get profileTitle => 'Me';

  @override
  String get notificationsTitle => 'Notifications';

  @override
  String get eventsTitle => 'Events & Celebrations';

  @override
  String get memoriesTitle => 'Memories & Timeline';

  @override
  String get chatTitle => 'Family Chat';

  @override
  String get documentsTitle => 'Document Vault';

  @override
  String get achievementsTitle => 'Achievements';

  @override
  String get shareTitle => 'Share & Invite';

  @override
  String get settingsTitle => 'Settings';

  @override
  String get signInTitle => 'Sign In';

  @override
  String get signUpTitle => 'Sign Up';

  @override
  String get onboardingTitle1 => 'Your Family, Your Story';

  @override
  String get onboardingBody1 =>
      'Kinrel maps every relationship in your family — from your grandparents to your grandchildren, in the language you grew up with.';

  @override
  String get onboardingTitle2 => 'Names That Feel Like Home';

  @override
  String get onboardingBody2 =>
      'Not just \'uncle\' and \'aunt\' — Kinrel knows the difference between your Chacha, Mama, Fufa, and Tauji.';

  @override
  String get onboardingTitle3 => 'See the Big Picture';

  @override
  String get onboardingBody3 =>
      'Your entire family as a beautiful, interactive graph. Zoom in, explore connections, discover relationships you never knew existed.';

  @override
  String get onboardingTitle4 => 'Find Any Relationship Instantly';

  @override
  String get onboardingBody4 =>
      'Select any two family members — Kinrel\'s AI calculates the exact relationship name in your language.';

  @override
  String get addMember => 'Add Member';

  @override
  String get shareFamily => 'Share Family';

  @override
  String get findPath => 'Find Path';

  @override
  String get viewFullGraph => 'View Full Graph';

  @override
  String get recentActivity => 'Recent Activity';

  @override
  String get familyInsights => 'Family at a Glance';

  @override
  String get noNotifications => 'All caught up! No new notifications.';

  @override
  String get noEvents =>
      'No events yet. Birthdays and anniversaries from your family will appear here automatically.';

  @override
  String get noMemories =>
      'No memories yet. Add your first family memory to begin.';

  @override
  String get noDocuments =>
      'No documents yet. Securely store your family\'s important documents.';

  @override
  String get createFamily => 'Create Family';

  @override
  String get joinFamily => 'Join Family';

  @override
  String get searchHint => 'Search relationships';

  @override
  String birthdayTomorrow(String name) {
    return '$name\'s birthday is tomorrow!';
  }

  @override
  String anniversarySoon(String name, String name2, int days) {
    return '$name & $name2\'s anniversary is in $days days!';
  }

  @override
  String get sendWishes => 'Send wishes?';

  @override
  String streakDays(int count) {
    return '$count Day Streak';
  }

  @override
  String profileCompletion(int percent) {
    return '$percent% Complete';
  }

  @override
  String treeCompleteness(int percent) {
    return 'Your tree is $percent% complete';
  }

  @override
  String get encryptNotice => 'Encrypted with AES-256';

  @override
  String get generatedByKinrel => 'Generated by Kinrel';

  @override
  String get madeByDaxelo => 'Made with love by Daxelo';

  @override
  String get welcomeBack => 'Welcome back';

  @override
  String get goodMorning => 'Good morning';

  @override
  String get goodAfternoon => 'Good afternoon';

  @override
  String get goodEvening => 'Good evening';

  @override
  String get goodNight => 'Good night';

  @override
  String get languageName => 'English';

  @override
  String get kinrelNavLabel => 'Kinrel';

  @override
  String get kinrelScreenTitle => 'Kinrel';

  @override
  String get kinrelEmptyTitle => 'Kinrel has not been computed yet';

  @override
  String get kinrelEmptyBody =>
      'Kinrel analyses your family graph to generate a unique symbol and archetype. This usually takes a few seconds.';

  @override
  String get kinrelGenerateButton => 'Generate Kinrel';

  @override
  String get kinrelRecomputeButton => 'Recompute';

  @override
  String get kinrelLoadingTitle => 'Computing Kinrel…';

  @override
  String get kinrelCachedBanner => 'Showing cached Kinrel — offline mode';

  @override
  String get kinrelErrorTitle => 'Could not load Kinrel';

  @override
  String get kinrelShareTooltip => 'Share Kinrel';

  @override
  String kinrelShareText(String familyName) {
    return 'Our family\'s Kinrel — $familyName';
  }

  @override
  String get kinrelTimelineTitle => 'Kinrel Timeline';

  @override
  String get kinrelTimelineEmptyTitle => 'No Kinrel history yet';

  @override
  String get kinrelTimelineEmptyBody =>
      'As your family grows, snapshots of how the Kinrel evolved will appear here.';

  @override
  String kinrelMemberCountCaption(int count) {
    return '$count members';
  }

  @override
  String kinrelConfidenceLabel(int percent) {
    return '$percent% match';
  }

  @override
  String get kinrelFeatureDisabled => 'Kinrel is not available.';

  @override
  String get familyMapLoading => 'Loading family map…';

  @override
  String get familyMapEmptyTitle => 'No family locations yet';

  @override
  String get familyMapEmptyBody =>
      'Add a location to a family member to see your family across the map.';

  @override
  String get familyMapFailedTitle => 'Couldn\'t load the family map';

  @override
  String get familyMapFailedBody => 'Check your connection and try again.';

  @override
  String get familyMapRetry => 'Retry';

  @override
  String familyMapLocatedCount(int count) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: 's',
      one: '',
    );
    return '$count member$_temp0 located';
  }

  @override
  String get familyMapTitle => 'Family Map';

  @override
  String get familyMapNoJourney =>
      'No journey data for this family member yet.';

  @override
  String familyMapHouseholdMembers(int count) {
    return 'Household — $count members';
  }

  @override
  String get familyMapViewProfile => 'View Profile';

  @override
  String familyMapUnpinnedCount(int count) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: 's',
      one: '',
    );
    return '$count member$_temp0 without map pin';
  }

  @override
  String get familyMapAddCityPrompt =>
      'Add a city to these members to see them on the map.';

  @override
  String get familyMapNoCitySet => 'No city set';

  @override
  String familyMapCityNotFound(String city) {
    return '$city (not found)';
  }

  @override
  String familyMapPinned(int count) {
    return '$count pinned';
  }

  @override
  String familyMapNotPinned(int count) {
    return '$count not pinned';
  }

  @override
  String get familyMapCouldNotLoad => 'Could Not Load Map';

  @override
  String get familyMapErrorBody =>
      'Something went wrong while loading the family map. Please try again.';

  @override
  String get familyMapLinkedMember => 'Linked family member';

  @override
  String get familyMapMemories => 'Memories';

  @override
  String get familyMapClose => 'Close';

  @override
  String get familyMapBack => 'Back';

  @override
  String get familyMapTest3dBengaluru => 'Test 3D: Bengaluru';

  @override
  String get familyMapFlyToBengaluruSnackbar =>
      'Flying to Bengaluru — 3D buildings should appear at this zoom level';

  @override
  String get familyMapFamilyMember => 'Family Member';

  @override
  String familyMapViewMember(String name) {
    return 'View $name';
  }

  @override
  String familyMapHouseholdClusterLabel(int count) {
    return 'Household with $count members. Double-tap to expand.';
  }

  @override
  String familyMapTimelineLabel(int year) {
    return 'Family timeline. Currently viewing $year. Drag to change.';
  }

  @override
  String get familyMapTimelinePreviousYear => 'Previous year';

  @override
  String get familyMapTimelineNextYear => 'Next year';

  @override
  String get familyMapTimelinePlay => 'Play timeline';

  @override
  String get familyMapTimelinePause => 'Pause timeline';

  @override
  String familyMapTimelineRange(int min, int max) {
    return '$min–$max';
  }

  @override
  String get familyMapJourneyTitle => 'Family Journey';

  @override
  String get familyMapJourneyBorn => 'Born';

  @override
  String get familyMapJourneyPrevious => 'Previous stop';

  @override
  String get familyMapJourneyNext => 'Next stop';

  @override
  String get familyMapJourneyPlay => 'Play journey';

  @override
  String get familyMapJourneyPause => 'Pause journey';

  @override
  String get familyMapJourneyClose => 'Close journey';

  @override
  String familyMapAvatarPinLabel(String name, String tier) {
    return '$name$tier. Double-tap to focus.';
  }

  @override
  String get familyMapAvatarSelectedSuffix => 'Selected.';

  @override
  String get familyMapAvatarDoubleTapFocus => 'Double-tap to focus.';

  @override
  String get familyMapTierLive => 'Live • now';

  @override
  String get familyMapTierUpdatedRecently => 'Updated recently';

  @override
  String get familyMapTierUpdatedJustNow => 'Updated just now';

  @override
  String familyMapTierUpdatedMinsAgo(int mins) {
    return 'Updated ${mins}m ago';
  }

  @override
  String get familyMapTierLastKnown => 'Last known';

  @override
  String get familyMapProgressOffline => 'Offline — showing cached data';

  @override
  String get familyMapProgressRestoring => 'Restoring your view…';

  @override
  String get familyMapProgressMap => 'Loading map…';

  @override
  String get familyMapProgressLandmarks => 'Loading landmarks…';

  @override
  String get familyMapProgressFamilyPlaces => 'Loading family places…';

  @override
  String get familyMapProgressConnections => 'Loading connections…';

  @override
  String get familyMapProgressMembers => 'Loading family members…';

  @override
  String get familyMapProgressAlmost => 'Almost there…';

  // ── P13 — Control stack + search + legend ──────────────────────────
  @override
  String get familyMapControlLocate => 'Locate me';

  @override
  String get familyMapControlZoomIn => 'Zoom in';

  @override
  String get familyMapControlZoomOut => 'Zoom out';

  @override
  String get familyMapControlLayers => 'Layers';

  @override
  String get familyMapControlDarkMode => 'Dark map';

  @override
  String get familyMapControlLightMode => 'Light map';

  @override
  String get familyMapControl3DBuildingsOn => 'Turn on 3D buildings';

  @override
  String get familyMapControl3DBuildingsOff => 'Turn off 3D buildings';

  @override
  String get familyMapLocateServiceOff => 'Location services are off.';

  @override
  String get familyMapLocatePermissionDenied => 'Location permission denied.';

  @override
  String get familyMapLocateFailed =>
      'Could not get your current location.';

  @override
  String get familyMapLayersTitle => 'Map layers';

  @override
  String get familyMapLayersDone => 'Done';

  @override
  String get familyMapLayerHomes => 'Family homes';

  @override
  String get familyMapLayerWeddings => 'Wedding venues';

  @override
  String get familyMapLayerMemorials => 'Memorials';

  @override
  String get familyMapLayerSchools => 'Schools';

  @override
  String get familyMapLayerPlaces => 'Important places';

  @override
  String get familyMapLayerRelationships => 'Relationship paths';

  @override
  String get familyMapLayerCallouts => 'Place labels';

  @override
  String get familyMapLayerLivePulses => 'Live pulses';

  @override
  String get familyMapSearchHint => 'Search city or family member';

  @override
  String get familyMapSearchCollapsed => 'Search city or family member';

  @override
  String get familyMapSearchClear => 'Clear';

  @override
  String get familyMapSearchCityHint => 'City';

  @override
  String get familyMapLegendPinned => 'located';

  @override
  String get familyMapLegendCities => 'cities';

  @override
  String get familyMapLegendStatusTitle => 'Status tiers';

  @override
  String get familyMapLegendCategoriesTitle => 'Place categories';

  @override
  String get familyMapLegendUnpinnedTitle => 'Not on map';

  @override
  String get familyMapLegendTierLive => 'Live';

  @override
  String get familyMapLegendTierLiveDesc => '< 2 min ago';

  @override
  String get familyMapLegendTierRecent => 'Recent';

  @override
  String get familyMapLegendTierRecentDesc => '< 15 min ago';

  @override
  String get familyMapLegendTierStale => 'Stale';

  @override
  String get familyMapLegendTierStaleDesc => '< 1 hour ago';

  @override
  String get familyMapLegendTierCity => 'City';

  @override
  String get familyMapLegendTierCityDesc => 'city centroid';
}
