// lib/features/share/presentation/share_screen.dart
//
// DAXELO KINREL — Share & Invite Screen
//
// Orange K-Graph DNA design:
//   • Tab bar: "Invite" | "Share Card" | "Share Graph"
//   • Invite tab: 6 share method cards in 2-column grid
//     (Link, QR Code, WhatsApp, SMS, Email, Copy)
//     + Active invite links list
//   • Share Card tab: Beautiful kinship card with regional term,
//     English translation, relationship path, "Generated by Kinrel"
//     branding + share to WhatsApp Status / general share sheet
//   • Share Graph tab: Graph preview with export options
//     + "Created with Kinrel by Daxelo" watermark
//
// Design colors:
//   Background:  #13141E (darkSurface)
//   Cards:       #191B2C (darkCard)
//   Primary:     #F5F0EE (textWhite)
//   Secondary:   #C9B4A8 (textSilver)
//   Accent:      #E8612A (orange)
//   WhatsApp:    #25D366 (green)
//   SMS:         #3B82F6 (blue)
//   Email:       #E8612A (orange)
//   QR Code:     #F59240 (amber)
//   Copy:        #F5F0EE (white)

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:share_plus/share_plus.dart' as share_plus;

import '../../../core/constants/brand_colors.dart';
import '../../../core/constants/brand_typography.dart';
import '../../../core/constants/brand_spacing.dart';
import '../../../shared/widgets/dk_components.dart';
import '../../../core/utils/share_helper.dart';
import '../providers/share_provider.dart';
import '../../../core/utils/device_tier.dart';

// ── Color shortcuts ──────────────────────────────────────────────────
const _cOrange = KinrelColors.orange; // #E8612A
const _cAmber = KinrelColors.amber; // #F59240
const _cGold = KinrelColors.gold; // #D4AF37
const _cBg = KinrelColors.darkSurface; // #13141E
const _cCard = KinrelColors.darkCard; // #191B2C
const _cElevated = KinrelColors.darkElevated; // #202338
const _cTextPrimary = KinrelColors.textWhite; // #F5F0EE
const _cTextSecondary = KinrelColors.textSilver; // #C9B4A8
const _cTextDim = KinrelColors.textDim; // #8A7A72
const _cBorder = Color(0xFF3A3A4A);
const _cWhatsApp = Color(0xFF25D366);
const _cSMS = Color(0xFF3B82F6);
const _cEmail = Color(0xFFE8612A);

// ═══════════════════════════════════════════════════════════════════════
// Share Screen
// ═══════════════════════════════════════════════════════════════════════

class ShareScreen extends ConsumerStatefulWidget {
  const ShareScreen({
    super.key,
    required this.familyId,
    required this.familyName,
  });

  final String familyId;
  final String familyName;

  @override
  ConsumerState<ShareScreen> createState() => _ShareScreenState();
}

class _ShareScreenState extends ConsumerState<ShareScreen>
    with SingleTickerProviderStateMixin {
  late TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 3, vsync: this);
    _tabController.addListener(() {
      if (!_tabController.indexIsChanging) {
        final tab = ShareTab.values[_tabController.index];
        ref
            .read(
              shareProvider((
                familyId: widget.familyId,
                familyName: widget.familyName,
              )).notifier,
            )
            .setTab(tab);
      }
    });
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    ref.watch(
      shareProvider((familyId: widget.familyId, familyName: widget.familyName)),
    );

    return DKScaffold(
      backgroundColor: _cBg,
      body: Column(
        children: [
          // ── Header ────────────────────────────────────────────────
          _ShareHeader(
            familyName: widget.familyName,
          ).animate().fadeIn(duration: 300.ms).slideY(begin: -0.05, end: 0),

          // ── Tab Bar ───────────────────────────────────────────────
          _ShareTabBar(
            tabController: _tabController,
          ).animate().fadeIn(duration: 300.ms, delay: 50.ms),

          const SizedBox(height: 12),

          // ── Tab Content ───────────────────────────────────────────
          Expanded(
            child: TabBarView(
              controller: _tabController,
              children: [
                // Tab 1: Invite
                _InviteTab(
                  familyId: widget.familyId,
                  familyName: widget.familyName,
                ),
                // Tab 2: Share Card
                _ShareCardTab(
                  familyId: widget.familyId,
                  familyName: widget.familyName,
                ),
                // Tab 3: Share Graph
                _ShareGraphTab(
                  familyId: widget.familyId,
                  familyName: widget.familyName,
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

// ═══════════════════════════════════════════════════════════════════════
// Header: "Share & Invite" with share icon
// ═══════════════════════════════════════════════════════════════════════

class _ShareHeader extends StatelessWidget {
  const _ShareHeader({required this.familyName});

  final String familyName;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.fromLTRB(
        KinrelSpacing.base,
        16,
        KinrelSpacing.base,
        8,
      ),
      decoration: BoxDecoration(
        color: _cBg,
        border: Border(
          bottom: BorderSide(
            color: Colors.white.withValues(alpha: 0.06),
            width: 0.5,
          ),
        ),
      ),
      child: Row(
        children: [
          // Back button
          GestureDetector(
            onTap: () => Navigator.of(context).pop(),
            child: Container(
              padding: const EdgeInsets.all(8),
              decoration: BoxDecoration(
                color: _cElevated,
                borderRadius: BorderRadius.circular(KinrelRadius.md),
              ),
              child: const Icon(
                Icons.arrow_back_rounded,
                color: _cTextSecondary,
                size: 20,
              ),
            ),
          ),
          const SizedBox(width: 14),
          // Share icon in orange
          Container(
            padding: const EdgeInsets.all(10),
            decoration: BoxDecoration(
              color: _cOrange.withValues(alpha: 0.12),
              borderRadius: BorderRadius.circular(KinrelRadius.md),
            ),
            child: const Icon(Icons.share_rounded, color: _cOrange, size: 22),
          ),
          const SizedBox(width: 14),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'Share & Invite',
                  style: TextStyle(
                    fontFamily: KinrelTypography.displayFont,
                    fontSize: 20,
                    fontWeight: FontWeight.w700,
                    color: _cTextPrimary,
                    letterSpacing: 0.3,
                  ),
                ),
                const SizedBox(height: 2),
                Text(
                  familyName,
                  style: TextStyle(
                    fontFamily: KinrelTypography.bodyFont,
                    fontSize: 12,
                    color: _cTextDim,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

// ═══════════════════════════════════════════════════════════════════════
// Tab Bar: "Invite" | "Share Card" | "Share Graph"
// ═══════════════════════════════════════════════════════════════════════

class _ShareTabBar extends StatelessWidget {
  const _ShareTabBar({required this.tabController});

  final TabController tabController;

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: KinrelSpacing.base),
      height: 44,
      decoration: BoxDecoration(
        color: _cCard,
        borderRadius: BorderRadius.circular(KinrelRadius.xl),
        border: Border.all(color: _cBorder, width: 1),
      ),
      child: TabBar(
        controller: tabController,
        indicator: BoxDecoration(
          gradient: KinrelGradients.igniteGradient,
          borderRadius: BorderRadius.circular(KinrelRadius.lg),
        ),
        indicatorSize: TabBarIndicatorSize.tab,
        indicatorPadding: const EdgeInsets.all(3),
        dividerColor: Colors.transparent,
        labelColor: Colors.white,
        unselectedLabelColor: _cTextDim,
        labelStyle: TextStyle(
          fontFamily: KinrelTypography.bodyFont,
          fontSize: 13,
          fontWeight: FontWeight.w600,
        ),
        unselectedLabelStyle: TextStyle(
          fontFamily: KinrelTypography.bodyFont,
          fontSize: 13,
          fontWeight: FontWeight.w500,
        ),
        tabs: const [
          Tab(text: 'Invite'),
          Tab(text: 'Share Card'),
          Tab(text: 'Share Graph'),
        ],
      ),
    );
  }
}

// ═══════════════════════════════════════════════════════════════════════
// Tab 1: Invite — 6 share method cards + active invite links
// ═══════════════════════════════════════════════════════════════════════

class _InviteTab extends ConsumerWidget {
  const _InviteTab({required this.familyId, required this.familyName});

  final String familyId;
  final String familyName;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final shareState = ref.watch(
      shareProvider((familyId: familyId, familyName: familyName)),
    );
    final notifier = ref.read(
      shareProvider((familyId: familyId, familyName: familyName)).notifier,
    );
    final primaryLink = shareState.primaryLink;

    return SingleChildScrollView(
      physics: const BouncingScrollPhysics(),
      padding: const EdgeInsets.fromLTRB(
        KinrelSpacing.base,
        0,
        KinrelSpacing.base,
        40,
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // ── Invite Link Card ───────────────────────────────────────
          if (primaryLink != null)
            _InviteLinkCard(
              link: primaryLink,
              copiedToClipboard: shareState.copiedToClipboard,
              onCopy: () {
                Clipboard.setData(ClipboardData(text: primaryLink.deepLink));
                notifier.markCopied();
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(
                    content: Text('Link copied to clipboard!'),
                    backgroundColor: _cCard,
                    behavior: SnackBarBehavior.floating,
                    duration: const Duration(seconds: 2),
                  ),
                );
              },
            ).animate().fadeIn(duration: 350.ms).slideY(begin: 0.06, end: 0),

          const SizedBox(height: 20),

          // ── "Choose how to invite" label ───────────────────────────
          Text(
            'Choose how to invite',
            style: TextStyle(
              fontFamily: KinrelTypography.bodyFont,
              fontSize: 14,
              fontWeight: FontWeight.w600,
              color: _cTextSecondary,
            ),
          ),

          const SizedBox(height: 12),

          // ── 6 Share Method Cards (2-column grid) ──────────────────
          _ShareMethodGrid(
                primaryLink: primaryLink,
                onCopy: () {
                  if (primaryLink != null) {
                    Clipboard.setData(
                      ClipboardData(text: primaryLink.deepLink),
                    );
                    notifier.markCopied();
                    ScaffoldMessenger.of(context).showSnackBar(
                      SnackBar(
                        content: Text('Link copied to clipboard!'),
                        backgroundColor: _cCard,
                        behavior: SnackBarBehavior.floating,
                        duration: const Duration(seconds: 2),
                      ),
                    );
                  }
                },
              )
              .animate()
              .fadeIn(duration: 350.ms, delay: 100.ms)
              .slideY(begin: 0.06, end: 0),

          const SizedBox(height: 24),

          // ── Generate New Link Button ──────────────────────────────
          GestureDetector(
            onTap: () => notifier.generateLink(),
            child: Container(
              width: double.infinity,
              padding: const EdgeInsets.symmetric(vertical: 14),
              decoration: BoxDecoration(
                gradient: KinrelGradients.igniteGradient,
                borderRadius: BorderRadius.circular(KinrelRadius.lg),
                boxShadow: [
                  BoxShadow(
                    color: _cOrange.withValues(alpha: 0.3),
                    blurRadius: 12,
                    offset: const Offset(0, 4),
                  ),
                ],
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const Icon(Icons.add_rounded, color: Colors.white, size: 20),
                  const SizedBox(width: 8),
                  Text(
                    'Generate New Link',
                    style: TextStyle(
                      fontFamily: KinrelTypography.bodyFont,
                      fontSize: 14,
                      fontWeight: FontWeight.w600,
                      color: Colors.white,
                      letterSpacing: 0.3,
                    ),
                  ),
                ],
              ),
            ),
          ),

          const SizedBox(height: 24),

          // ── Active Invite Links ───────────────────────────────────
          if (shareState.activeLinks.isNotEmpty) ...[
            Text(
              'Active Links',
              style: TextStyle(
                fontFamily: KinrelTypography.bodyFont,
                fontSize: 14,
                fontWeight: FontWeight.w600,
                color: _cTextSecondary,
              ),
            ),
            const SizedBox(height: 10),
            ...shareState.activeLinks.map(
              (link) => Padding(
                padding: const EdgeInsets.only(bottom: 10),
                child: _ActiveLinkTile(
                  link: link,
                  onDeactivate: () => notifier.deactivateLink(link.id),
                ),
              ),
            ),
          ],

          // ── Expired Links ─────────────────────────────────────────
          if (shareState.expiredLinks.isNotEmpty) ...[
            const SizedBox(height: 16),
            Text(
              'Expired Links',
              style: TextStyle(
                fontFamily: KinrelTypography.bodyFont,
                fontSize: 14,
                fontWeight: FontWeight.w600,
                color: _cTextDim,
              ),
            ),
            const SizedBox(height: 10),
            ...shareState.expiredLinks.map(
              (link) => Padding(
                padding: const EdgeInsets.only(bottom: 10),
                child: _ExpiredLinkTile(link: link),
              ),
            ),
          ],
        ],
      ),
    );
  }
}

// ═══════════════════════════════════════════════════════════════════════
// Invite Link Card — Deep link display with code, expiry info
// ═══════════════════════════════════════════════════════════════════════

class _InviteLinkCard extends StatelessWidget {
  const _InviteLinkCard({
    required this.link,
    required this.copiedToClipboard,
    required this.onCopy,
  });

  final InviteLink link;
  final bool copiedToClipboard;
  final VoidCallback onCopy;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(KinrelSpacing.xl),
      decoration: BoxDecoration(
        gradient: KinrelGradients.cardGradient,
        borderRadius: BorderRadius.circular(KinrelRadius.lg),
        border: Border.all(color: _cOrange.withValues(alpha: 0.15), width: 1),
        boxShadow: [
          BoxShadow(
            color: _cOrange.withValues(alpha: 0.05),
            blurRadius: 16,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // ── Top row: Icon + "Your Invite Link" ────────────────────
          Row(
            children: [
              Container(
                padding: const EdgeInsets.all(8),
                decoration: BoxDecoration(
                  color: _cOrange.withValues(alpha: 0.12),
                  borderRadius: BorderRadius.circular(KinrelRadius.sm),
                ),
                child: const Icon(
                  Icons.link_rounded,
                  color: _cOrange,
                  size: 18,
                ),
              ),
              const SizedBox(width: 10),
              Expanded(
                child: Text(
                  'Your Invite Link',
                  style: TextStyle(
                    fontFamily: KinrelTypography.bodyFont,
                    fontSize: 14,
                    fontWeight: FontWeight.w600,
                    color: _cTextPrimary,
                  ),
                ),
              ),
              // Copy button
              GestureDetector(
                onTap: onCopy,
                child: AnimatedContainer(
                  duration: KinrelMotion.fast,
                  padding: const EdgeInsets.symmetric(
                    horizontal: 12,
                    vertical: 6,
                  ),
                  decoration: BoxDecoration(
                    color: copiedToClipboard
                        ? KinrelColors.success.withValues(alpha: 0.15)
                        : _cOrange.withValues(alpha: 0.12),
                    borderRadius: BorderRadius.circular(KinrelRadius.full),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Icon(
                        copiedToClipboard
                            ? Icons.check_rounded
                            : Icons.copy_rounded,
                        size: 14,
                        color: copiedToClipboard
                            ? KinrelColors.success
                            : _cOrange,
                      ),
                      const SizedBox(width: 4),
                      Text(
                        copiedToClipboard ? 'Copied!' : 'Copy',
                        style: TextStyle(
                          fontFamily: KinrelTypography.bodyFont,
                          fontSize: 11,
                          fontWeight: FontWeight.w600,
                          color: copiedToClipboard
                              ? KinrelColors.success
                              : _cOrange,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),

          const SizedBox(height: 14),

          // ── Deep link display ─────────────────────────────────────
          Container(
            width: double.infinity,
            padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
            decoration: BoxDecoration(
              color: _cBg,
              borderRadius: BorderRadius.circular(KinrelRadius.md),
              border: Border.all(color: _cBorder, width: 1),
            ),
            child: Row(
              children: [
                // Orange link icon
                Container(
                  padding: const EdgeInsets.all(4),
                  decoration: BoxDecoration(
                    color: _cOrange.withValues(alpha: 0.1),
                    borderRadius: BorderRadius.circular(4),
                  ),
                  child: const Icon(
                    Icons.language_rounded,
                    color: _cOrange,
                    size: 14,
                  ),
                ),
                const SizedBox(width: 10),
                Expanded(
                  child: Text(
                    link.deepLink,
                    style: TextStyle(
                      fontFamily: KinrelTypography.monoFont,
                      fontSize: 14,
                      fontWeight: FontWeight.w500,
                      color: _cTextPrimary,
                      letterSpacing: 0.5,
                    ),
                  ),
                ),
              ],
            ),
          ),

          const SizedBox(height: 12),

          // ── Code + Expiry + Usage ─────────────────────────────────
          Row(
            children: [
              // Invite code
              _LinkInfoChip(
                icon: Icons.tag_rounded,
                label: link.code,
                color: _cOrange,
              ),
              const SizedBox(width: 8),
              // Expiry
              _LinkInfoChip(
                icon: Icons.schedule_rounded,
                label: link.expiryLabel,
                color: _cAmber,
              ),
              const Spacer(),
              // Usage
              _LinkInfoChip(
                icon: Icons.people_rounded,
                label: link.usageLabel,
                color: _cTextDim,
              ),
            ],
          ),
        ],
      ),
    );
  }
}

// ═══════════════════════════════════════════════════════════════════════
// Link Info Chip (reusable for invite link card)
// ═══════════════════════════════════════════════════════════════════════

class _LinkInfoChip extends StatelessWidget {
  const _LinkInfoChip({
    required this.icon,
    required this.label,
    required this.color,
  });

  final IconData icon;
  final String label;
  final Color color;

  @override
  Widget build(BuildContext context) {
    return Row(
      mainAxisSize: MainAxisSize.min,
      children: [
        Icon(icon, size: 12, color: color),
        const SizedBox(width: 4),
        Text(
          label,
          style: TextStyle(
            fontFamily: KinrelTypography.bodyFont,
            fontSize: 11,
            fontWeight: FontWeight.w500,
            color: color,
          ),
        ),
      ],
    );
  }
}

// ═══════════════════════════════════════════════════════════════════════
// Share Method Grid — 2-column grid of 6 invite methods
// ═══════════════════════════════════════════════════════════════════════

class _ShareMethodGrid extends StatelessWidget {
  const _ShareMethodGrid({required this.primaryLink, required this.onCopy});

  final InviteLink? primaryLink;
  final VoidCallback onCopy;

  static const _methods = [
    (
      type: InviteMethod.link,
      label: 'Link',
      icon: Icons.link_rounded,
      color: _cOrange,
    ),
    (
      type: InviteMethod.qrCode,
      label: 'QR Code',
      icon: Icons.qr_code_2_rounded,
      color: _cAmber,
    ),
    (
      type: InviteMethod.whatsapp,
      label: 'WhatsApp',
      icon: Icons.chat_rounded,
      color: _cWhatsApp,
    ),
    (
      type: InviteMethod.sms,
      label: 'SMS',
      icon: Icons.sms_rounded,
      color: _cSMS,
    ),
    (
      type: InviteMethod.email,
      label: 'Email',
      icon: Icons.email_rounded,
      color: _cEmail,
    ),
    (
      type: InviteMethod.copyLink,
      label: 'Copy Link',
      icon: Icons.copy_rounded,
      color: _cTextPrimary,
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return GridView.count(
      crossAxisCount: 2,
      shrinkWrap: true,
      physics: const NeverScrollableScrollPhysics(),
      mainAxisSpacing: 10,
      crossAxisSpacing: 10,
      childAspectRatio: 2.4,
      children: _methods
          .map(
            (m) => _ShareMethodCard(
              method: m.type,
              label: m.label,
              icon: m.icon,
              color: m.color,
              primaryLink: primaryLink,
              onCopy: onCopy,
            ),
          )
          .toList(),
    );
  }
}

// ═══════════════════════════════════════════════════════════════════════
// Share Method Card — Individual invite method tile
// ═══════════════════════════════════════════════════════════════════════

class _ShareMethodCard extends StatelessWidget {
  const _ShareMethodCard({
    required this.method,
    required this.label,
    required this.icon,
    required this.color,
    required this.primaryLink,
    required this.onCopy,
  });

  final InviteMethod method;
  final String label;
  final IconData icon;
  final Color color;
  final InviteLink? primaryLink;
  final VoidCallback onCopy;

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => _handleTap(context),
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
        decoration: BoxDecoration(
          color: _cCard,
          borderRadius: BorderRadius.circular(KinrelRadius.lg),
          border: Border.all(color: color.withValues(alpha: 0.12), width: 1),
        ),
        child: Row(
          children: [
            Container(
              padding: const EdgeInsets.all(8),
              decoration: BoxDecoration(
                color: color.withValues(alpha: 0.12),
                borderRadius: BorderRadius.circular(KinrelRadius.md),
              ),
              child: Icon(icon, size: 20, color: color),
            ),
            const SizedBox(width: 10),
            Expanded(
              child: Text(
                label,
                style: TextStyle(
                  fontFamily: KinrelTypography.bodyFont,
                  fontSize: 13,
                  fontWeight: FontWeight.w600,
                  color: _cTextPrimary,
                ),
              ),
            ),
            Icon(Icons.chevron_right_rounded, size: 18, color: _cTextDim),
          ],
        ),
      ),
    );
  }

  void _handleTap(BuildContext context) {
    switch (method) {
      case InviteMethod.link:
        _showLinkDialog(context);
      case InviteMethod.qrCode:
        _showQRCodeSheet(context);
      case InviteMethod.whatsapp:
        _showWhatsAppSheet(context);
      case InviteMethod.sms:
        _showSMSSheet(context);
      case InviteMethod.email:
        _showEmailSheet(context);
      case InviteMethod.copyLink:
        onCopy();
    }
  }

  void _showLinkDialog(BuildContext context) {
    showModalBottomSheet(
      context: context,
      backgroundColor: _cCard,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(
          top: Radius.circular(KinrelRadius.bottomSheet),
        ),
      ),
      builder: (ctx) => _LinkDetailSheet(link: primaryLink, onCopy: onCopy),
    );
  }

  void _showQRCodeSheet(BuildContext context) {
    showModalBottomSheet(
      context: context,
      backgroundColor: _cCard,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(
          top: Radius.circular(KinrelRadius.bottomSheet),
        ),
      ),
      builder: (ctx) => _QRCodeSheet(link: primaryLink),
    );
  }

  void _showWhatsAppSheet(BuildContext context) {
    showModalBottomSheet(
      context: context,
      backgroundColor: _cCard,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(
          top: Radius.circular(KinrelRadius.bottomSheet),
        ),
      ),
      builder: (ctx) => _WhatsAppSheet(link: primaryLink),
    );
  }

  void _showSMSSheet(BuildContext context) {
    showModalBottomSheet(
      context: context,
      backgroundColor: _cCard,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(
          top: Radius.circular(KinrelRadius.bottomSheet),
        ),
      ),
      builder: (ctx) => _SMSSheet(link: primaryLink),
    );
  }

  void _showEmailSheet(BuildContext context) {
    showModalBottomSheet(
      context: context,
      backgroundColor: _cCard,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(
          top: Radius.circular(KinrelRadius.bottomSheet),
        ),
      ),
      builder: (ctx) => _EmailSheet(link: primaryLink),
    );
  }
}

// ═══════════════════════════════════════════════════════════════════════
// Active Link Tile — for the links list
// ═══════════════════════════════════════════════════════════════════════

class _ActiveLinkTile extends StatelessWidget {
  const _ActiveLinkTile({required this.link, required this.onDeactivate});

  final InviteLink link;
  final VoidCallback onDeactivate;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: _cCard,
        borderRadius: BorderRadius.circular(KinrelRadius.lg),
        border: Border.all(color: _cWhatsApp.withValues(alpha: 0.08), width: 1),
      ),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: _cWhatsApp.withValues(alpha: 0.1),
              borderRadius: BorderRadius.circular(KinrelRadius.sm),
            ),
            child: const Icon(Icons.link_rounded, color: _cWhatsApp, size: 16),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  link.deepLink,
                  style: TextStyle(
                    fontFamily: KinrelTypography.monoFont,
                    fontSize: 12,
                    fontWeight: FontWeight.w500,
                    color: _cTextPrimary,
                  ),
                ),
                const SizedBox(height: 3),
                Row(
                  children: [
                    Text(
                      link.expiryLabel,
                      style: TextStyle(
                        fontFamily: KinrelTypography.bodyFont,
                        fontSize: 11,
                        color: _cAmber,
                      ),
                    ),
                    const SizedBox(width: 10),
                    Text(
                      link.usageLabel,
                      style: TextStyle(
                        fontFamily: KinrelTypography.bodyFont,
                        fontSize: 11,
                        color: _cTextDim,
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
          // Deactivate button
          GestureDetector(
            onTap: onDeactivate,
            child: Container(
              padding: const EdgeInsets.all(6),
              decoration: BoxDecoration(
                color: Colors.red.withValues(alpha: 0.1),
                borderRadius: BorderRadius.circular(KinrelRadius.sm),
              ),
              child: const Icon(
                Icons.block_rounded,
                color: Colors.redAccent,
                size: 16,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

// ═══════════════════════════════════════════════════════════════════════
// Expired Link Tile
// ═══════════════════════════════════════════════════════════════════════

class _ExpiredLinkTile extends StatelessWidget {
  const _ExpiredLinkTile({required this.link});

  final InviteLink link;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: _cCard,
        borderRadius: BorderRadius.circular(KinrelRadius.lg),
        border: Border.all(color: _cBorder.withValues(alpha: 0.5), width: 1),
      ),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: _cTextDim.withValues(alpha: 0.1),
              borderRadius: BorderRadius.circular(KinrelRadius.sm),
            ),
            child: Icon(Icons.link_off_rounded, color: _cTextDim, size: 16),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  link.deepLink,
                  style: TextStyle(
                    fontFamily: KinrelTypography.monoFont,
                    fontSize: 12,
                    fontWeight: FontWeight.w500,
                    color: _cTextDim,
                    decoration: TextDecoration.lineThrough,
                  ),
                ),
                const SizedBox(height: 3),
                Text(
                  'Expired · ${link.formattedCreatedDate}',
                  style: TextStyle(
                    fontFamily: KinrelTypography.bodyFont,
                    fontSize: 11,
                    color: _cTextDim,
                  ),
                ),
              ],
            ),
          ),
          Text(
            '${link.usedCount} joined',
            style: TextStyle(
              fontFamily: KinrelTypography.bodyFont,
              fontSize: 11,
              fontWeight: FontWeight.w500,
              color: _cTextDim,
            ),
          ),
        ],
      ),
    );
  }
}

// ═══════════════════════════════════════════════════════════════════════
// Bottom Sheets for Invite Methods
// ═══════════════════════════════════════════════════════════════════════

// ── Link Detail Sheet ────────────────────────────────────────────────

class _LinkDetailSheet extends StatelessWidget {
  const _LinkDetailSheet({required this.link, required this.onCopy});

  final InviteLink? link;
  final VoidCallback onCopy;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(KinrelSpacing.xl),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          // Handle
          Center(
            child: Container(
              width: 40,
              height: 4,
              decoration: BoxDecoration(
                color: _cBorder,
                borderRadius: BorderRadius.circular(2),
              ),
            ),
          ),
          const SizedBox(height: 20),

          // Icon
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: _cOrange.withValues(alpha: 0.12),
              shape: BoxShape.circle,
            ),
            child: const Icon(Icons.link_rounded, color: _cOrange, size: 32),
          ),
          const SizedBox(height: 16),

          Text(
            'Share Invite Link',
            style: TextStyle(
              fontFamily: KinrelTypography.displayFont,
              fontSize: 20,
              fontWeight: FontWeight.w700,
              color: _cTextPrimary,
            ),
          ),
          const SizedBox(height: 8),
          Text(
            'Anyone with this link can join your family on Kinrel.',
            textAlign: TextAlign.center,
            style: TextStyle(
              fontFamily: KinrelTypography.bodyFont,
              fontSize: 13,
              color: _cTextSecondary,
              height: 1.5,
            ),
          ),
          const SizedBox(height: 16),

          // Link display
          Container(
            width: double.infinity,
            padding: const EdgeInsets.all(14),
            decoration: BoxDecoration(
              color: _cBg,
              borderRadius: BorderRadius.circular(KinrelRadius.md),
              border: Border.all(color: _cBorder),
            ),
            child: Text(
              link?.deepLink ?? 'kinrel.app/invite/...',
              style: TextStyle(
                fontFamily: KinrelTypography.monoFont,
                fontSize: 15,
                fontWeight: FontWeight.w500,
                color: _cTextPrimary,
                letterSpacing: 0.5,
              ),
              textAlign: TextAlign.center,
            ),
          ),
          const SizedBox(height: 16),

          // Copy button
          GestureDetector(
            onTap: () {
              onCopy();
              Navigator.of(context).pop();
            },
            child: Container(
              width: double.infinity,
              padding: const EdgeInsets.symmetric(vertical: 14),
              decoration: BoxDecoration(
                gradient: KinrelGradients.igniteGradient,
                borderRadius: BorderRadius.circular(KinrelRadius.lg),
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const Icon(Icons.copy_rounded, color: Colors.white, size: 18),
                  const SizedBox(width: 8),
                  Text(
                    'Copy Link',
                    style: TextStyle(
                      fontFamily: KinrelTypography.bodyFont,
                      fontSize: 14,
                      fontWeight: FontWeight.w600,
                      color: Colors.white,
                    ),
                  ),
                ],
              ),
            ),
          ),
          const SizedBox(height: 12),

          // Share button
          GestureDetector(
            onTap: () {
              Navigator.of(context).pop();
              if (link != null) {
                ShareHelper.shareInvite(
                  inviteCode: link!.code,
                  familyName: link!.familyName,
                );
              }
            },
            child: Container(
              width: double.infinity,
              padding: const EdgeInsets.symmetric(vertical: 14),
              decoration: BoxDecoration(
                color: _cElevated,
                borderRadius: BorderRadius.circular(KinrelRadius.lg),
                border: Border.all(color: _cBorder),
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const Icon(
                    Icons.share_rounded,
                    color: _cTextSecondary,
                    size: 18,
                  ),
                  const SizedBox(width: 8),
                  Text(
                    'Share via...',
                    style: TextStyle(
                      fontFamily: KinrelTypography.bodyFont,
                      fontSize: 14,
                      fontWeight: FontWeight.w600,
                      color: _cTextPrimary,
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

// ── QR Code Sheet ────────────────────────────────────────────────────

class _QRCodeSheet extends StatelessWidget {
  const _QRCodeSheet({required this.link});

  final InviteLink? link;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(KinrelSpacing.xl),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          // Handle
          Center(
            child: Container(
              width: 40,
              height: 4,
              decoration: BoxDecoration(
                color: _cBorder,
                borderRadius: BorderRadius.circular(2),
              ),
            ),
          ),
          const SizedBox(height: 20),

          // QR Code Card — styled with dashed border + K-graph logo center
          Container(
            width: 240,
            height: 240,
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(KinrelRadius.xl),
              // Dashed border via custom painter
              border: Border.all(
                color: _cAmber.withValues(alpha: 0.3),
                width: 2,
              ),
            ),
            child: CustomPaint(
              painter: _DashedBorderPainter(
                color: _cAmber.withValues(alpha: 0.5),
                borderRadius: KinrelRadius.xl,
              ),
              child: Center(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    // K-graph logo placeholder in center
                    Container(
                      width: 56,
                      height: 56,
                      decoration: BoxDecoration(
                        gradient: KinrelGradients.igniteGradient,
                        borderRadius: BorderRadius.circular(KinrelRadius.md),
                      ),
                      child: const Center(
                        child: Text(
                          'K',
                          style: TextStyle(
                            fontFamily: 'Outfit',
                            fontSize: 28,
                            fontWeight: FontWeight.w800,
                            color: Colors.white,
                            height: 1,
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(height: 10),
                    // QR code placeholder pattern
                    Icon(Icons.qr_code_2_rounded, size: 80, color: _cBg),
                  ],
                ),
              ),
            ),
          ),
          const SizedBox(height: 16),

          Text(
            'Scan to Join',
            style: TextStyle(
              fontFamily: KinrelTypography.displayFont,
              fontSize: 18,
              fontWeight: FontWeight.w700,
              color: _cTextPrimary,
            ),
          ),
          const SizedBox(height: 6),
          Text(
            link?.deepLink ?? 'kinrel.app/invite/...',
            style: TextStyle(
              fontFamily: KinrelTypography.monoFont,
              fontSize: 12,
              fontWeight: FontWeight.w500,
              color: _cAmber,
              letterSpacing: 0.5,
            ),
          ),
          const SizedBox(height: 16),

          // Save QR button
          GestureDetector(
            onTap: () => Navigator.of(context).pop(),
            child: Container(
              width: double.infinity,
              padding: const EdgeInsets.symmetric(vertical: 14),
              decoration: BoxDecoration(
                gradient: KinrelGradients.igniteGradient,
                borderRadius: BorderRadius.circular(KinrelRadius.lg),
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const Icon(
                    Icons.save_alt_rounded,
                    color: Colors.white,
                    size: 18,
                  ),
                  const SizedBox(width: 8),
                  Text(
                    'Save QR Code',
                    style: TextStyle(
                      fontFamily: KinrelTypography.bodyFont,
                      fontSize: 14,
                      fontWeight: FontWeight.w600,
                      color: Colors.white,
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

// ── Dashed Border Painter ────────────────────────────────────────────

class _DashedBorderPainter extends CustomPainter {
  _DashedBorderPainter({required this.color, required this.borderRadius});

  final Color color;
  final double borderRadius;

  @override
  void paint(Canvas canvas, Size size) {
    final paint = Paint()
      ..color = color
      ..strokeWidth = 2
      ..style = PaintingStyle.stroke;

    final dashWidth = 8.0;
    final dashSpace = 6.0;
    final rect = RRect.fromRectAndRadius(
      Rect.fromLTWH(0, 0, size.width, size.height),
      Radius.circular(borderRadius),
    );

    final path = Path()..addRRect(rect);
    final metrics = path.computeMetrics();

    for (final metric in metrics) {
      double distance = 0;
      while (distance < metric.length) {
        final end = (distance + dashWidth) < metric.length
            ? distance + dashWidth
            : metric.length;
        canvas.drawPath(metric.extractPath(distance, end), paint);
        distance += dashWidth + dashSpace;
      }
    }
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => false;
}

// ── WhatsApp Sheet ───────────────────────────────────────────────────

class _WhatsAppSheet extends StatelessWidget {
  const _WhatsAppSheet({required this.link});

  final InviteLink? link;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(KinrelSpacing.xl),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          // Handle
          Center(
            child: Container(
              width: 40,
              height: 4,
              decoration: BoxDecoration(
                color: _cBorder,
                borderRadius: BorderRadius.circular(2),
              ),
            ),
          ),
          const SizedBox(height: 20),

          // WhatsApp icon
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: _cWhatsApp.withValues(alpha: 0.12),
              shape: BoxShape.circle,
            ),
            child: const Icon(Icons.chat_rounded, color: _cWhatsApp, size: 32),
          ),
          const SizedBox(height: 16),

          Text(
            'Share via WhatsApp',
            style: TextStyle(
              fontFamily: KinrelTypography.displayFont,
              fontSize: 20,
              fontWeight: FontWeight.w700,
              color: _cTextPrimary,
            ),
          ),
          const SizedBox(height: 12),

          // Pre-formatted message preview
          Container(
            width: double.infinity,
            padding: const EdgeInsets.all(14),
            decoration: BoxDecoration(
              color: _cBg,
              borderRadius: BorderRadius.circular(KinrelRadius.md),
              border: Border.all(color: _cBorder),
            ),
            child: Text(
              link?.whatsappMessage ?? '',
              style: TextStyle(
                fontFamily: KinrelTypography.bodyFont,
                fontSize: 13,
                color: _cTextSecondary,
                height: 1.6,
              ),
            ),
          ),
          const SizedBox(height: 16),

          // Send via WhatsApp button
          GestureDetector(
            onTap: () {
              Navigator.of(context).pop();
              if (link != null) {
                ShareHelper.shareInvite(
                  inviteCode: link!.code,
                  familyName: link!.familyName,
                );
              }
            },
            child: Container(
              width: double.infinity,
              padding: const EdgeInsets.symmetric(vertical: 14),
              decoration: BoxDecoration(
                color: _cWhatsApp,
                borderRadius: BorderRadius.circular(KinrelRadius.lg),
                boxShadow: [
                  BoxShadow(
                    color: _cWhatsApp.withValues(alpha: 0.3),
                    blurRadius: 12,
                    offset: const Offset(0, 4),
                  ),
                ],
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const Icon(Icons.chat_rounded, color: Colors.white, size: 20),
                  const SizedBox(width: 8),
                  Text(
                    'Send on WhatsApp',
                    style: TextStyle(
                      fontFamily: KinrelTypography.bodyFont,
                      fontSize: 14,
                      fontWeight: FontWeight.w600,
                      color: Colors.white,
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

// ── SMS Sheet ────────────────────────────────────────────────────────

class _SMSSheet extends StatelessWidget {
  const _SMSSheet({required this.link});

  final InviteLink? link;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(KinrelSpacing.xl),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Center(
            child: Container(
              width: 40,
              height: 4,
              decoration: BoxDecoration(
                color: _cBorder,
                borderRadius: BorderRadius.circular(2),
              ),
            ),
          ),
          const SizedBox(height: 20),
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: _cSMS.withValues(alpha: 0.12),
              shape: BoxShape.circle,
            ),
            child: const Icon(Icons.sms_rounded, color: _cSMS, size: 32),
          ),
          const SizedBox(height: 16),
          Text(
            'Send via SMS',
            style: TextStyle(
              fontFamily: KinrelTypography.displayFont,
              fontSize: 20,
              fontWeight: FontWeight.w700,
              color: _cTextPrimary,
            ),
          ),
          const SizedBox(height: 12),
          Container(
            width: double.infinity,
            padding: const EdgeInsets.all(14),
            decoration: BoxDecoration(
              color: _cBg,
              borderRadius: BorderRadius.circular(KinrelRadius.md),
              border: Border.all(color: _cBorder),
            ),
            child: Text(
              link?.smsMessage ?? '',
              style: TextStyle(
                fontFamily: KinrelTypography.bodyFont,
                fontSize: 13,
                color: _cTextSecondary,
                height: 1.6,
              ),
            ),
          ),
          const SizedBox(height: 16),
          GestureDetector(
            onTap: () {
              Navigator.of(context).pop();
              if (link != null) {
                ShareHelper.shareInvite(
                  inviteCode: link!.code,
                  familyName: link!.familyName,
                );
              }
            },
            child: Container(
              width: double.infinity,
              padding: const EdgeInsets.symmetric(vertical: 14),
              decoration: BoxDecoration(
                color: _cSMS,
                borderRadius: BorderRadius.circular(KinrelRadius.lg),
                boxShadow: [
                  BoxShadow(
                    color: _cSMS.withValues(alpha: 0.3),
                    blurRadius: 12,
                    offset: const Offset(0, 4),
                  ),
                ],
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const Icon(Icons.sms_rounded, color: Colors.white, size: 20),
                  const SizedBox(width: 8),
                  Text(
                    'Send SMS',
                    style: TextStyle(
                      fontFamily: KinrelTypography.bodyFont,
                      fontSize: 14,
                      fontWeight: FontWeight.w600,
                      color: Colors.white,
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

// ── Email Sheet ──────────────────────────────────────────────────────

class _EmailSheet extends StatelessWidget {
  const _EmailSheet({required this.link});

  final InviteLink? link;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(KinrelSpacing.xl),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Center(
            child: Container(
              width: 40,
              height: 4,
              decoration: BoxDecoration(
                color: _cBorder,
                borderRadius: BorderRadius.circular(2),
              ),
            ),
          ),
          const SizedBox(height: 20),
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: _cEmail.withValues(alpha: 0.12),
              shape: BoxShape.circle,
            ),
            child: const Icon(Icons.email_rounded, color: _cEmail, size: 32),
          ),
          const SizedBox(height: 16),
          Text(
            'Send via Email',
            style: TextStyle(
              fontFamily: KinrelTypography.displayFont,
              fontSize: 20,
              fontWeight: FontWeight.w700,
              color: _cTextPrimary,
            ),
          ),
          const SizedBox(height: 12),

          // Subject
          Container(
            width: double.infinity,
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: _cBg,
              borderRadius: BorderRadius.only(
                topLeft: Radius.circular(KinrelRadius.md),
                topRight: Radius.circular(KinrelRadius.md),
              ),
              border: Border.all(color: _cBorder),
            ),
            child: Row(
              children: [
                Text(
                  'Subject: ',
                  style: TextStyle(
                    fontFamily: KinrelTypography.bodyFont,
                    fontSize: 12,
                    fontWeight: FontWeight.w600,
                    color: _cTextDim,
                  ),
                ),
                Expanded(
                  child: Text(
                    link?.emailSubject ?? '',
                    style: TextStyle(
                      fontFamily: KinrelTypography.bodyFont,
                      fontSize: 12,
                      color: _cTextPrimary,
                    ),
                  ),
                ),
              ],
            ),
          ),

          // Body
          Container(
            width: double.infinity,
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: _cBg,
              borderRadius: BorderRadius.only(
                bottomLeft: Radius.circular(KinrelRadius.md),
                bottomRight: Radius.circular(KinrelRadius.md),
              ),
              border: Border(
                left: BorderSide(color: _cBorder),
                right: BorderSide(color: _cBorder),
                bottom: BorderSide(color: _cBorder),
              ),
            ),
            child: Text(
              link?.emailBody ?? '',
              style: TextStyle(
                fontFamily: KinrelTypography.bodyFont,
                fontSize: 13,
                color: _cTextSecondary,
                height: 1.6,
              ),
            ),
          ),
          const SizedBox(height: 16),
          GestureDetector(
            onTap: () {
              Navigator.of(context).pop();
              if (link != null) {
                ShareHelper.shareInvite(
                  inviteCode: link!.code,
                  familyName: link!.familyName,
                );
              }
            },
            child: Container(
              width: double.infinity,
              padding: const EdgeInsets.symmetric(vertical: 14),
              decoration: BoxDecoration(
                gradient: KinrelGradients.igniteGradient,
                borderRadius: BorderRadius.circular(KinrelRadius.lg),
                boxShadow: [
                  BoxShadow(
                    color: _cOrange.withValues(alpha: 0.3),
                    blurRadius: 12,
                    offset: const Offset(0, 4),
                  ),
                ],
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const Icon(
                    Icons.email_rounded,
                    color: Colors.white,
                    size: 20,
                  ),
                  const SizedBox(width: 8),
                  Text(
                    'Open Email App',
                    style: TextStyle(
                      fontFamily: KinrelTypography.bodyFont,
                      fontSize: 14,
                      fontWeight: FontWeight.w600,
                      color: Colors.white,
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

// ═══════════════════════════════════════════════════════════════════════
// Tab 2: Share Card — Kinship term sharing with beautiful card design
// ═══════════════════════════════════════════════════════════════════════

class _ShareCardTab extends ConsumerStatefulWidget {
  const _ShareCardTab({required this.familyId, required this.familyName});

  final String familyId;
  final String familyName;

  @override
  ConsumerState<_ShareCardTab> createState() => _ShareCardTabState();
}

class _ShareCardTabState extends ConsumerState<_ShareCardTab> {
  int _selectedIndex = 0;

  @override
  Widget build(BuildContext context) {
    final shareState = ref.watch(
      shareProvider((familyId: widget.familyId, familyName: widget.familyName)),
    );
    final cards = shareState.kinshipCards;
    if (cards.isEmpty) return _buildEmptyState();

    final card = cards[_selectedIndex];

    return SingleChildScrollView(
      physics: const BouncingScrollPhysics(),
      padding: const EdgeInsets.fromLTRB(
        KinrelSpacing.base,
        0,
        KinrelSpacing.base,
        40,
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // ── "What do I call [name]?" section ──────────────────────
          Text(
            card.questionText,
            style: TextStyle(
              fontFamily: KinrelTypography.displayFont,
              fontSize: 22,
              fontWeight: FontWeight.w700,
              color: _cTextPrimary,
              letterSpacing: 0.3,
            ),
          ).animate().fadeIn(duration: 350.ms).slideY(begin: 0.06, end: 0),

          const SizedBox(height: 16),

          // ── Beautiful Kinship Card ────────────────────────────────
          _KinshipCardWidget(card: card)
              .animate()
              .fadeIn(duration: 400.ms, delay: 100.ms)
              .slideY(begin: 0.08, end: 0),

          const SizedBox(height: 20),

          // ── Card Selector (horizontal scroll of kinship terms) ────
          Text(
            'Choose a kinship card',
            style: TextStyle(
              fontFamily: KinrelTypography.bodyFont,
              fontSize: 13,
              fontWeight: FontWeight.w600,
              color: _cTextSecondary,
            ),
          ),
          const SizedBox(height: 10),

          SizedBox(
            height: 52,
            child: ListView.separated(
              scrollDirection: Axis.horizontal,
              itemCount: cards.length,
              separatorBuilder: (_, __) => const SizedBox(width: 8),
              itemBuilder: (context, index) {
                final c = cards[index];
                final isSelected = index == _selectedIndex;
                return GestureDetector(
                  onTap: () => setState(() => _selectedIndex = index),
                  child: AnimatedContainer(
                    duration: KinrelMotion.fast,
                    padding: const EdgeInsets.symmetric(
                      horizontal: 14,
                      vertical: 10,
                    ),
                    decoration: BoxDecoration(
                      gradient: isSelected
                          ? KinrelGradients.igniteGradient
                          : null,
                      color: isSelected ? null : _cCard,
                      borderRadius: BorderRadius.circular(KinrelRadius.lg),
                      border: isSelected ? null : Border.all(color: _cBorder),
                    ),
                    child: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Text(
                          c.kinshipTermRegional,
                          style: TextStyle(
                            fontFamily: KinrelTypography.displayFont,
                            fontSize: 16,
                            fontWeight: FontWeight.w700,
                            color: isSelected ? Colors.white : _cOrange,
                            height: 1,
                          ),
                        ),
                        const SizedBox(width: 6),
                        Text(
                          c.personName.split(' ').first,
                          style: TextStyle(
                            fontFamily: KinrelTypography.bodyFont,
                            fontSize: 11,
                            fontWeight: FontWeight.w500,
                            color: isSelected
                                ? Colors.white.withValues(alpha: 0.8)
                                : _cTextDim,
                          ),
                        ),
                      ],
                    ),
                  ),
                );
              },
            ),
          ),

          const SizedBox(height: 20),

          // ── Share Buttons ─────────────────────────────────────────
          Row(
            children: [
              // Share to WhatsApp Status
              Expanded(
                child: GestureDetector(
                  onTap: () {
                    Clipboard.setData(
                      ClipboardData(text: card.whatsappStatusText),
                    );
                    ScaffoldMessenger.of(context).showSnackBar(
                      SnackBar(
                        content: Text('Copied for WhatsApp Status!'),
                        backgroundColor: _cCard,
                        behavior: SnackBarBehavior.floating,
                      ),
                    );
                  },
                  child: Container(
                    padding: const EdgeInsets.symmetric(vertical: 14),
                    decoration: BoxDecoration(
                      color: _cWhatsApp,
                      borderRadius: BorderRadius.circular(KinrelRadius.lg),
                      boxShadow: [
                        BoxShadow(
                          color: _cWhatsApp.withValues(alpha: 0.25),
                          blurRadius: 10,
                          offset: const Offset(0, 3),
                        ),
                      ],
                    ),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        const Icon(
                          Icons.chat_rounded,
                          color: Colors.white,
                          size: 18,
                        ),
                        const SizedBox(width: 8),
                        Flexible(
                          child: Text(
                            'WhatsApp Status',
                            style: TextStyle(
                              fontFamily: KinrelTypography.bodyFont,
                              fontSize: 13,
                              fontWeight: FontWeight.w600,
                              color: Colors.white,
                            ),
                            overflow: TextOverflow.ellipsis,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              const SizedBox(width: 10),
              // General Share Sheet
              Expanded(
                child: GestureDetector(
                  onTap: () {
                    Clipboard.setData(ClipboardData(text: card.shareText));
                    ScaffoldMessenger.of(context).showSnackBar(
                      SnackBar(
                        content: Text('Copied to clipboard!'),
                        backgroundColor: _cCard,
                        behavior: SnackBarBehavior.floating,
                      ),
                    );
                  },
                  child: Container(
                    padding: const EdgeInsets.symmetric(vertical: 14),
                    decoration: BoxDecoration(
                      gradient: KinrelGradients.igniteGradient,
                      borderRadius: BorderRadius.circular(KinrelRadius.lg),
                      boxShadow: [
                        BoxShadow(
                          color: _cOrange.withValues(alpha: 0.25),
                          blurRadius: 10,
                          offset: const Offset(0, 3),
                        ),
                      ],
                    ),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        const Icon(
                          Icons.share_rounded,
                          color: Colors.white,
                          size: 18,
                        ),
                        const SizedBox(width: 8),
                        Flexible(
                          child: Text(
                            'Share',
                            style: TextStyle(
                              fontFamily: KinrelTypography.bodyFont,
                              fontSize: 13,
                              fontWeight: FontWeight.w600,
                              color: Colors.white,
                            ),
                            overflow: TextOverflow.ellipsis,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildEmptyState() {
    return Center(
      child: Padding(
        padding: const EdgeInsets.symmetric(horizontal: KinrelSpacing.xxl),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Container(
              width: 100,
              height: 100,
              decoration: BoxDecoration(
                color: _cOrange.withValues(alpha: 0.08),
                shape: BoxShape.circle,
              ),
              child: Icon(
                Icons.style_rounded,
                size: 48,
                color: _cOrange.withValues(alpha: 0.3),
              ),
            ),
            const SizedBox(height: 20),
            Text(
              'No kinship cards yet',
              style: TextStyle(
                fontFamily: KinrelTypography.displayFont,
                fontSize: 18,
                fontWeight: FontWeight.w700,
                color: _cTextPrimary,
              ),
            ),
            const SizedBox(height: 8),
            Text(
              'Find a kinship term to create a shareable card.',
              textAlign: TextAlign.center,
              style: TextStyle(
                fontFamily: KinrelTypography.bodyFont,
                fontSize: 13,
                color: _cTextSecondary,
                height: 1.5,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

// ═══════════════════════════════════════════════════════════════════════
// Kinship Card Widget — Beautiful shareable card
// ═══════════════════════════════════════════════════════════════════════

class _KinshipCardWidget extends StatelessWidget {
  const _KinshipCardWidget({required this.card});

  final KinshipShareCard card;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(KinrelRadius.xl),
        gradient: LinearGradient(
          colors: [Color(0xFF1E1028), Color(0xFF191B2C), Color(0xFF1A1420)],
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
        ),
        border: Border.all(color: _cOrange.withValues(alpha: 0.2), width: 1.5),
        boxShadow: [
          BoxShadow(
            color: _cOrange.withValues(alpha: 0.08),
            blurRadius: 24,
            offset: const Offset(0, 8),
          ),
        ],
      ),
      child: Stack(
        children: [
          // Background Ignite gradient accent (top-right corner glow)
          Positioned(
            top: -30,
            right: -30,
            child: Container(
              width: 140,
              height: 140,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                gradient: RadialGradient(
                  colors: [
                    _cOrange.withValues(alpha: 0.15),
                    Colors.transparent,
                  ],
                ),
              ),
            ),
          ),

          // Bottom-left subtle glow
          Positioned(
            bottom: -20,
            left: -20,
            child: Container(
              width: 100,
              height: 100,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                gradient: RadialGradient(
                  colors: [_cAmber.withValues(alpha: 0.08), Colors.transparent],
                ),
              ),
            ),
          ),

          // Content
          Padding(
            padding: const EdgeInsets.all(KinrelSpacing.xl),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // ── Top: "What do I call [name]?" ────────────────────
                Row(
                  children: [
                    Container(
                      padding: const EdgeInsets.symmetric(
                        horizontal: 8,
                        vertical: 4,
                      ),
                      decoration: BoxDecoration(
                        color: _cOrange.withValues(alpha: 0.12),
                        borderRadius: BorderRadius.circular(KinrelRadius.xs),
                      ),
                      child: Text(
                        card.languageName,
                        style: TextStyle(
                          fontFamily: KinrelTypography.monoFont,
                          fontSize: 10,
                          fontWeight: FontWeight.w500,
                          color: _cOrange,
                          letterSpacing: 0.5,
                        ),
                      ),
                    ),
                    const SizedBox(width: 6),
                    Text(
                      card.languageScript,
                      style: TextStyle(
                        fontFamily: KinrelTypography.bodyFont,
                        fontSize: 10,
                        color: _cTextDim,
                      ),
                    ),
                  ],
                ),

                const SizedBox(height: 20),

                // ── Person name ──────────────────────────────────────
                Text(
                  card.personName,
                  style: TextStyle(
                    fontFamily: KinrelTypography.bodyFont,
                    fontSize: 14,
                    fontWeight: FontWeight.w500,
                    color: _cTextSecondary,
                  ),
                ),

                const SizedBox(height: 8),

                // ── Regional kinship term (LARGE, ORANGE) ────────────
                Text(
                  card.kinshipTermRegional,
                  style: TextStyle(
                    fontFamily: KinrelTypography.displayFont,
                    fontSize: 56,
                    fontWeight: FontWeight.w800,
                    color: _cOrange,
                    height: 1.1,
                    letterSpacing: 2,
                  ),
                ),

                const SizedBox(height: 8),

                // ── English translation ──────────────────────────────
                Text(
                  card.kinshipTermEnglish,
                  style: TextStyle(
                    fontFamily: KinrelTypography.bodyFont,
                    fontSize: 16,
                    fontWeight: FontWeight.w500,
                    color: _cTextPrimary,
                    height: 1.4,
                  ),
                ),

                const SizedBox(height: 16),

                // ── Relationship path ────────────────────────────────
                Container(
                  width: double.infinity,
                  padding: const EdgeInsets.symmetric(
                    horizontal: 12,
                    vertical: 10,
                  ),
                  decoration: BoxDecoration(
                    color: _cBg.withValues(alpha: 0.5),
                    borderRadius: BorderRadius.circular(KinrelRadius.md),
                    border: Border.all(
                      color: _cOrange.withValues(alpha: 0.1),
                      width: 1,
                    ),
                  ),
                  child: Row(
                    children: [
                      Icon(Icons.route_rounded, size: 14, color: _cAmber),
                      const SizedBox(width: 8),
                      Expanded(
                        child: Text(
                          card.relationshipPath,
                          style: TextStyle(
                            fontFamily: KinrelTypography.monoFont,
                            fontSize: 12,
                            fontWeight: FontWeight.w400,
                            color: _cTextSecondary,
                            letterSpacing: 0.3,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),

                const SizedBox(height: 20),

                // ── "Generated by Kinrel" branding ───────────────────
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Container(
                      width: 16,
                      height: 16,
                      decoration: BoxDecoration(
                        gradient: KinrelGradients.igniteGradient,
                        borderRadius: BorderRadius.circular(3),
                      ),
                      child: const Center(
                        child: Text(
                          'K',
                          style: TextStyle(
                            fontFamily: 'Outfit',
                            fontSize: 9,
                            fontWeight: FontWeight.w800,
                            color: Colors.white,
                            height: 1,
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(width: 6),
                    Text(
                      'Generated by Kinrel',
                      style: TextStyle(
                        fontFamily: KinrelTypography.monoFont,
                        fontSize: 10,
                        fontWeight: FontWeight.w500,
                        color: _cTextDim,
                        letterSpacing: 1,
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

// ═══════════════════════════════════════════════════════════════════════
// Tab 3: Share Graph — Family graph export with watermark
// ═══════════════════════════════════════════════════════════════════════

class _ShareGraphTab extends ConsumerWidget {
  const _ShareGraphTab({required this.familyId, required this.familyName});

  final String familyId;
  final String familyName;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final shareState = ref.watch(
      shareProvider((familyId: familyId, familyName: familyName)),
    );
    final notifier = ref.read(
      shareProvider((familyId: familyId, familyName: familyName)).notifier,
    );

    return SingleChildScrollView(
      physics: const BouncingScrollPhysics(),
      padding: const EdgeInsets.fromLTRB(
        KinrelSpacing.base,
        0,
        KinrelSpacing.base,
        40,
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // ── "Share Family Graph" heading ──────────────────────────
          Text(
            'Share Family Graph',
            style: TextStyle(
              fontFamily: KinrelTypography.displayFont,
              fontSize: 20,
              fontWeight: FontWeight.w700,
              color: _cTextPrimary,
            ),
          ).animate().fadeIn(duration: 350.ms).slideY(begin: 0.06, end: 0),

          const SizedBox(height: 6),

          Text(
            'Export your family graph as a high-resolution image',
            style: TextStyle(
              fontFamily: KinrelTypography.bodyFont,
              fontSize: 13,
              color: _cTextSecondary,
              height: 1.5,
            ),
          ),

          const SizedBox(height: 20),

          // ── Graph Preview Card ────────────────────────────────────
          _GraphPreviewCard(familyName: familyName)
              .animate()
              .fadeIn(duration: 400.ms, delay: 100.ms)
              .slideY(begin: 0.08, end: 0),

          const SizedBox(height: 20),

          // ── Export Options ────────────────────────────────────────
          _ExportOptionsSection(
                isExporting: shareState.isExporting,
                onExport: () async {
                  await notifier.exportGraph();
                  if (context.mounted) {
                    ScaffoldMessenger.of(context).showSnackBar(
                      SnackBar(
                        content: Text('Graph exported successfully!'),
                        backgroundColor: _cCard,
                        behavior: SnackBarBehavior.floating,
                      ),
                    );
                  }
                },
              )
              .animate()
              .fadeIn(duration: 400.ms, delay: 200.ms)
              .slideY(begin: 0.08, end: 0),

          const SizedBox(height: 20),

          // ── Watermark Notice ──────────────────────────────────────
          Container(
            width: double.infinity,
            padding: const EdgeInsets.all(14),
            decoration: BoxDecoration(
              color: _cCard,
              borderRadius: BorderRadius.circular(KinrelRadius.lg),
              border: Border.all(color: _cBorder.withValues(alpha: 0.5)),
            ),
            child: Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(
                    color: _cOrange.withValues(alpha: 0.1),
                    borderRadius: BorderRadius.circular(KinrelRadius.sm),
                  ),
                  child: Icon(
                    Icons.branding_watermark,
                    color: _cOrange,
                    size: 18,
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Watermark included',
                        style: TextStyle(
                          fontFamily: KinrelTypography.bodyFont,
                          fontSize: 13,
                          fontWeight: FontWeight.w600,
                          color: _cTextPrimary,
                        ),
                      ),
                      const SizedBox(height: 2),
                      Text(
                        'All exported images include "Created with Kinrel by Daxelo" watermark',
                        style: TextStyle(
                          fontFamily: KinrelTypography.bodyFont,
                          fontSize: 11,
                          color: _cTextDim,
                          height: 1.4,
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),

          const SizedBox(height: 20),

          // ── Share Graph Button ────────────────────────────────────
          GestureDetector(
            onTap: () {
              ShareHelper.shareFamily(
                familyId: familyId,
                familyName: familyName,
              );
            },
            child: Container(
              width: double.infinity,
              padding: const EdgeInsets.symmetric(vertical: 14),
              decoration: BoxDecoration(
                gradient: KinrelGradients.igniteGradient,
                borderRadius: BorderRadius.circular(KinrelRadius.lg),
                boxShadow: [
                  BoxShadow(
                    color: _cOrange.withValues(alpha: 0.3),
                    blurRadius: 12,
                    offset: const Offset(0, 4),
                  ),
                ],
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const Icon(
                    Icons.share_rounded,
                    color: Colors.white,
                    size: 20,
                  ),
                  const SizedBox(width: 8),
                  Text(
                    'Share Graph',
                    style: TextStyle(
                      fontFamily: KinrelTypography.bodyFont,
                      fontSize: 14,
                      fontWeight: FontWeight.w600,
                      color: Colors.white,
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

// ═══════════════════════════════════════════════════════════════════════
// Graph Preview Card — Placeholder with family tree visual
// ═══════════════════════════════════════════════════════════════════════

class _GraphPreviewCard extends StatelessWidget {
  const _GraphPreviewCard({required this.familyName});

  final String familyName;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      height: 280,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(KinrelRadius.xl),
        gradient: LinearGradient(
          colors: [Color(0xFF191B2C), Color(0xFF202338), Color(0xFF1A1420)],
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
        ),
        border: Border.all(color: _cOrange.withValues(alpha: 0.12), width: 1),
      ),
      child: Stack(
        children: [
          // Background glow
          Positioned(
            top: 20,
            left: 20,
            child: Container(
              width: 80,
              height: 80,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                gradient: RadialGradient(
                  colors: [
                    _cOrange.withValues(alpha: 0.08),
                    Colors.transparent,
                  ],
                ),
              ),
            ),
          ),

          // Graph nodes placeholder — generation rows
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 24),
            child: Column(
              children: [
                // Gen 2: Grandparents
                _GraphGenRow(
                  generation: 'Gen 2',
                  nodes: [
                    _Graphnode(initials: 'DK', color: _cGold),
                    _Graphnode(initials: 'KK', color: _cGold),
                  ],
                ),

                const SizedBox(height: 16),

                // Connecting lines (simplified)
                CustomPaint(
                  size: Size(double.infinity, 20),
                  painter: _SimpleTreeLinePainter(),
                ),

                const SizedBox(height: 16),

                // Gen 1: Parents + siblings
                _GraphGenRow(
                  generation: 'Gen 1',
                  nodes: [
                    _Graphnode(initials: 'RS', color: _cAmber),
                    _Graphnode(initials: 'SS', color: _cAmber),
                    _Graphnode(initials: 'RP', color: _cAmber),
                    _Graphnode(initials: 'MP', color: _cAmber),
                  ],
                ),

                const SizedBox(height: 16),

                CustomPaint(
                  size: Size(double.infinity, 20),
                  painter: _SimpleTreeLinePainter(),
                ),

                const SizedBox(height: 16),

                // Gen 0: You + cousins
                _GraphGenRow(
                  generation: 'You',
                  nodes: [
                    _Graphnode(initials: 'AS', color: _cOrange, isYou: true),
                    _Graphnode(initials: 'PS', color: _cOrange),
                    _Graphnode(initials: 'AP', color: _cOrange),
                  ],
                ),
              ],
            ),
          ),

          // ── Watermark overlay ──────────────────────────────────────
          Positioned(
            bottom: 10,
            right: 14,
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                Container(
                  width: 12,
                  height: 12,
                  decoration: BoxDecoration(
                    gradient: KinrelGradients.igniteGradient,
                    borderRadius: BorderRadius.circular(2),
                  ),
                  child: const Center(
                    child: Text(
                      'K',
                      style: TextStyle(
                        fontFamily: 'Outfit',
                        fontSize: 7,
                        fontWeight: FontWeight.w800,
                        color: Colors.white,
                        height: 1,
                      ),
                    ),
                  ),
                ),
                const SizedBox(width: 4),
                Text(
                  'Created with Kinrel by Daxelo',
                  style: TextStyle(
                    fontFamily: KinrelTypography.monoFont,
                    fontSize: 8,
                    fontWeight: FontWeight.w400,
                    color: _cTextDim.withValues(alpha: 0.6),
                    letterSpacing: 0.5,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

// ── Graph Generation Row ─────────────────────────────────────────────

class _GraphGenRow extends StatelessWidget {
  const _GraphGenRow({required this.generation, required this.nodes});

  final String generation;
  final List<_Graphnode> nodes;

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        SizedBox(
          width: 36,
          child: Text(
            generation,
            style: TextStyle(
              fontFamily: KinrelTypography.monoFont,
              fontSize: 8,
              fontWeight: FontWeight.w500,
              color: _cTextDim,
              letterSpacing: 0.3,
            ),
          ),
        ),
        const SizedBox(width: 8),
        Expanded(
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: nodes,
          ),
        ),
      ],
    );
  }
}

// ── Graph Node ───────────────────────────────────────────────────────

class _Graphnode extends StatelessWidget {
  const _Graphnode({
    required this.initials,
    required this.color,
    this.isYou = false,
  });

  final String initials;
  final Color color;
  final bool isYou;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: isYou ? 36 : 30,
      height: isYou ? 36 : 30,
      decoration: BoxDecoration(
        shape: BoxShape.circle,
        color: color.withValues(alpha: 0.15),
        border: Border.all(
          color: color.withValues(alpha: isYou ? 0.8 : 0.4),
          width: isYou ? 2 : 1.5,
        ),
        boxShadow: isYou
            ? [
                BoxShadow(
                  color: color.withValues(alpha: 0.3),
                  blurRadius: 8,
                  offset: const Offset(0, 2),
                ),
              ]
            : null,
      ),
      alignment: Alignment.center,
      child: Text(
        initials,
        style: TextStyle(
          fontFamily: KinrelTypography.displayFont,
          fontSize: isYou ? 11 : 9,
          fontWeight: FontWeight.w700,
          color: color,
          height: 1,
        ),
      ),
    );
  }
}

// ── Simple Tree Line Painter ─────────────────────────────────────────

class _SimpleTreeLinePainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    final paint = Paint()
      ..color = _cOrange.withValues(alpha: 0.15)
      ..strokeWidth = 1
      ..style = PaintingStyle.stroke;

    final width = size.width;
    final midY = size.height / 2;

    // Horizontal line
    canvas.drawLine(
      Offset(width * 0.15, midY),
      Offset(width * 0.85, midY),
      paint,
    );

    // Vertical connectors
    final positions = [0.25, 0.45, 0.65, 0.8];
    for (final x in positions) {
      canvas.drawLine(
        Offset(width * x, midY - 6),
        Offset(width * x, midY + 6),
        paint,
      );
    }
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => false;
}

// ═══════════════════════════════════════════════════════════════════════
// Export Options Section
// ═══════════════════════════════════════════════════════════════════════

class _ExportOptionsSection extends StatelessWidget {
  const _ExportOptionsSection({
    required this.isExporting,
    required this.onExport,
  });

  final bool isExporting;
  final VoidCallback onExport;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          'Export Options',
          style: TextStyle(
            fontFamily: KinrelTypography.bodyFont,
            fontSize: 14,
            fontWeight: FontWeight.w600,
            color: _cTextSecondary,
          ),
        ),
        const SizedBox(height: 10),

        // High-res image export
        _ExportOptionTile(
          icon: Icons.image_rounded,
          title: 'High-Resolution Image',
          subtitle: 'PNG · 300 DPI · Suitable for printing',
          color: _cOrange,
          isExporting: isExporting,
          onTap: onExport,
        ),
        const SizedBox(height: 8),

        // PDF export
        _ExportOptionTile(
          icon: Icons.picture_as_pdf_rounded,
          title: 'PDF Document',
          subtitle: 'Vector quality · A4 layout',
          color: _cSMS,
          onTap: () {
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(
                content: Text('PDF export coming soon!'),
                backgroundColor: _cCard,
                behavior: SnackBarBehavior.floating,
              ),
            );
          },
        ),
        const SizedBox(height: 8),

        // SVG export
        _ExportOptionTile(
          icon: Icons.draw_rounded,
          title: 'SVG Vector',
          subtitle: 'Scalable · Editable in design tools',
          color: _cAmber,
          onTap: () {
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(
                content: Text('SVG export coming soon!'),
                backgroundColor: _cCard,
                behavior: SnackBarBehavior.floating,
              ),
            );
          },
        ),
      ],
    );
  }
}

// ═══════════════════════════════════════════════════════════════════════
// Export Option Tile
// ═══════════════════════════════════════════════════════════════════════

class _ExportOptionTile extends StatelessWidget {
  const _ExportOptionTile({
    required this.icon,
    required this.title,
    required this.subtitle,
    required this.color,
    required this.onTap,
    this.isExporting = false,
  });

  final IconData icon;
  final String title;
  final String subtitle;
  final Color color;
  final VoidCallback onTap;
  final bool isExporting;

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: isExporting ? null : onTap,
      child: Container(
        padding: const EdgeInsets.all(14),
        decoration: BoxDecoration(
          color: _cCard,
          borderRadius: BorderRadius.circular(KinrelRadius.lg),
          border: Border.all(color: color.withValues(alpha: 0.12), width: 1),
        ),
        child: Row(
          children: [
            Container(
              padding: const EdgeInsets.all(10),
              decoration: BoxDecoration(
                color: color.withValues(alpha: 0.1),
                borderRadius: BorderRadius.circular(KinrelRadius.md),
              ),
              child: isExporting
                  ? SizedBox(
                      width: 20,
                      height: 20,
                      child: CircularProgressIndicator(
                        strokeWidth: 2,
                        valueColor: AlwaysStoppedAnimation<Color>(color),
                      ),
                    )
                  : Icon(icon, size: 20, color: color),
            ),
            const SizedBox(width: 12),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    title,
                    style: TextStyle(
                      fontFamily: KinrelTypography.bodyFont,
                      fontSize: 14,
                      fontWeight: FontWeight.w600,
                      color: _cTextPrimary,
                    ),
                  ),
                  const SizedBox(height: 2),
                  Text(
                    subtitle,
                    style: TextStyle(
                      fontFamily: KinrelTypography.bodyFont,
                      fontSize: 11,
                      color: _cTextDim,
                    ),
                  ),
                ],
              ),
            ),
            Icon(Icons.chevron_right_rounded, size: 20, color: _cTextDim),
          ],
        ),
      ),
    );
  }
}
