// lib/features/events/providers/events_provider.dart
//
// DAXELO KINREL — Events & Celebrations Provider
//
// Event types: birthday, anniversary, reunion, festival, custom
// Auto-generates birthdays from member DOBs and anniversaries
// from marriage dates. Provides reminder scheduling and RSVP tracking.
//
// Orange K-Graph DNA: Birthday = orange, Anniversary = amber,
// Festival = gold, Reunion = orange-amber, Custom = silver.

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../core/constants/brand_colors.dart';

// ═══════════════════════════════════════════════════════════════════════
// Event Type Enum
// ═══════════════════════════════════════════════════════════════════════

/// Types of events supported by the Events & Celebrations feature.
enum EventType {
  birthday,
  anniversary,
  reunion,
  festival,
  custom,
}

// ═══════════════════════════════════════════════════════════════════════
// RSVP Status Enum
// ═══════════════════════════════════════════════════════════════════════

/// RSVP response status for reunion-type events.
enum RSVPStatus {
  none,
  going,
  maybe,
  notGoing,
}

// ═══════════════════════════════════════════════════════════════════════
// Reminder Timing
// ═══════════════════════════════════════════════════════════════════════

/// When a reminder should fire relative to the event.
enum ReminderTiming {
  oneWeekBefore,
  oneDayBefore,
  dayOf,
  custom,
}

// ═══════════════════════════════════════════════════════════════════════
// Event Member (related person)
// ═══════════════════════════════════════════════════════════════════════

/// A family member associated with an event (avatar display).
class EventMember {
  const EventMember({
    required this.id,
    required this.name,
    this.avatarUrl,
    this.initials,
  });

  final String id;
  final String name;
  final String? avatarUrl;
  final String? initials;

  /// Returns initials derived from the name if not explicitly set.
  String get displayInitials =>
      initials ??
      (name.isNotEmpty
          ? name
              .split(' ')
              .where((s) => s.isNotEmpty)
              .take(2)
              .map((s) => s[0].toUpperCase())
              .join()
          : '?');
}

// ═══════════════════════════════════════════════════════════════════════
// Event Model
// ═══════════════════════════════════════════════════════════════════════

/// Represents a single event in the Events & Celebrations feature.
class EventModel {
  const EventModel({
    required this.id,
    required this.name,
    required this.type,
    required this.date,
    this.endTime,
    this.description,
    this.location,
    this.members = const [],
    this.reminderTimings = const [],
    this.rsvpStatus = RSVPStatus.none,
    this.isAutoGenerated = false,
    this.imageUrl,
    this.photoUrls = const [],
    this.comments = const [],
    this.isAllDay = true,
  });

  /// Unique identifier.
  final String id;

  /// Event name / title.
  final String name;

  /// Event type.
  final EventType type;

  /// Event date & time.
  final DateTime date;

  /// Optional end date/time.
  final DateTime? endTime;

  /// Optional description.
  final String? description;

  /// Optional location string.
  final String? location;

  /// Related family members.
  final List<EventMember> members;

  /// Configured reminder timings.
  final List<ReminderTiming> reminderTimings;

  /// RSVP status (only meaningful for reunion type).
  final RSVPStatus rsvpStatus;

  /// Whether this event was auto-generated from DOB/marriage dates.
  final bool isAutoGenerated;

  /// Optional hero image URL.
  final String? imageUrl;

  /// Photo gallery URLs (placeholder).
  final List<String> photoUrls;

  /// Comments on this event.
  final List<EventComment> comments;

  /// Whether this is an all-day event.
  final bool isAllDay;

  // ── Computed Properties ──────────────────────────────────────────

  /// Whether the event is in the future.
  bool get isUpcoming => date.isAfter(DateTime.now());

  /// Whether the event falls within the current month.
  bool get isThisMonth {
    final now = DateTime.now();
    return date.year == now.year && date.month == now.month;
  }

  /// Days remaining until the event.
  int get daysUntil {
    final now = DateTime.now();
    final diff = date.difference(now).inDays;
    if (diff < 0 && !isUpcoming) {
      // For recurring events (birthdays/anniversaries), compute next occurrence
      if (type == EventType.birthday || type == EventType.anniversary) {
        var nextDate = DateTime(now.year, date.month, date.day);
        if (nextDate.isBefore(now)) {
          nextDate = DateTime(now.year + 1, date.month, date.day);
        }
        return nextDate.difference(now).inDays;
      }
    }
    return diff;
  }

  /// Hours remaining until the event.
  int get hoursUntil => date.difference(DateTime.now()).inHours;

  /// Minutes remaining until the event.
  int get minutesUntil => date.difference(DateTime.now()).inMinutes;

  /// Accent color for the event type.
  Color get accentColor {
    switch (type) {
      case EventType.birthday:
        return KinrelColors.orange;    // #E8612A
      case EventType.anniversary:
        return KinrelColors.amber;     // #F59240
      case EventType.festival:
        return KinrelColors.gold;      // #D4AF37
      case EventType.reunion:
        return KinrelColors.orange;    // #E8612A
      case EventType.custom:
        return KinrelColors.textSilver; // #C9B4A8
    }
  }

  /// Icon for the event type.
  IconData get icon {
    switch (type) {
      case EventType.birthday:
        return Icons.cake_rounded;
      case EventType.anniversary:
        return Icons.favorite_rounded;
      case EventType.reunion:
        return Icons.groups_rounded;
      case EventType.festival:
        return Icons.celebration_rounded;
      case EventType.custom:
        return Icons.event_rounded;
    }
  }

  /// Emoji for the event type (for quick messages).
  String get emoji {
    switch (type) {
      case EventType.birthday:
        return '🎂';
      case EventType.anniversary:
        return '💍';
      case EventType.reunion:
        return '🤝';
      case EventType.festival:
        return '🎉';
      case EventType.custom:
        return '📌';
    }
  }

  /// Format the date for display.
  String get formattedDate {
    const months = [
      '', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
    ];
    return '${date.day} ${months[date.month]}, ${date.year}';
  }

  /// Format time for display.
  String get formattedTime {
    if (isAllDay) return 'All Day';
    final hour = date.hour;
    final minute = date.minute.toString().padLeft(2, '0');
    final period = hour >= 12 ? 'PM' : 'AM';
    final displayHour = hour > 12 ? hour - 12 : (hour == 0 ? 12 : hour);
    return '$displayHour:$minute $period';
  }

  /// Copy with method for immutable updates.
  EventModel copyWith({
    String? id,
    String? name,
    EventType? type,
    DateTime? date,
    DateTime? endTime,
    String? description,
    String? location,
    List<EventMember>? members,
    List<ReminderTiming>? reminderTimings,
    RSVPStatus? rsvpStatus,
    bool? isAutoGenerated,
    String? imageUrl,
    List<String>? photoUrls,
    List<EventComment>? comments,
    bool? isAllDay,
  }) {
    return EventModel(
      id: id ?? this.id,
      name: name ?? this.name,
      type: type ?? this.type,
      date: date ?? this.date,
      endTime: endTime ?? this.endTime,
      description: description ?? this.description,
      location: location ?? this.location,
      members: members ?? this.members,
      reminderTimings: reminderTimings ?? this.reminderTimings,
      rsvpStatus: rsvpStatus ?? this.rsvpStatus,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      imageUrl: imageUrl ?? this.imageUrl,
      photoUrls: photoUrls ?? this.photoUrls,
      comments: comments ?? this.comments,
      isAllDay: isAllDay ?? this.isAllDay,
    );
  }
}

// ═══════════════════════════════════════════════════════════════════════
// Event Comment
// ═══════════════════════════════════════════════════════════════════════

/// A comment on an event.
class EventComment {
  const EventComment({
    required this.id,
    required this.author,
    required this.text,
    required this.timestamp,
  });

  final String id;
  final EventMember author;
  final String text;
  final DateTime timestamp;
}

// ═══════════════════════════════════════════════════════════════════════
// Events Filter Enum
// ═══════════════════════════════════════════════════════════════════════

/// Tab filter options for the events screen.
enum EventsFilter {
  upcoming,
  thisMonth,
  all,
}

// ═══════════════════════════════════════════════════════════════════════
// Events State
// ═══════════════════════════════════════════════════════════════════════

/// State for the events feature.
class EventsState {
  const EventsState({
    this.events = const [],
    this.filter = EventsFilter.upcoming,
    this.isLoading = false,
    this.error,
  });

  final List<EventModel> events;
  final EventsFilter filter;
  final bool isLoading;
  final String? error;

  /// Filtered events based on the current filter.
  List<EventModel> get filteredEvents {
    switch (filter) {
      case EventsFilter.upcoming:
        return events.where((e) => e.isUpcoming || e.daysUntil <= 365).toList()
          ..sort((a, b) => a.daysUntil.compareTo(b.daysUntil));
      case EventsFilter.thisMonth:
        return events.where((e) => e.isThisMonth).toList()
          ..sort((a, b) => a.date.compareTo(b.date));
      case EventsFilter.all:
        return events.toList()
          ..sort((a, b) => a.date.compareTo(b.date));
    }
  }

  /// Auto-generated birthday events.
  List<EventModel> get birthdays =>
      events.where((e) => e.type == EventType.birthday).toList();

  /// Auto-generated anniversary events.
  List<EventModel> get anniversaries =>
      events.where((e) => e.type == EventType.anniversary).toList();

  /// Festival events.
  List<EventModel> get festivals =>
      events.where((e) => e.type == EventType.festival).toList();

  /// Reunion events.
  List<EventModel> get reunions =>
      events.where((e) => e.type == EventType.reunion).toList();

  EventsState copyWith({
    List<EventModel>? events,
    EventsFilter? filter,
    bool? isLoading,
    String? error,
  }) {
    return EventsState(
      events: events ?? this.events,
      filter: filter ?? this.filter,
      isLoading: isLoading ?? this.isLoading,
      error: error,
    );
  }
}

// ═══════════════════════════════════════════════════════════════════════
// Events Notifier
// ═══════════════════════════════════════════════════════════════════════

/// State notifier managing the events list and operations.
class EventsNotifier extends StateNotifier<EventsState> {
  EventsNotifier() : super(EventsState(events: _demoEvents));

  /// Set the filter tab.
  void setFilter(EventsFilter filter) {
    state = state.copyWith(filter: filter);
  }

  /// Update RSVP status for a reunion event.
  void updateRSVP(String eventId, RSVPStatus status) {
    final updatedEvents = state.events.map((e) {
      if (e.id == eventId) {
        return e.copyWith(rsvpStatus: status);
      }
      return e;
    }).toList();
    state = state.copyWith(events: updatedEvents);
  }

  /// Add a new custom event.
  void addEvent(EventModel event) {
    state = state.copyWith(events: [...state.events, event]);
  }

  /// Toggle a reminder timing for an event.
  void toggleReminder(String eventId, ReminderTiming timing) {
    final updatedEvents = state.events.map((e) {
      if (e.id == eventId) {
        final timings = List<ReminderTiming>.from(e.reminderTimings);
        if (timings.contains(timing)) {
          timings.remove(timing);
        } else {
          timings.add(timing);
        }
        return e.copyWith(reminderTimings: timings);
      }
      return e;
    }).toList();
    state = state.copyWith(events: updatedEvents);
  }

  /// Add a comment to an event.
  void addComment(String eventId, EventComment comment) {
    final updatedEvents = state.events.map((e) {
      if (e.id == eventId) {
        return e.copyWith(comments: [...e.comments, comment]);
      }
      return e;
    }).toList();
    state = state.copyWith(events: updatedEvents);
  }

  /// Get "Send wishes" quick message options for birthdays/anniversaries.
  List<String> getWishOptions(EventModel event) {
    switch (event.type) {
      case EventType.birthday:
        return [
          'Happy Birthday, ${event.members.firstOrNull?.name ?? 'dear'}! ${event.emoji} Wishing you an amazing year ahead!',
          'Wishing you a wonderful birthday filled with joy and laughter! ${event.emoji}',
          'Happy Birthday! May all your dreams come true this year! ${event.emoji}',
        ];
      case EventType.anniversary:
        return [
          'Happy Anniversary! ${event.emoji} Wishing you many more years of love and happiness!',
          'Congratulations on another year of togetherness! ${event.emoji}',
          'May your bond grow stronger with each passing year! Happy Anniversary! ${event.emoji}',
        ];
      default:
        return [
          'Wishing you a wonderful ${event.name}! ${event.emoji}',
        ];
    }
  }
}

// ═══════════════════════════════════════════════════════════════════════
// Provider
// ═══════════════════════════════════════════════════════════════════════

/// Main events provider.
final eventsProvider =
    StateNotifierProvider<EventsNotifier, EventsState>((ref) {
  return EventsNotifier();
});

// ═══════════════════════════════════════════════════════════════════════
// Demo Data — Realistic Indian Family Events
// ═══════════════════════════════════════════════════════════════════════

final _now = DateTime.now();

final _demoEvents = <EventModel>[
  // ── Birthdays (auto-generated from DOBs) ────────────────────────
  EventModel(
    id: 'bday-arjun',
    name: 'Arjun Sharma — Birthday',
    type: EventType.birthday,
    date: DateTime(_now.year, _now.month, _now.day + 5),
    isAllDay: true,
    isAutoGenerated: true,
    description: 'Arjun turns 32 today! 🎂',
    reminderTimings: [
      ReminderTiming.oneWeekBefore,
      ReminderTiming.oneDayBefore,
      ReminderTiming.dayOf,
    ],
    members: [
      EventMember(id: 'm1', name: 'Arjun Sharma', initials: 'AS'),
      EventMember(id: 'm2', name: 'Priya Sharma', initials: 'PS'),
      EventMember(id: 'm3', name: 'Vikram Sharma', initials: 'VS'),
    ],
  ),

  EventModel(
    id: 'bday-meera',
    name: 'Meera Patel — Birthday',
    type: EventType.birthday,
    date: DateTime(_now.year, _now.month, _now.day + 18),
    isAllDay: true,
    isAutoGenerated: true,
    description: 'Meera\'s special day! 🎂',
    reminderTimings: [
      ReminderTiming.oneWeekBefore,
      ReminderTiming.dayOf,
    ],
    members: [
      EventMember(id: 'm4', name: 'Meera Patel', initials: 'MP'),
      EventMember(id: 'm5', name: 'Rajesh Patel', initials: 'RP'),
    ],
  ),

  EventModel(
    id: 'bday-dadi',
    name: 'Dadi (Kamla Sharma) — Birthday',
    type: EventType.birthday,
    date: DateTime(_now.year, _now.month + 1, 10),
    isAllDay: true,
    isAutoGenerated: true,
    description: 'Dadi\'s 75th birthday celebration! 🎂🎉',
    reminderTimings: [
      ReminderTiming.oneWeekBefore,
      ReminderTiming.oneDayBefore,
      ReminderTiming.dayOf,
    ],
    members: [
      EventMember(id: 'm6', name: 'Kamla Sharma', initials: 'KS'),
      EventMember(id: 'm1', name: 'Arjun Sharma', initials: 'AS'),
      EventMember(id: 'm7', name: 'Ravi Sharma', initials: 'RS'),
      EventMember(id: 'm8', name: 'Sunita Sharma', initials: 'SS'),
    ],
  ),

  EventModel(
    id: 'bday-nani',
    name: 'Nani (Saroj Devi) — Birthday',
    type: EventType.birthday,
    date: DateTime(_now.year, _now.month + 2, 22),
    isAllDay: true,
    isAutoGenerated: true,
    description: 'Nani\'s birthday — the whole family gathers! 🎂',
    reminderTimings: [
      ReminderTiming.oneWeekBefore,
      ReminderTiming.dayOf,
    ],
    members: [
      EventMember(id: 'm9', name: 'Saroj Devi', initials: 'SD'),
      EventMember(id: 'm4', name: 'Meera Patel', initials: 'MP'),
    ],
  ),

  // ── Anniversaries (auto-generated from marriage dates) ───────────
  EventModel(
    id: 'anni-sharma',
    name: 'Sharma Family — Wedding Anniversary',
    type: EventType.anniversary,
    date: DateTime(_now.year, _now.month, _now.day + 12),
    isAllDay: true,
    isAutoGenerated: true,
    description: 'Vikram & Sunita celebrate 35 years of togetherness! 💍',
    reminderTimings: [
      ReminderTiming.oneWeekBefore,
      ReminderTiming.oneDayBefore,
      ReminderTiming.dayOf,
    ],
    members: [
      EventMember(id: 'm7', name: 'Ravi Sharma', initials: 'RS'),
      EventMember(id: 'm8', name: 'Sunita Sharma', initials: 'SS'),
      EventMember(id: 'm1', name: 'Arjun Sharma', initials: 'AS'),
    ],
  ),

  EventModel(
    id: 'anni-patel',
    name: 'Patel Family — Wedding Anniversary',
    type: EventType.anniversary,
    date: DateTime(_now.year, _now.month + 1, 15),
    isAllDay: true,
    isAutoGenerated: true,
    description: 'Rajesh & Meera celebrate 8 years! 💍',
    reminderTimings: [
      ReminderTiming.oneWeekBefore,
      ReminderTiming.dayOf,
    ],
    members: [
      EventMember(id: 'm5', name: 'Rajesh Patel', initials: 'RP'),
      EventMember(id: 'm4', name: 'Meera Patel', initials: 'MP'),
    ],
  ),

  // ── Festivals ───────────────────────────────────────────────────
  EventModel(
    id: 'diwali',
    name: 'Diwali — Festival of Lights',
    type: EventType.festival,
    date: DateTime(_now.year, _now.month, _now.day + 25),
    isAllDay: true,
    description: 'May the festival of lights bring joy, prosperity, and happiness to your family! 🪔✨',
    location: 'Sharma Family Home, Jaipur',
    reminderTimings: [
      ReminderTiming.oneWeekBefore,
      ReminderTiming.oneDayBefore,
      ReminderTiming.dayOf,
    ],
    members: [
      EventMember(id: 'm6', name: 'Kamla Sharma', initials: 'KS'),
      EventMember(id: 'm7', name: 'Ravi Sharma', initials: 'RS'),
      EventMember(id: 'm8', name: 'Sunita Sharma', initials: 'SS'),
      EventMember(id: 'm1', name: 'Arjun Sharma', initials: 'AS'),
    ],
  ),

  EventModel(
    id: 'holi',
    name: 'Holi — Festival of Colors',
    type: EventType.festival,
    date: DateTime(_now.year, 3, 14),
    isAllDay: true,
    description: 'Celebrate the victory of good over evil with colors and joy! 🎨🌈',
    location: 'Community Ground, Jaipur',
    reminderTimings: [
      ReminderTiming.oneWeekBefore,
      ReminderTiming.dayOf,
    ],
    members: [
      EventMember(id: 'm1', name: 'Arjun Sharma', initials: 'AS'),
      EventMember(id: 'm2', name: 'Priya Sharma', initials: 'PS'),
    ],
  ),

  EventModel(
    id: 'eid',
    name: 'Eid ul-Fitr',
    type: EventType.festival,
    date: DateTime(_now.year, _now.month + 2, 2),
    isAllDay: true,
    description: 'Eid Mubarak! May blessings and joy fill your home! 🌙✨',
    reminderTimings: [
      ReminderTiming.oneDayBefore,
      ReminderTiming.dayOf,
    ],
    members: [
      EventMember(id: 'm10', name: 'Imran Khan', initials: 'IK'),
    ],
  ),

  EventModel(
    id: 'christmas',
    name: 'Christmas',
    type: EventType.festival,
    date: DateTime(_now.year, 12, 25),
    isAllDay: true,
    description: 'Merry Christmas! Wishing warmth and joy to the family! 🎄🎁',
    reminderTimings: [
      ReminderTiming.oneWeekBefore,
      ReminderTiming.dayOf,
    ],
    members: [
      EventMember(id: 'm11', name: 'Anita D\'Souza', initials: 'AD'),
    ],
  ),

  // ── Family Reunions ─────────────────────────────────────────────
  EventModel(
    id: 'reunion-2026',
    name: 'Sharma Family Reunion 2026',
    type: EventType.reunion,
    date: DateTime(_now.year, _now.month + 1, 20, 10, 0),
    endTime: DateTime(_now.year, _now.month + 1, 22, 18, 0),
    isAllDay: false,
    description: 'Annual Sharma family gathering — 3 days of food, fun, and family bonding! Don\'t miss the cricket match and rangoli competition.',
    location: 'Farmhouse, Kukas, Jaipur',
    rsvpStatus: RSVPStatus.none,
    reminderTimings: [
      ReminderTiming.oneWeekBefore,
      ReminderTiming.oneDayBefore,
      ReminderTiming.dayOf,
    ],
    members: [
      EventMember(id: 'm6', name: 'Kamla Sharma', initials: 'KS'),
      EventMember(id: 'm7', name: 'Ravi Sharma', initials: 'RS'),
      EventMember(id: 'm8', name: 'Sunita Sharma', initials: 'SS'),
      EventMember(id: 'm1', name: 'Arjun Sharma', initials: 'AS'),
    ],
  ),

  EventModel(
    id: 'reunion-patel',
    name: 'Patel Family Get-Together',
    type: EventType.reunion,
    date: DateTime(_now.year, _now.month + 3, 8, 11, 0),
    endTime: DateTime(_now.year, _now.month + 3, 8, 20, 0),
    isAllDay: false,
    description: 'One-day Patel family meet with lunch and garba night! 💃🕺',
    location: 'Patel Wadi, Ahmedabad',
    rsvpStatus: RSVPStatus.going,
    reminderTimings: [
      ReminderTiming.oneWeekBefore,
      ReminderTiming.dayOf,
    ],
    members: [
      EventMember(id: 'm5', name: 'Rajesh Patel', initials: 'RP'),
      EventMember(id: 'm4', name: 'Meera Patel', initials: 'MP'),
      EventMember(id: 'm12', name: 'Dinesh Patel', initials: 'DP'),
    ],
  ),

  // ── Custom Events ───────────────────────────────────────────────
  EventModel(
    id: 'custom-naming',
    name: 'Anaya\'s Naming Ceremony',
    type: EventType.custom,
    date: DateTime(_now.year, _now.month, _now.day + 30, 9, 0),
    isAllDay: false,
    description: 'Namkaran ceremony for baby Anaya. All family members invited! 🎀👶',
    location: 'Sharma Residence, Malviya Nagar, Jaipur',
    reminderTimings: [
      ReminderTiming.oneWeekBefore,
      ReminderTiming.oneDayBefore,
      ReminderTiming.dayOf,
    ],
    members: [
      EventMember(id: 'm1', name: 'Arjun Sharma', initials: 'AS'),
      EventMember(id: 'm2', name: 'Priya Sharma', initials: 'PS'),
      EventMember(id: 'm6', name: 'Kamla Sharma', initials: 'KS'),
    ],
  ),

  EventModel(
    id: 'custom-griha-pravesh',
    name: 'Griha Pravesh — New Home',
    type: EventType.custom,
    date: DateTime(_now.year, _now.month + 2, 5, 8, 0),
    isAllDay: false,
    description: 'Housewarming ceremony at the new Patel residence. Puja followed by lunch. 🏠🙏',
    location: 'New Patel House, Vastrapur, Ahmedabad',
    reminderTimings: [
      ReminderTiming.oneWeekBefore,
      ReminderTiming.dayOf,
    ],
    members: [
      EventMember(id: 'm5', name: 'Rajesh Patel', initials: 'RP'),
      EventMember(id: 'm4', name: 'Meera Patel', initials: 'MP'),
      EventMember(id: 'm9', name: 'Saroj Devi', initials: 'SD'),
    ],
  ),
];
