// =============================================================================
// Track C v2.0 — AURA Intelligence
// intelligence.module.ts
// =============================================================================
// The module wires the LLM provider based on environment, with this priority:
//
//   1. ZAI_API_KEY set           → ZaiProvider (FREE — recommended)
//   2. ZAI_API_KEY absent but
//      ZAI_PROVIDER_ENABLED=true → ZaiProvider (free public endpoint)
//   3. OPENAI_API_KEY set         → OpenAIProvider (paid)
//   4. None of the above          → MockLLMProvider (canned responses)
//
// Z.ai (GLM-4.6) is the RECOMMENDED provider:
//   - FREE (no per-token charges, no credit card needed)
//   - Quality comparable to GPT-4o-mini
//   - Supports JSON mode for structured outputs
//   - OpenAI-compatible REST API
//
// To enable Z.ai on Render, set ONE of:
//   ZAI_API_KEY=your-zai-key       (if you have a paid Z.ai key for higher limits)
//   ZAI_PROVIDER_ENABLED=true      (to use the free public endpoint — no key needed)
//
// To use OpenAI instead, set:
//   OPENAI_API_KEY=sk-...          (paid — will incur costs)
// =============================================================================

import { Module, Logger } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { IntelligenceController } from './intelligence.controller';
import { IntelligenceService } from './intelligence.service';
import { IntelligenceCache } from './intelligence.cache';
import { CircuitBreaker } from './intelligence.circuit-breaker';
import { CostGuard } from './intelligence.cost-guard';
import { RedactionService } from './redaction';
import { DecisionAnalysisKind } from './kinds/decision-analysis.kind';
import { ProsConsKind } from './kinds/pros-cons.kind';
import { SummaryKind } from './kinds/summary.kind';
import { DuplicateDetectionKind } from './kinds/duplicate-detection.kind';
import { ActionItemsKind } from './kinds/action-items.kind';
import { LLM_PROVIDER, LLMProvider } from './llm-provider';
import { OpenAIProvider } from './llm-providers/openai.provider';
import { ZaiProvider, loadZaiConfigFromFile } from './llm-providers/zai.provider';
import { MockLLMProvider } from './llm-providers/mock.provider';
import { GovernanceTimelineModule } from '../governance-timeline/timeline.module';
import { TrackcCommonModule } from '../common/trackc-common.module';
import { PrismaModule } from '../../prisma/prisma.module';

@Module({
  imports: [PrismaModule, ConfigModule, TrackcCommonModule, GovernanceTimelineModule],
  controllers: [IntelligenceController],
  providers: [
    IntelligenceCache,
    CircuitBreaker,
    CostGuard,
    RedactionService,
    DecisionAnalysisKind,
    ProsConsKind,
    SummaryKind,
    DuplicateDetectionKind,
    ActionItemsKind,
    IntelligenceService,
    {
      // Factory: choose provider based on env — Z.ai is preferred (free)
      provide: LLM_PROVIDER,
      inject: [ConfigService],
      useFactory: (config: ConfigService): LLMProvider => {
        const logger = new Logger('LLMProviderFactory');

        // ── Priority 1+2: Z.ai (FREE — recommended) ──────────────────────
        // ZAI_TOKEN can come from env var OR from the z-ai config file
        // (auto-generated by the z-ai CLI on first use).
        const zaiApiKey = config.get<string>('ZAI_API_KEY');
        const zaiEnabled = config.get<string>('ZAI_PROVIDER_ENABLED')?.toLowerCase();
        const zaiBaseUrl = config.get<string>('ZAI_BASE_URL');
        const zaiModel = config.get<string>('ZAI_DEFAULT_MODEL') ?? 'glm-4.7-flash';
        const zaiToken = config.get<string>('ZAI_TOKEN');
        const zaiUserId = config.get<string>('ZAI_USER_ID');
        const zaiChatId = config.get<string>('ZAI_CHAT_ID');

        // Try env var first, then config file
        const fileConfig = loadZaiConfigFromFile();
        const effectiveToken = zaiToken || fileConfig?.token;
        const effectiveApiKey = zaiApiKey || fileConfig?.apiKey || 'Z.ai';
        const effectiveBaseUrl = zaiBaseUrl || fileConfig?.baseUrl;
        const effectiveUserId = zaiUserId || fileConfig?.userId;
        const effectiveChatId = zaiChatId || fileConfig?.chatId;

        if (effectiveToken) {
          logger.log(`Using Z.ai LLM provider (model=${zaiModel}) — FREE`);
          return new ZaiProvider({
            apiKey: effectiveApiKey,
            baseUrl: effectiveBaseUrl,
            defaultModelId: zaiModel,
            token: effectiveToken,
            userId: effectiveUserId,
            chatId: effectiveChatId,
          });
        }
        if (zaiEnabled === 'true' || zaiEnabled === '1' || zaiEnabled === 'yes') {
          logger.warn(
            'ZAI_PROVIDER_ENABLED=true but no ZAI_TOKEN found. Set ZAI_TOKEN env var ' +
            'or ensure /etc/.z-ai-config exists. Falling back to MockLLMProvider.',
          );
        }

        // ── Priority 3: OpenAI (paid) ────────────────────────────────────
        const openaiApiKey = config.get<string>('OPENAI_API_KEY');
        const openaiBaseUrl = config.get<string>('OPENAI_BASE_URL');
        const openaiModel = config.get<string>('OPENAI_DEFAULT_MODEL') ?? 'glm-4.7-flash';
        if (openaiApiKey && openaiApiKey.length > 10) {
          logger.log(`Using OpenAI LLM provider (model=${openaiModel}) — PAID`);
          return new OpenAIProvider({ apiKey: openaiApiKey, baseUrl: openaiBaseUrl, defaultModelId: openaiModel });
        }

        // ── Priority 4: Mock (canned responses) ──────────────────────────
        logger.warn(
          'No LLM provider configured. Set ZAI_PROVIDER_ENABLED=true (FREE) or OPENAI_API_KEY (paid). ' +
          'Falling back to MockLLMProvider — AI insights will be canned.',
        );
        return new MockLLMProvider();
      },
    },
  ],
  exports: [
    IntelligenceService,
    IntelligenceCache,
    CircuitBreaker,
    CostGuard,
    RedactionService,
    DecisionAnalysisKind,
    ProsConsKind,
    SummaryKind,
    DuplicateDetectionKind,
    ActionItemsKind,
    LLM_PROVIDER,
  ],
})
export class AuraIntelligenceModule {}
