// lib/features/share/providers/share_provider.dart
//
// DAXELO KINREL — Share & Invite Provider
//
// Manages invite links, kinship share cards, and family graph export.
// Supports 6 invite methods: Link, QR Code, WhatsApp, SMS, Email, Copy.
// Kinship share card displays the regional term, English translation,
// relationship path, and "Generated by Kinrel" branding.
// Family graph export with watermark.
//
// Orange K-Graph DNA: Link=orange, QR=amber, WhatsApp=green,
//   SMS=blue, Email=orange, Copy=white.

import 'package:flutter_riverpod/flutter_riverpod.dart';

// ═══════════════════════════════════════════════════════════════════════
// Invite Method Enum
// ═══════════════════════════════════════════════════════════════════════

/// Methods available for sharing an invite.
enum InviteMethod {
  link,
  qrCode,
  whatsapp,
  sms,
  email,
  copyLink,
}

// ═══════════════════════════════════════════════════════════════════════
// Invite Link Model
// ═══════════════════════════════════════════════════════════════════════

/// Represents an active invite link for a family.
class InviteLink {
  const InviteLink({
    required this.id,
    required this.code,
    required this.familyId,
    required this.familyName,
    required this.createdAt,
    required this.expiresAt,
    this.usedCount = 0,
    this.maxUses = 50,
    this.isActive = true,
  });

  /// Unique identifier.
  final String id;

  /// Short alphanumeric invite code (e.g. "abc123").
  final String code;

  /// The family this link belongs to.
  final String familyId;

  /// Display name of the family.
  final String familyName;

  /// When the link was created.
  final DateTime createdAt;

  /// When the link expires.
  final DateTime expiresAt;

  /// Number of times the link has been used.
  final int usedCount;

  /// Maximum allowed uses.
  final int maxUses;

  /// Whether the link is still active.
  final bool isActive;

  // ── Computed Properties ──────────────────────────────────────────

  /// Full deep link URL (e.g., kinrel.app/invite/abc123).
  String get deepLink => 'kinrel.app/invite/$code';

  /// Whether the link has expired.
  bool get isExpired => DateTime.now().isAfter(expiresAt);

  /// Days remaining until expiry.
  int get daysUntilExpiry => expiresAt.difference(DateTime.now()).inDays;

  /// Formatted expiry label.
  String get expiryLabel {
    if (isExpired) return 'Expired';
    if (daysUntilExpiry == 0) return 'Expires today';
    if (daysUntilExpiry == 1) return 'Expires tomorrow';
    return 'Expires in $daysUntilExpiry days';
  }

  /// Usage label.
  String get usageLabel => '$usedCount / $maxUses used';

  /// Formatted creation date.
  String get formattedCreatedDate {
    const months = [
      '', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
    ];
    return '${createdAt.day} ${months[createdAt.month]} ${createdAt.year}';
  }

  /// WhatsApp pre-formatted message.
  String get whatsappMessage =>
      'Hey! Join our family on Kinrel 🧡\n\n'
      'I\'m building our family tree and I\'d love for you to be part of it. '
      'Click the link below to join the *$familyName* family:\n\n'
      '🔗 $deepLink\n\n'
      '— Sent via Kinrel by Daxelo';

  /// SMS pre-formatted message.
  String get smsMessage =>
      'Join our family on Kinrel! Click here: $deepLink — Sent via Kinrel';

  /// Email subject line.
  String get emailSubject => 'Join the $familyName Family on Kinrel';

  /// Email body.
  String get emailBody =>
      'Hi there!\n\n'
      'I\'m building our family tree on Kinrel and would love for you to join.\n\n'
      'Click the link below to join the $familyName family:\n'
      '$deepLink\n\n'
      'With Kinrel, you can:\n'
      '• Discover how you\'re related to family members\n'
      '• Learn kinship terms in your regional language\n'
      '• Build and explore your family graph\n\n'
      'Looking forward to connecting!\n\n'
      '— Sent via Kinrel by Daxelo';

  InviteLink copyWith({
    String? id,
    String? code,
    String? familyId,
    String? familyName,
    DateTime? createdAt,
    DateTime? expiresAt,
    int? usedCount,
    int? maxUses,
    bool? isActive,
  }) {
    return InviteLink(
      id: id ?? this.id,
      code: code ?? this.code,
      familyId: familyId ?? this.familyId,
      familyName: familyName ?? this.familyName,
      createdAt: createdAt ?? this.createdAt,
      expiresAt: expiresAt ?? this.expiresAt,
      usedCount: usedCount ?? this.usedCount,
      maxUses: maxUses ?? this.maxUses,
      isActive: isActive ?? this.isActive,
    );
  }
}

// ═══════════════════════════════════════════════════════════════════════
// Kinship Share Card Model
// ═══════════════════════════════════════════════════════════════════════

/// A shareable kinship card showing the regional term, translation,
/// and relationship path.
class KinshipShareCard {
  const KinshipShareCard({
    required this.id,
    required this.personName,
    required this.kinshipTermRegional,
    required this.kinshipTermEnglish,
    required this.relationshipPath,
    this.languageName = 'Hindi',
    this.languageScript = 'हिंदी',
    this.generationNumber = 2,
  });

  /// Unique identifier.
  final String id;

  /// Name of the person you call by this kinship term.
  final String personName;

  /// The kinship term in regional script (e.g., "चाचा").
  final String kinshipTermRegional;

  /// English translation (e.g., "Father's younger brother").
  final String kinshipTermEnglish;

  /// Human-readable relationship path (e.g., "You → Father → Younger Brother").
  final String relationshipPath;

  /// Name of the language (e.g., "Hindi").
  final String languageName;

  /// Script name in native form (e.g., "हिंदी").
  final String languageScript;

  /// Which generation this relative belongs to.
  final int generationNumber;

  // ── Computed Properties ──────────────────────────────────────────

  /// "What do I call [name]?" question text.
  String get questionText => 'What do I call $personName?';

  /// Share text for WhatsApp Status.
  String get whatsappStatusText =>
      'I call them *$kinshipTermRegional* ($kinshipTermEnglish) 🧡\n\n'
      '$questionText\n'
      'Path: $relationshipPath\n\n'
      '#Kinrel #Family #Kinship';

  /// Share text for general share sheet.
  String get shareText =>
      'On Kinrel, I discovered I call $personName "$kinshipTermRegional" '
      '($kinshipTermEnglish).\n\n'
      'Path: $relationshipPath\n\n'
      '— Generated by Kinrel';

  KinshipShareCard copyWith({
    String? id,
    String? personName,
    String? kinshipTermRegional,
    String? kinshipTermEnglish,
    String? relationshipPath,
    String? languageName,
    String? languageScript,
    int? generationNumber,
  }) {
    return KinshipShareCard(
      id: id ?? this.id,
      personName: personName ?? this.personName,
      kinshipTermRegional: kinshipTermRegional ?? this.kinshipTermRegional,
      kinshipTermEnglish: kinshipTermEnglish ?? this.kinshipTermEnglish,
      relationshipPath: relationshipPath ?? this.relationshipPath,
      languageName: languageName ?? this.languageName,
      languageScript: languageScript ?? this.languageScript,
      generationNumber: generationNumber ?? this.generationNumber,
    );
  }
}

// ═══════════════════════════════════════════════════════════════════════
// Share Tab Enum
// ═══════════════════════════════════════════════════════════════════════

/// Tabs on the Share screen.
enum ShareTab {
  invite,
  shareCard,
  shareGraph,
}

// ═══════════════════════════════════════════════════════════════════════
// Share State
// ═══════════════════════════════════════════════════════════════════════

/// State for the Share & Invite feature.
class ShareState {
  const ShareState({
    this.inviteLinks = const [],
    this.kinshipCards = const [],
    this.currentTab = ShareTab.invite,
    this.familyId = '',
    this.familyName = '',
    this.isExporting = false,
    this.copiedToClipboard = false,
  });

  /// Active invite links for the family.
  final List<InviteLink> inviteLinks;

  /// Available kinship share cards.
  final List<KinshipShareCard> kinshipCards;

  /// Currently selected tab.
  final ShareTab currentTab;

  /// Family ID for context.
  final String familyId;

  /// Family display name.
  final String familyName;

  /// Whether a graph export is in progress.
  final bool isExporting;

  /// Whether link was recently copied to clipboard.
  final bool copiedToClipboard;

  /// Active (non-expired) invite links.
  List<InviteLink> get activeLinks =>
      inviteLinks.where((l) => l.isActive && !l.isExpired).toList();

  /// Expired invite links.
  List<InviteLink> get expiredLinks =>
      inviteLinks.where((l) => l.isExpired || !l.isActive).toList();

  /// Primary invite link (most recent active).
  InviteLink? get primaryLink =>
      activeLinks.isNotEmpty ? activeLinks.first : null;

  ShareState copyWith({
    List<InviteLink>? inviteLinks,
    List<KinshipShareCard>? kinshipCards,
    ShareTab? currentTab,
    String? familyId,
    String? familyName,
    bool? isExporting,
    bool? copiedToClipboard,
  }) {
    return ShareState(
      inviteLinks: inviteLinks ?? this.inviteLinks,
      kinshipCards: kinshipCards ?? this.kinshipCards,
      currentTab: currentTab ?? this.currentTab,
      familyId: familyId ?? this.familyId,
      familyName: familyName ?? this.familyName,
      isExporting: isExporting ?? this.isExporting,
      copiedToClipboard: copiedToClipboard ?? this.copiedToClipboard,
    );
  }
}

// ═══════════════════════════════════════════════════════════════════════
// Share Notifier
// ═══════════════════════════════════════════════════════════════════════

/// State notifier managing share & invite operations.
class ShareNotifier extends StateNotifier<ShareState> {
  ShareNotifier({required String familyId, required String familyName})
      : super(ShareState(
          familyId: familyId,
          familyName: familyName,
          inviteLinks: _demoInviteLinks,
          kinshipCards: _demoKinshipCards,
        ));

  /// Switch between tabs.
  void setTab(ShareTab tab) {
    state = state.copyWith(currentTab: tab);
  }

  /// Generate a new invite link.
  void generateLink() {
    final code = _generateCode();
    final now = DateTime.now();
    final newLink = InviteLink(
      id: 'link-${now.millisecondsSinceEpoch}',
      code: code,
      familyId: state.familyId,
      familyName: state.familyName,
      createdAt: now,
      expiresAt: now.add(const Duration(days: 30)),
      usedCount: 0,
      maxUses: 50,
      isActive: true,
    );
    state = state.copyWith(inviteLinks: [newLink, ...state.inviteLinks]);
  }

  /// Deactivate an invite link.
  void deactivateLink(String linkId) {
    final updated = state.inviteLinks.map((l) {
      if (l.id == linkId) return l.copyWith(isActive: false);
      return l;
    }).toList();
    state = state.copyWith(inviteLinks: updated);
  }

  /// Mark link as copied to clipboard.
  void markCopied() {
    state = state.copyWith(copiedToClipboard: true);
    // Reset after 2 seconds
    Future.delayed(const Duration(seconds: 2), () {
      if (mounted) state = state.copyWith(copiedToClipboard: false);
    });
  }

  /// Start graph export simulation.
  Future<void> exportGraph() async {
    state = state.copyWith(isExporting: true);
    // Simulate export delay
    await Future.delayed(const Duration(seconds: 2));
    if (mounted) state = state.copyWith(isExporting: false);
  }

  /// Generate a random 6-char invite code.
  static String _generateCode() {
    const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';
    final now = DateTime.now().millisecondsSinceEpoch;
    // Simple deterministic "random" from timestamp
    return List.generate(6, (i) {
      final index = (now + i * 7) % chars.length;
      return chars[index];
    }).join();
  }
}

// ═══════════════════════════════════════════════════════════════════════
// Provider
// ═══════════════════════════════════════════════════════════════════════

/// Family-scoped share provider.
/// Usage: ref.watch(shareProvider(familyId: 'xxx', familyName: 'Sharma'))
final shareProvider = StateNotifierProvider.family<ShareNotifier, ShareState,
    ({String familyId, String familyName})>(
  (ref, params) => ShareNotifier(
    familyId: params.familyId,
    familyName: params.familyName,
  ),
);

// ═══════════════════════════════════════════════════════════════════════
// Demo Data — Realistic Indian Family Invite Links & Kinship Cards
// ═══════════════════════════════════════════════════════════════════════

final _now = DateTime.now();

final _demoInviteLinks = <InviteLink>[
  InviteLink(
    id: 'link-001',
    code: 'sharma25',
    familyId: 'fam-sharma',
    familyName: 'Sharma Family',
    createdAt: _now.subtract(const Duration(days: 5)),
    expiresAt: _now.add(const Duration(days: 25)),
    usedCount: 12,
    maxUses: 50,
    isActive: true,
  ),
  InviteLink(
    id: 'link-002',
    code: 'diwali26',
    familyId: 'fam-sharma',
    familyName: 'Sharma Family',
    createdAt: _now.subtract(const Duration(days: 2)),
    expiresAt: _now.add(const Duration(days: 28)),
    usedCount: 3,
    maxUses: 100,
    isActive: true,
  ),
  InviteLink(
    id: 'link-003',
    code: 'reunion8',
    familyId: 'fam-sharma',
    familyName: 'Sharma Family',
    createdAt: _now.subtract(const Duration(days: 40)),
    expiresAt: _now.subtract(const Duration(days: 10)),
    usedCount: 28,
    maxUses: 50,
    isActive: false,
  ),
  InviteLink(
    id: 'link-004',
    code: 'patel24',
    familyId: 'fam-sharma',
    familyName: 'Sharma Family',
    createdAt: _now.subtract(const Duration(days: 1)),
    expiresAt: _now.add(const Duration(days: 29)),
    usedCount: 1,
    maxUses: 30,
    isActive: true,
  ),
];

final _demoKinshipCards = <KinshipShareCard>[
  KinshipShareCard(
    id: 'kc-001',
    personName: 'Rajesh Chacha',
    kinshipTermRegional: 'चाचा',
    kinshipTermEnglish: "Father's younger brother",
    relationshipPath: 'You → Father → Younger Brother',
    languageName: 'Hindi',
    languageScript: 'हिंदी',
    generationNumber: 1,
  ),
  KinshipShareCard(
    id: 'kc-002',
    personName: 'Neeta Bhabhi',
    kinshipTermRegional: 'भाभी',
    kinshipTermEnglish: "Elder brother's wife",
    relationshipPath: 'You → Elder Brother → Wife',
    languageName: 'Hindi',
    languageScript: 'हिंदी',
    generationNumber: 0,
  ),
  KinshipShareCard(
    id: 'kc-003',
    personName: 'Dadi Kamla',
    kinshipTermRegional: 'दादी',
    kinshipTermEnglish: 'Paternal grandmother',
    relationshipPath: 'You → Father → Mother',
    languageName: 'Hindi',
    languageScript: 'हिंदी',
    generationNumber: 2,
  ),
  KinshipShareCard(
    id: 'kc-004',
    personName: 'Meera Mausi',
    kinshipTermRegional: 'मौसी',
    kinshipTermEnglish: "Mother's sister",
    relationshipPath: 'You → Mother → Sister',
    languageName: 'Hindi',
    languageScript: 'हिंदी',
    generationNumber: 1,
  ),
  KinshipShareCard(
    id: 'kc-005',
    personName: 'Ramesh Mama',
    kinshipTermRegional: 'मामा',
    kinshipTermEnglish: "Mother's brother",
    relationshipPath: 'You → Mother → Brother',
    languageName: 'Hindi',
    languageScript: 'हिंदी',
    generationNumber: 1,
  ),
  KinshipShareCard(
    id: 'kc-006',
    personName: 'Priya Nanad',
    kinshipTermRegional: 'ननद',
    kinshipTermEnglish: "Husband's sister",
    relationshipPath: 'You → Husband → Sister',
    languageName: 'Hindi',
    languageScript: 'हिंदी',
    generationNumber: 0,
  ),
];
