// =============================================================================
// Track C v2.0 — AURA Intelligence
// llm-providers/zai.provider.ts
// =============================================================================
// Z.ai (GLM) LLM provider — FREE, high-quality, OpenAI-compatible.
//
// Z.ai offers:
//   - Free tier via the z-ai-web-dev-sdk (no credit card needed)
//   - GLM-4.6 model (comparable to GPT-4o-mini in quality)
//   - OpenAI-compatible /chat/completions endpoint
//   - JSON mode support
//
// This provider uses the Z.ai REST API directly (no SDK dependency needed
// in the NestJS server, since z-ai-web-dev-sdk is ESM-only).
//
// Authentication:
//   The Z.ai API requires a JWT token (X-Token header) that's generated per
//   session. On the production server, the z-ai CLI generates this token
//   automatically. For the NestJS server, we read the token from:
//     1. ZAI_TOKEN env var (preferred — set this on Render)
//     2. /etc/.z-ai-config file (auto-generated by the z-ai CLI)
//     3. ~/.z-ai-config file
//
// Configuration (set via Render env vars):
//   - ZAI_TOKEN: The JWT token from your z-ai config (REQUIRED for production)
//   - ZAI_API_KEY: Optional. Defaults to 'Z.ai' (the public key)
//   - ZAI_BASE_URL: Optional. Defaults to https://internal-api.z.ai/v1
//   - ZAI_DEFAULT_MODEL: Optional. Defaults to 'glm-4.6'
//   - ZAI_USER_ID: Optional. Your Z.ai user ID (from config)
//   - ZAI_CHAT_ID: Optional. A chat session ID
//
// Cost: FREE (no per-token charges). Ideal for the AURA Intelligence module's
// 50K tokens/day budget — you'll never hit the budget.
//
// HOW TO GET YOUR ZAI_TOKEN:
//   The z-ai CLI auto-generates a token on first use. To get it:
//     1. Run `z-ai chat -p "hello"` on any server with z-ai installed
//     2. Read the token from /etc/.z-ai-config or ~/.z-ai-config
//     3. Copy the "token" field value
//     4. Set ZAI_TOKEN=<that-value> on Render
// =============================================================================

import { Injectable, Logger } from '@nestjs/common';
import { readFileSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';
import {
  LLMProvider,
  LLMRequest,
  LLMResponse,
  LLMUsageStats,
} from '../llm-provider';

export interface ZaiProviderConfig {
  apiKey?: string;
  baseUrl?: string;
  defaultModelId?: string;
  token?: string;       // JWT — REQUIRED for API access
  userId?: string;
  chatId?: string;
}

@Injectable()
export class ZaiProvider implements LLMProvider {
  readonly providerName = 'zai';
  private readonly logger = new Logger(ZaiProvider.name);
  private readonly baseUrl: string;
  private readonly apiKey: string;
  private readonly defaultModelId: string;
  private readonly token: string | undefined;
  private readonly userId: string | undefined;
  private readonly chatId: string | undefined;

  private stats: LLMUsageStats = {
    totalRequests: 0,
    totalTokensIn: 0,
    totalTokensOut: 0,
    totalCostUsd: 0, // Always 0 — Z.ai is free
    errorCount: 0,
  };

  constructor(config: ZaiProviderConfig = {}) {
    this.apiKey = config.apiKey || 'Z.ai';
    this.baseUrl = config.baseUrl || 'https://internal-api.z.ai/v1';
    this.defaultModelId = config.defaultModelId || 'glm-4.6';
    this.token = config.token;
    this.userId = config.userId;
    this.chatId = config.chatId;
  }

  async generate(req: LLMRequest): Promise<LLMResponse> {
    const modelId = req.modelId || this.defaultModelId;
    const start = Date.now();

    const body: any = {
      model: modelId,
      messages: req.messages,
      max_tokens: Math.min(req.maxOutputTokens ?? 1500, 4000),
      temperature: req.temperature ?? 0.4,
      thinking: { type: 'disabled' }, // Z.ai requires this
    };
    if (req.responseFormat === 'json_object') {
      body.response_format = { type: 'json_object' };
    }

    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${this.apiKey}`,
      'X-Z-AI-From': 'Z',
    };
    if (this.token) headers['X-Token'] = this.token;
    if (this.userId) headers['X-User-Id'] = this.userId;
    if (this.chatId) headers['X-Chat-Id'] = this.chatId;

    const res = await fetch(`${this.baseUrl}/chat/completions`, {
      method: 'POST',
      headers,
      body: JSON.stringify(body),
    });

    if (!res.ok) {
      const errText = await res.text().catch(() => '');
      this.stats.errorCount++;
      throw new Error(`Z.ai API ${res.status}: ${errText.slice(0, 500)}`);
    }

    const data: any = await res.json();
    const content = data.choices?.[0]?.message?.content ?? '';
    const tokensIn = data.usage?.prompt_tokens ?? this.estimateTokens(req.messages);
    const tokensOut = data.usage?.completion_tokens ?? this.estimateTokens([{ content }] as any);
    const latencyMs = Date.now() - start;

    this.stats.totalRequests++;
    this.stats.totalTokensIn += tokensIn;
    this.stats.totalTokensOut += tokensOut;
    // Z.ai is free — costUsd stays 0

    return { modelId, content, tokensIn, tokensOut, costUsd: 0, latencyMs };
  }

  getUsageStats(): LLMUsageStats {
    return { ...this.stats };
  }

  private estimateTokens(messages: { content: string }[]): number {
    return Math.ceil(messages.reduce((acc, m) => acc + (m?.content?.length ?? 0), 0) / 4);
  }
}

/**
 * Load Z.ai config from the standard config file locations.
 * Used as a fallback when ZAI_TOKEN env var is not set.
 */
export function loadZaiConfigFromFile(): Partial<ZaiProviderConfig> | null {
  const paths = [
    join(process.cwd(), '.z-ai-config'),
    join(homedir(), '.z-ai-config'),
    '/etc/.z-ai-config',
  ];

  for (const p of paths) {
    try {
      const raw = readFileSync(p, 'utf-8');
      const config = JSON.parse(raw);
      if (config.baseUrl && config.apiKey) {
        return {
          apiKey: config.apiKey,
          baseUrl: config.baseUrl,
          token: config.token,
          userId: config.userId,
          chatId: config.chatId,
        };
      }
    } catch {
      // File doesn't exist or is invalid — try next
    }
  }
  return null;
}
