import { Injectable, Logger, BadRequestException } from '@nestjs/common';

// ── Types ────────────────────────────────────────────────────────────

interface ReferralRecord {
  code: string;
  userId: string;
  referredBy?: string;
  createdAt: Date;
}

export interface RewardTier {
  name: string;
  referralsRequired: number;
  description: string;
  badge: string;
  benefits: string[];
}

// ── Reward Tiers ─────────────────────────────────────────────────────

const REWARD_TIERS: RewardTier[] = [
  {
    name: 'Bronze',
    referralsRequired: 3,
    description: 'Bronze Referrer — You\'re getting started!',
    badge: '🥉',
    benefits: ['Custom profile badge', '1 free AI card generation per week'],
  },
  {
    name: 'Silver',
    referralsRequired: 10,
    description: 'Silver Referrer — Building your community!',
    badge: '🥈',
    benefits: [
      'Custom profile badge',
      '3 free AI card generations per week',
      'Priority quiz leaderboard display',
    ],
  },
  {
    name: 'Gold',
    referralsRequired: 25,
    description: 'Gold Referrer — A true kinship ambassador!',
    badge: '🥇',
    benefits: [
      'Custom profile badge',
      'Unlimited AI card generations',
      'Priority quiz leaderboard display',
      'Early access to new features',
    ],
  },
  {
    name: 'Platinum',
    referralsRequired: 50,
    description: 'Platinum Referrer — The ultimate kinship champion!',
    badge: '💎',
    benefits: [
      'Custom profile badge',
      'Unlimited AI card generations',
      'Priority quiz leaderboard display',
      'Early access to new features',
      'Dedicated support channel',
      'Family tree premium features',
    ],
  },
];

@Injectable()
export class ReferralService {
  private readonly logger = new Logger(ReferralService.name);
  private readonly referrals: Map<string, ReferralRecord> = new Map(); // code -> record
  private readonly userReferrals: Map<string, string[]> = new Map(); // userId -> [codes]

  /**
   * Generate a unique referral code for a user.
   */
  generateCode(userId: string): { code: string; createdAt: Date } {
    // Check if user already has a referral code
    const existing = [...this.referrals.values()].find(
      (r) => r.userId === userId && !r.referredBy,
    );
    if (existing) {
      return { code: existing.code, createdAt: existing.createdAt };
    }

    // Generate unique 8-char alphanumeric code
    const code = this.generateUniqueCode();

    const record: ReferralRecord = {
      code,
      userId,
      createdAt: new Date(),
    };

    this.referrals.set(code, record);

    // Track user's referral codes
    const userCodes = this.userReferrals.get(userId) || [];
    userCodes.push(code);
    this.userReferrals.set(userId, userCodes);

    return { code, createdAt: record.createdAt };
  }

  /**
   * Get referral stats for a user.
   */
  getStats(userId: string): {
    totalReferrals: number;
    referralCode: string | null;
    currentTier: string;
    nextTier: string | null;
    referralsToNextTier: number;
    recentReferrals: Array<{ code: string; referredAt: Date }>;
  } {
    // Find user's own referral code
    const ownCode = [...this.referrals.values()].find(
      (r) => r.userId === userId && !r.referredBy,
    );

    // Count successful referrals (codes generated by this user that were used by others)
    const userCodes = this.userReferrals.get(userId) || [];
    const successfulReferrals: ReferralRecord[] = [];

    for (const code of userCodes) {
      // Find all records where this user's code was the referredBy
      const refs = [...this.referrals.values()].filter(
        (r) => r.referredBy === code,
      );
      successfulReferrals.push(...refs);
    }

    const totalReferrals = successfulReferrals.length;

    // Determine current tier
    let currentTier = 'None';
    let nextTier: string | null = null;
    let referralsToNextTier = 0;

    for (let i = REWARD_TIERS.length - 1; i >= 0; i--) {
      if (totalReferrals >= REWARD_TIERS[i].referralsRequired) {
        currentTier = REWARD_TIERS[i].name;
        if (i < REWARD_TIERS.length - 1) {
          nextTier = REWARD_TIERS[i + 1].name;
          referralsToNextTier = REWARD_TIERS[i + 1].referralsRequired - totalReferrals;
        }
        break;
      }
    }

    if (currentTier === 'None' && REWARD_TIERS.length > 0) {
      nextTier = REWARD_TIERS[0].name;
      referralsToNextTier = REWARD_TIERS[0].referralsRequired - totalReferrals;
    }

    const recentReferrals = successfulReferrals
      .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime())
      .slice(0, 10)
      .map((r) => ({ code: r.code, referredAt: r.createdAt }));

    return {
      totalReferrals,
      referralCode: ownCode?.code || null,
      currentTier,
      nextTier,
      referralsToNextTier,
      recentReferrals,
    };
  }

  /**
   * Apply a referral code (new user was referred).
   */
  applyCode(
    userId: string,
    code: string,
  ): { success: boolean; message: string; referrer?: string } {
    const referral = this.referrals.get(code);

    if (!referral) {
      throw new BadRequestException('Invalid referral code');
    }

    // Check if user is trying to use their own code
    if (referral.userId === userId) {
      throw new BadRequestException('You cannot use your own referral code');
    }

    // Check if user has already applied a referral code
    const existingReferral = [...this.referrals.values()].find(
      (r) => r.userId === userId && r.referredBy,
    );
    if (existingReferral) {
      throw new BadRequestException('You have already applied a referral code');
    }

    // Create a new referral record for the referred user
    const newUserCode = this.generateUniqueCode();
    const record: ReferralRecord = {
      code: newUserCode,
      userId,
      referredBy: code,
      createdAt: new Date(),
    };

    this.referrals.set(newUserCode, record);
    const userCodes = this.userReferrals.get(userId) || [];
    userCodes.push(newUserCode);
    this.userReferrals.set(userId, userCodes);

    return {
      success: true,
      message: 'Referral code applied successfully! Welcome to Daxelo Kinrel!',
      referrer: referral.userId,
    };
  }

  /**
   * Get reward tiers.
   */
  getRewardTiers(): RewardTier[] {
    return REWARD_TIERS;
  }

  // ── Private Helpers ────────────────────────────────────────────────

  private generateUniqueCode(): string {
    const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; // Removed confusing chars like I, O, 0, 1
    let code = '';
    for (let i = 0; i < 8; i++) {
      code += chars.charAt(Math.floor(Math.random() * chars.length));
    }

    // Ensure uniqueness
    if (this.referrals.has(code)) {
      return this.generateUniqueCode();
    }

    return code;
  }
}
