// =============================================================================
// Track C v2.0 — Kinrel Timeline
// timeline.exporter.ts
// =============================================================================
// PDF export of the Kinrel Timeline. Section 11.2.
// Uses a minimal HTML-to-PDF approach (no heavy dependencies — we generate
// a print-ready HTML string and let the client render it via the browser's
// print-to-PDF, or via a server-side headless browser if available).
// =============================================================================

import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';

@Injectable()
export class TimelineExporter {
  private readonly logger = new Logger(TimelineExporter.name);

  constructor(private readonly prisma: PrismaService) {}

  /**
   * Generate a print-ready HTML document for the timeline.
   * The client renders this in a hidden iframe and triggers print-to-PDF.
   *
   * Section 19 edge case #13: Timeline export > 10MB → chunked by year.
   * This method accepts a year filter; if omitted, exports current year.
   */
  async exportPdfHtml(
    familyId: string,
    opts: { year?: number; from?: string; to?: string } = {},
  ): Promise<{ html: string; eventCount: number; year?: number }> {
    const where: any = { familyId };
    if (opts.year) {
      const start = new Date(opts.year, 0, 1);
      const end = new Date(opts.year + 1, 0, 1);
      where.occurredAt = { gte: start, lt: end };
    } else if (opts.from || opts.to) {
      where.occurredAt = {};
      if (opts.from) where.occurredAt.gte = new Date(opts.from);
      if (opts.to) where.occurredAt.lte = new Date(opts.to);
    }

    const [events, family] = await Promise.all([
      this.prisma.kinrelTimelineEvent.findMany({
        where,
        orderBy: { occurredAt: 'asc' },
        take: 5000,
      }),
      this.prisma.family.findUnique({
        where: { id: familyId },
        select: { name: true },
      }),
    ]);

    const familyName = family?.name ?? 'Family';
    const generatedAt = new Date().toISOString();
    const yearLabel = opts.year ? `${opts.year}` : 'All Time';

    const rows = events
      .map((e) => {
        const payloadStr = Object.keys(e.payload as any).length
          ? `<pre class="payload">${escapeHtml(JSON.stringify(e.payload, null, 2))}</pre>`
          : '';
        return `
          <tr>
            <td class="date">${e.occurredAt.toISOString()}</td>
            <td class="kind">${e.kind}</td>
            <td class="actor">${e.actorId ?? 'system'}</td>
            <td class="title">${escapeHtml(e.title)}${e.description ? `<p class="desc">${escapeHtml(e.description)}</p>` : ''}${payloadStr}</td>
          </tr>`;
      })
      .join('\n');

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(familyName)} — Kinrel Timeline (${yearLabel})</title>
  <style>
    @page { size: A4 landscape; margin: 1.5cm; }
    * { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; }
    body { color: #1a1a1a; }
    h1 { font-size: 22pt; margin: 0 0 4pt; }
    h2 { font-size: 11pt; color: #666; margin: 0 0 24pt; font-weight: normal; }
    table { width: 100%; border-collapse: collapse; }
    th, td { padding: 6pt 8pt; border-bottom: 1px solid #ddd; vertical-align: top; text-align: left; }
    th { background: #f5f5f5; font-size: 9pt; text-transform: uppercase; letter-spacing: 0.5pt; }
    td.date { white-space: nowrap; font-size: 9pt; color: #666; }
    td.kind { white-space: nowrap; font-size: 9pt; font-weight: 600; }
    td.actor { white-space: nowrap; font-size: 9pt; color: #666; }
    td.title { font-size: 10pt; }
    .desc { margin: 4pt 0 0; font-size: 9pt; color: #666; }
    .payload { margin: 4pt 0 0; font-size: 8pt; background: #f9f9f9; padding: 4pt; border-radius: 3pt; white-space: pre-wrap; max-height: 200pt; overflow: hidden; }
    footer { margin-top: 24pt; font-size: 8pt; color: #999; }
  </style>
</head>
<body>
  <h1>${escapeHtml(familyName)} — Kinrel Timeline</h1>
  <h2>Period: ${yearLabel} · Generated: ${generatedAt} · Events: ${events.length}</h2>
  <table>
    <thead>
      <tr><th>Date</th><th>Kind</th><th>Actor</th><th>Event</th></tr>
    </thead>
    <tbody>
      ${rows}
    </tbody>
  </table>
  <footer>Track C v2.0 — Kinrel Governance Engine · Append-only · Generated by Kinrel</footer>
</body>
</html>`;

    return { html, eventCount: events.length, year: opts.year };
  }
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
