-- Migration: 20260916100000_tugofwar_game.sql
-- Generated by scripts/tugofwar/build_migration.py (anchors verified
-- against the LIVE function definitions).

-- ============================================================================
-- Tug of War — team multiplayer mini-game (game #16)
--
-- Two teams pull a rope. Players spam-tap a PULL button; every validated tap
-- contributes force. The rope moves toward the stronger side and the first
-- team to pull the center flag past the victory line wins.
--
-- FAIRNESS: team strength is NORMALIZED — rope position is driven by
--   avgTapsPerPlayer = teamTaps / teamSize
-- so a 10-player team never crushes a 3-player team just by numbers.
--   ropePosition = (avgA - avgB) / 30   →  victory at |rope| >= 1
--   (a sustained 30 taps-per-player lead wins instantly)
--
-- ANTI-CHEAT: all validation is server-side (fn_tugofwar_pull):
--   • cumulative cap: floor(elapsedSec * 15) + 10  (max 15 taps/sec avg)
--   • per-call cap: 8 taps (clients batch every ~400 ms)
--
-- SYNC: game-row UPDATEs are throttled to >=150 ms apart server-side
-- (~6 authoritative updates/sec); clients interpolate at 60 fps and apply a
-- local impulse on their own taps for <100 ms perceived latency.
-- ============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- 1) Tables
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "tugofwar_games" (
  id                  TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  "familyId"          TEXT NOT NULL,
  "hostUserId"        TEXT NOT NULL,
  "hostUserName"      TEXT NOT NULL DEFAULT 'Host',
  "roomName"          TEXT,
  status              TEXT NOT NULL DEFAULT 'waiting',  -- waiting|in_progress|completed|cancelled
  "teamMode"          TEXT NOT NULL DEFAULT 'auto',     -- auto|manual|random
  "matchDurationSec"  INTEGER NOT NULL DEFAULT 60,      -- 30|60|90|0 (unlimited)
  "maxPlayers"        INTEGER NOT NULL DEFAULT 8,
  "teamATaps"         INTEGER NOT NULL DEFAULT 0,
  "teamBTaps"         INTEGER NOT NULL DEFAULT 0,
  "ropePosition"      REAL NOT NULL DEFAULT 0,          -- -1..+1 (+ = Team A lead)
  "lastRopeAt"        TIMESTAMPTZ,                      -- throttle for rope updates
  "winnerTeam"        TEXT,                             -- 'A'|'B'|NULL (draw)
  "winnerUserIds"     JSONB NOT NULL DEFAULT '[]'::jsonb,
  "endReason"         TEXT,                             -- victory_line|time_up|walkover
  "startedAt"         TIMESTAMPTZ,
  "endsAt"            TIMESTAMPTZ,                      -- startedAt + duration (NULL = unlimited)
  "completedAt"       TIMESTAMPTZ,
  "createdAt"         TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- shared temporary-room lifecycle columns (see 20260913120000)
  "autoCloseDeadline" TIMESTAMPTZ,
  "cancelledAt"       TIMESTAMPTZ,
  "closedAt"          TIMESTAMPTZ,
  "hostReady"         BOOLEAN DEFAULT true,
  "spectatorsEnabled" BOOLEAN DEFAULT true,
  "lastActivityAt"    TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "tugofwar_players" (
  id                TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  "gameId"          TEXT NOT NULL REFERENCES "tugofwar_games"(id) ON DELETE CASCADE,
  "userId"          TEXT NOT NULL,
  "userName"        TEXT NOT NULL,
  team              TEXT,                              -- 'A'|'B'|NULL (unassigned)
  "pullCount"       INTEGER NOT NULL DEFAULT 0,        -- validated taps
  "lastPullAt"      TIMESTAMPTZ,
  "isReady"         BOOLEAN NOT NULL DEFAULT false,
  "readyAt"         TIMESTAMPTZ,
  "joinedAt"        TIMESTAMPTZ NOT NULL DEFAULT now(),
  "lastActivityAt"  TIMESTAMPTZ DEFAULT now(),
  UNIQUE ("gameId", "userId")
);

CREATE INDEX IF NOT EXISTS idx_tugofwar_players_game ON "tugofwar_players" ("gameId");
CREATE INDEX IF NOT EXISTS idx_tugofwar_games_family_status ON "tugofwar_games" ("familyId", "status");

-- ─────────────────────────────────────────────────────────────────────────────
-- 2) RLS (family-scoped, same shape as every other game table)
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE "tugofwar_games" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tugofwar_players" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "tugofwar_games_select" ON "tugofwar_games";
CREATE POLICY "tugofwar_games_select" ON "tugofwar_games" FOR SELECT TO authenticated USING (
  EXISTS (SELECT 1 FROM "FamilyMember" fm
          WHERE fm."familyId" = "tugofwar_games"."familyId"
            AND fm."userId" = auth.uid()::text));

DROP POLICY IF EXISTS "tugofwar_games_insert" ON "tugofwar_games";
CREATE POLICY "tugofwar_games_insert" ON "tugofwar_games" FOR INSERT TO authenticated WITH CHECK (
  EXISTS (SELECT 1 FROM "FamilyMember" fm
          WHERE fm."familyId" = "tugofwar_games"."familyId"
            AND fm."userId" = auth.uid()::text)
  AND "hostUserId" = auth.uid()::text);

DROP POLICY IF EXISTS "tugofwar_games_update" ON "tugofwar_games";
CREATE POLICY "tugofwar_games_update" ON "tugofwar_games" FOR UPDATE TO authenticated USING (
  EXISTS (SELECT 1 FROM "FamilyMember" fm
          WHERE fm."familyId" = "tugofwar_games"."familyId"
            AND fm."userId" = auth.uid()::text));

DROP POLICY IF EXISTS "tugofwar_players_select" ON "tugofwar_players";
CREATE POLICY "tugofwar_players_select" ON "tugofwar_players" FOR SELECT TO authenticated USING (
  EXISTS (SELECT 1 FROM "tugofwar_games" g
          JOIN "FamilyMember" fm ON fm."familyId" = g."familyId"
          WHERE g."id" = "tugofwar_players"."gameId"
            AND fm."userId" = auth.uid()::text));

DROP POLICY IF EXISTS "tugofwar_players_insert" ON "tugofwar_players";
CREATE POLICY "tugofwar_players_insert" ON "tugofwar_players" FOR INSERT TO authenticated WITH CHECK (
  "userId" = auth.uid()::text
  AND EXISTS (SELECT 1 FROM "tugofwar_games" g
              JOIN "FamilyMember" fm ON fm."familyId" = g."familyId"
              WHERE g."id" = "tugofwar_players"."gameId"
                AND fm."userId" = auth.uid()::text));

DROP POLICY IF EXISTS "tugofwar_players_update" ON "tugofwar_players";
CREATE POLICY "tugofwar_players_update" ON "tugofwar_players" FOR UPDATE TO authenticated USING (
  "userId" = auth.uid()::text)
WITH CHECK (
  "userId" = auth.uid()::text);

DROP POLICY IF EXISTS "tugofwar_players_delete_self" ON "tugofwar_players";
CREATE POLICY "tugofwar_players_delete_self" ON "tugofwar_players" FOR DELETE TO authenticated USING (
  "userId" = auth.uid()::text);

-- ─────────────────────────────────────────────────────────────────────────────
-- 3) Realtime (REPLICA IDENTITY FULL so UPDATE payloads carry the whole row)
-- ─────────────────────────────────────────────────────────────────────────────

ALTER PUBLICATION supabase_realtime ADD TABLE "tugofwar_games";
ALTER PUBLICATION supabase_realtime ADD TABLE "tugofwar_players";
ALTER TABLE "tugofwar_games" REPLICA IDENTITY FULL;
ALTER TABLE "tugofwar_players" REPLICA IDENTITY FULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- 4) Game RPCs
-- ─────────────────────────────────────────────────────────────────────────────

-- Player picks their own team in the lobby (manual mode). Host-only override
-- is intentionally NOT offered: auto-balance / shuffle cover host needs.
CREATE OR REPLACE FUNCTION fn_tugofwar_set_team(p_game_id text, p_team text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  g record;
BEGIN
  IF p_team NOT IN ('A','B') THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'bad_team');
  END IF;

  SELECT status, "hostUserId" INTO g FROM "tugofwar_games" WHERE "id" = p_game_id;
  IF g.status IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_found');
  END IF;
  IF g.status <> 'waiting' THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'already_started');
  END IF;

  UPDATE "tugofwar_players"
     SET team = p_team, "lastActivityAt" = now()
   WHERE "gameId" = p_game_id AND "userId" = auth.uid()::text;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_player');
  END IF;

  PERFORM fn_touch_game_activity('tugofwar_games', p_game_id);
  RETURN jsonb_build_object('ok', true);
END;
$$;
GRANT EXECUTE ON FUNCTION fn_tugofwar_set_team(text, text) TO authenticated;

-- Host tool: 'auto' assigns every UNASSIGNED player to the smaller team
-- (join order); 'random' reshuffles EVERYONE into even halves.
CREATE OR REPLACE FUNCTION fn_tugofwar_assign_teams(p_game_id text, p_mode text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  g record;
  v_n_a int; v_n_b int;
  r record;
  v_team text;
  v_i int := 0;
BEGIN
  SELECT status, "hostUserId" INTO g FROM "tugofwar_games" WHERE "id" = p_game_id;
  IF g.status IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_found');
  END IF;
  IF g."hostUserId" <> auth.uid()::text THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_host');
  END IF;
  IF g.status <> 'waiting' THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'already_started');
  END IF;
  IF p_mode NOT IN ('auto','random') THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'bad_mode');
  END IF;

  IF p_mode = 'auto' THEN
    -- Unassigned players → the smaller team (join order breaks ties).
    FOR r IN
      SELECT id FROM "tugofwar_players"
       WHERE "gameId" = p_game_id AND team IS NULL
       ORDER BY "joinedAt" ASC, id ASC
    LOOP
      SELECT COUNT(*) INTO v_n_a FROM "tugofwar_players"
       WHERE "gameId" = p_game_id AND team = 'A';
      SELECT COUNT(*) INTO v_n_b FROM "tugofwar_players"
       WHERE "gameId" = p_game_id AND team = 'B';
      v_team := CASE WHEN v_n_a <= v_n_b THEN 'A' ELSE 'B' END;
      UPDATE "tugofwar_players" SET team = v_team WHERE id = r.id;
    END LOOP;
  ELSE
    -- Random: shuffle everyone, deal alternately → even halves.
    FOR r IN
      SELECT id FROM "tugofwar_players"
       WHERE "gameId" = p_game_id
       ORDER BY random()
    LOOP
      v_team := CASE WHEN v_i % 2 = 0 THEN 'A' ELSE 'B' END;
      UPDATE "tugofwar_players" SET team = v_team WHERE id = r.id;
      v_i := v_i + 1;
    END LOOP;
  END IF;

  SELECT COUNT(*) FILTER (WHERE team = 'A'), COUNT(*) FILTER (WHERE team = 'B')
    INTO v_n_a, v_n_b
    FROM "tugofwar_players" WHERE "gameId" = p_game_id;

  PERFORM fn_touch_game_activity('tugofwar_games', p_game_id);
  RETURN jsonb_build_object('ok', true, 'teamA', v_n_a, 'teamB', v_n_b);
END;
$$;
GRANT EXECUTE ON FUNCTION fn_tugofwar_assign_teams(text, text) TO authenticated;

-- Host starts the match. Requires >= 1 player per team. In 'auto' mode any
-- unassigned players are balanced first, so the host can just tap Start.
CREATE OR REPLACE FUNCTION fn_tugofwar_start(p_game_id text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  g record;
  v_n_a int; v_n_b int;
BEGIN
  SELECT * INTO g FROM "tugofwar_games" WHERE "id" = p_game_id FOR UPDATE;
  IF g.id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_found');
  END IF;
  IF g."hostUserId" <> auth.uid()::text THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_host');
  END IF;
  IF g.status <> 'waiting' THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'already_started');
  END IF;

  -- Auto mode: balance unassigned players before validating teams.
  IF g."teamMode" = 'auto' THEN
    PERFORM fn_tugofwar_assign_teams(p_game_id, 'auto');
  END IF;

  SELECT COUNT(*) FILTER (WHERE team = 'A'), COUNT(*) FILTER (WHERE team = 'B')
    INTO v_n_a, v_n_b
    FROM "tugofwar_players" WHERE "gameId" = p_game_id;

  IF v_n_a = 0 OR v_n_b = 0 THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'empty_team',
                              'teamA', v_n_a, 'teamB', v_n_b);
  END IF;

  UPDATE "tugofwar_games"
     SET status = 'in_progress',
         "startedAt" = now(),
         "endsAt" = CASE WHEN "matchDurationSec" = 0 THEN NULL
                         ELSE now() + ("matchDurationSec" * interval '1 second') END,
         "lastRopeAt" = now(),
         "lastActivityAt" = now(),
         "autoCloseDeadline" = NULL
   WHERE "id" = p_game_id;

  RETURN jsonb_build_object('ok', true);
END;
$$;
GRANT EXECUTE ON FUNCTION fn_tugofwar_start(text) TO authenticated;

-- Internal: finish an expired timed match by the higher average
-- (fairness formula — teamTaps / teamSize). Draw when averages are equal.
CREATE OR REPLACE FUNCTION fn_tugofwar_finish_by_time(p_game_id text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_sum_a int; v_sum_b int; v_n_a int; v_n_b int;
  v_avg_a real; v_avg_b real;
  v_winner text;
  v_winner_ids jsonb;
BEGIN
  SELECT COALESCE(SUM("pullCount"),0), COUNT(*) INTO v_sum_a, v_n_a
    FROM "tugofwar_players" WHERE "gameId" = p_game_id AND team = 'A';
  SELECT COALESCE(SUM("pullCount"),0), COUNT(*) INTO v_sum_b, v_n_b
    FROM "tugofwar_players" WHERE "gameId" = p_game_id AND team = 'B';

  v_avg_a := CASE WHEN v_n_a = 0 THEN 0 ELSE v_sum_a::real / v_n_a END;
  v_avg_b := CASE WHEN v_n_b = 0 THEN 0 ELSE v_sum_b::real / v_n_b END;

  IF v_avg_a > v_avg_b THEN v_winner := 'A';
  ELSIF v_avg_b > v_avg_a THEN v_winner := 'B';
  ELSE v_winner := NULL;  -- dead-heat draw
  END IF;

  v_winner_ids := COALESCE((
    SELECT jsonb_agg("userId") FROM "tugofwar_players"
     WHERE "gameId" = p_game_id AND team = v_winner
  ), '[]'::jsonb);

  UPDATE "tugofwar_games"
     SET status = 'completed',
         "completedAt" = now(),
         "teamATaps" = v_sum_a,
         "teamBTaps" = v_sum_b,
         "winnerTeam" = v_winner,
         "winnerUserIds" = v_winner_ids,
         "endReason" = 'time_up',
         "lastActivityAt" = now()
   WHERE "id" = p_game_id
     AND status = 'in_progress';
END;
$$;

-- The hot path. Clients batch taps (~400 ms windows) and call this.
-- Server-side validation only — clients can never inflate their counts.
CREATE OR REPLACE FUNCTION fn_tugofwar_pull(p_game_id text, p_taps int)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  g record;
  me record;
  v_accepted int;
  v_elapsed real;
  v_cap int;
  v_sum_a int; v_sum_b int; v_n_a int; v_n_b int;
  v_avg_a real; v_avg_b real;
  v_rope real;
BEGIN
  SELECT * INTO g FROM "tugofwar_games" WHERE "id" = p_game_id;
  IF g.id IS NULL OR g.status <> 'in_progress' THEN
    RETURN jsonb_build_object('accepted', 0, 'status', g.status);
  END IF;

  -- Timer expiry beats pulling.
  IF g."endsAt" IS NOT NULL AND now() > g."endsAt" THEN
    PERFORM fn_tugofwar_finish_by_time(p_game_id);
    RETURN jsonb_build_object('accepted', 0, 'status', 'completed');
  END IF;

  SELECT * INTO me FROM "tugofwar_players"
   WHERE "gameId" = p_game_id AND "userId" = auth.uid()::text;
  IF me.id IS NULL OR me.team IS NULL THEN
    RETURN jsonb_build_object('accepted', 0, 'reason', 'not_player');
  END IF;

  -- ── Anti-cheat ────────────────────────────────────────────────────────
  -- Cumulative average cap of 15 taps/sec (+10 burst budget) since start,
  -- plus a hard per-call ceiling of 8 (batch cadence is ~2.5 calls/sec).
  v_elapsed := GREATEST(EXTRACT(epoch FROM (now() - g."startedAt")), 0);
  v_cap := FLOOR(v_elapsed * 15)::int + 10;
  v_accepted := LEAST(GREATEST(p_taps, 0), GREATEST(v_cap - me."pullCount", 0), 8);
  IF v_accepted <= 0 THEN
    RETURN jsonb_build_object('accepted', 0, 'rateLimited', true);
  END IF;

  UPDATE "tugofwar_players"
     SET "pullCount" = "pullCount" + v_accepted,
         "lastPullAt" = now()
   WHERE "id" = me.id;

  -- ── Throttled authoritative rope update (~6 Hz globally) ──────────────
  IF g."lastRopeAt" IS NULL OR now() - g."lastRopeAt" > interval '150 milliseconds' THEN
    SELECT COALESCE(SUM("pullCount"),0), COUNT(*) INTO v_sum_a, v_n_a
      FROM "tugofwar_players" WHERE "gameId" = p_game_id AND team = 'A';
    SELECT COALESCE(SUM("pullCount"),0), COUNT(*) INTO v_sum_b, v_n_b
      FROM "tugofwar_players" WHERE "gameId" = p_game_id AND team = 'B';

    v_avg_a := CASE WHEN v_n_a = 0 THEN 0 ELSE v_sum_a::real / v_n_a END;
    v_avg_b := CASE WHEN v_n_b = 0 THEN 0 ELSE v_sum_b::real / v_n_b END;

    -- FAIRNESS: normalized per-player averages, not raw team totals.
    v_rope := LEAST(GREATEST((v_avg_a - v_avg_b) / 30.0, -1.0), 1.0);

    IF v_rope >= 1.0 AND v_n_a > 0 AND v_n_b > 0 THEN
      UPDATE "tugofwar_games"
         SET status = 'completed', "completedAt" = now(),
             "teamATaps" = v_sum_a, "teamBTaps" = v_sum_b,
             "ropePosition" = 1.0, "lastRopeAt" = now(),
             "winnerTeam" = 'A',
             "winnerUserIds" = COALESCE((
               SELECT jsonb_agg("userId") FROM "tugofwar_players"
                WHERE "gameId" = p_game_id AND team = 'A'), '[]'::jsonb),
             "endReason" = 'victory_line',
             "lastActivityAt" = now()
       WHERE "id" = p_game_id AND status = 'in_progress';
    ELSIF v_rope <= -1.0 AND v_n_a > 0 AND v_n_b > 0 THEN
      UPDATE "tugofwar_games"
         SET status = 'completed', "completedAt" = now(),
             "teamATaps" = v_sum_a, "teamBTaps" = v_sum_b,
             "ropePosition" = -1.0, "lastRopeAt" = now(),
             "winnerTeam" = 'B',
             "winnerUserIds" = COALESCE((
               SELECT jsonb_agg("userId") FROM "tugofwar_players"
                WHERE "gameId" = p_game_id AND team = 'B'), '[]'::jsonb),
             "endReason" = 'victory_line',
             "lastActivityAt" = now()
       WHERE "id" = p_game_id AND status = 'in_progress';
    ELSE
      UPDATE "tugofwar_games"
         SET "teamATaps" = v_sum_a, "teamBTaps" = v_sum_b,
             "ropePosition" = v_rope, "lastRopeAt" = now(),
             "lastActivityAt" = now()
       WHERE "id" = p_game_id;
    END IF;
    RETURN jsonb_build_object('accepted', v_accepted, 'ropePosition', v_rope);
  END IF;

  RETURN jsonb_build_object('accepted', v_accepted);
END;
$$;
GRANT EXECUTE ON FUNCTION fn_tugofwar_pull(text, int) TO authenticated;

-- Lightweight watchdog any client can run (every ~2 s while playing): ends
-- a timed match the moment it expires, even if everyone stopped pulling.
CREATE OR REPLACE FUNCTION fn_tugofwar_tick(p_game_id text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  g record;
BEGIN
  SELECT status, "endsAt" INTO g FROM "tugofwar_games" WHERE "id" = p_game_id;
  IF g.status IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_found');
  END IF;
  IF g.status = 'in_progress' AND g."endsAt" IS NOT NULL AND now() > g."endsAt" THEN
    PERFORM fn_tugofwar_finish_by_time(p_game_id);
    RETURN jsonb_build_object('ok', true, 'status', 'completed');
  END IF;
  RETURN jsonb_build_object('ok', true, 'status', g.status);
END;
$$;
GRANT EXECUTE ON FUNCTION fn_tugofwar_tick(text) TO authenticated;

-- Leave the match at any phase. In an in_progress match, if a whole team
-- walks out the other team wins by walkover (win condition #3).
CREATE OR REPLACE FUNCTION fn_tugofwar_leave(p_game_id text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  g record;
  me record;
  v_n_a int; v_n_b int;
  v_family_id text;
  v_user_name text;
BEGIN
  SELECT * INTO g FROM "tugofwar_games" WHERE "id" = p_game_id;
  IF g.id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_found');
  END IF;

  SELECT * INTO me FROM "tugofwar_players"
   WHERE "gameId" = p_game_id AND "userId" = auth.uid()::text;
  IF me.id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_player');
  END IF;

  -- Remove the player row + bookkeeping (participant leftAt + leave event).
  -- NOTE: while waiting we deliberately do NOT use fn_leave_game_room's
  -- host-cancels-room semantics — the host path goes through
  -- fn_cancel_waiting_room from the provider, exactly like Ludo.
  DELETE FROM "tugofwar_players" WHERE id = me.id;

  SELECT "userName", "familyId" INTO v_user_name, v_family_id
    FROM "game_participants"
   WHERE "gameTable" = 'tugofwar_games' AND "gameId" = p_game_id
     AND "userId" = auth.uid()::text;
  IF v_user_name IS NOT NULL THEN
    UPDATE "game_participants"
       SET "leftAt" = now(), "connectionState" = 'offline'
     WHERE "gameTable" = 'tugofwar_games' AND "gameId" = p_game_id
       AND "userId" = auth.uid()::text;
    INSERT INTO "game_room_events"
      ("gameTable","gameId","familyId","userId","userName","eventType","payload")
    VALUES
      ('tugofwar_games', p_game_id, v_family_id, auth.uid()::text, v_user_name,
       'leave', jsonb_build_object('reason', 'left'));
  END IF;

  -- Walkover: an empty team during a live match hands the win to the other side.
  IF g.status = 'in_progress' THEN
    SELECT COUNT(*) FILTER (WHERE team = 'A'), COUNT(*) FILTER (WHERE team = 'B')
      INTO v_n_a, v_n_b
      FROM "tugofwar_players" WHERE "gameId" = p_game_id;

    IF (v_n_a = 0 AND v_n_b > 0) OR (v_n_b = 0 AND v_n_a > 0) THEN
      UPDATE "tugofwar_games"
         SET status = 'completed', "completedAt" = now(),
             "winnerTeam" = CASE WHEN v_n_a > 0 THEN 'A' ELSE 'B' END,
             "winnerUserIds" = COALESCE((
               SELECT jsonb_agg("userId") FROM "tugofwar_players"
                WHERE "gameId" = p_game_id), '[]'::jsonb),
             "endReason" = 'walkover',
             "lastActivityAt" = now()
       WHERE "id" = p_game_id AND status = 'in_progress';
    END IF;
  END IF;

  RETURN jsonb_build_object('ok', true);
END;
$$;
GRANT EXECUTE ON FUNCTION fn_tugofwar_leave(text) TO authenticated;

-- ─────────────────────────────────────────────────────────────────────────────
-- 5) Archive-on-complete trigger (Ghost Painter pattern)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION fn__tugofwar_on_complete()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW."status" = 'completed' AND COALESCE(OLD."status", '') <> 'completed' THEN
    BEGIN
      PERFORM public.fn__archive_family_match('tugofwar_games', NEW."id");
    EXCEPTION WHEN OTHERS THEN
      RAISE NOTICE 'tug of war archive failed for %: %', NEW."id", SQLERRM;
    END;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_tugofwar_archive ON "tugofwar_games";
CREATE TRIGGER trg_tugofwar_archive
AFTER UPDATE ON "tugofwar_games"
FOR EACH ROW EXECUTE FUNCTION public.fn__tugofwar_on_complete();

-- ─────────────────────────────────────────────────────────────────────────────
-- 6) Champion badge seed (idempotent)
-- ─────────────────────────────────────────────────────────────────────────────

INSERT INTO "Badge" ("id","slug","name","nameHi","description","icon","category","tier","threshold","isSecret","createdAt")
VALUES
  (gen_random_uuid()::text,'tugofwar-titan','Tug of War Titan','रस्साकशी टाइटन','Win 5 Tug of War matches','🪢','games','gold',5,false,now())
ON CONFLICT ("slug") DO NOTHING;


-- ═══ fn_touch_game_activity: whitelist += tugofwar_games ═══

CREATE OR REPLACE FUNCTION public.fn_touch_game_activity(p_game_table text, p_game_id text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
    IF p_game_table NOT IN (
        'antakshari_games', 'chitmatch_games', 'bingo_games', 'ludo_games',
        'sos_games', 'dotsboxes_games', 'nameplace_games',
        'truthordare_games', 'twotruths_games', 'redlight_rounds',
        'chess_games', 'tictactoe_games', 'checkers_games', 'carrom_games',
        'tugofwar_games'
    ) THEN
        RAISE EXCEPTION 'Unknown game table: %', p_game_table;
    END IF;
    EXECUTE format(
        'UPDATE public.%I SET "lastActivityAt" = now() WHERE "id" = $1;',
        p_game_table
    ) USING p_game_id;
END;
$function$;


-- ═══ fn__hard_delete_room: whitelist += tugofwar_games ═══

CREATE OR REPLACE FUNCTION public.fn__hard_delete_room(p_game_table text, p_game_id text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
    IF p_game_table NOT IN (
        'antakshari_games', 'chitmatch_games', 'bingo_games', 'ludo_games',
        'sos_games', 'dotsboxes_games', 'nameplace_games',
        'truthordare_games', 'twotruths_games', 'redlight_rounds',
        'chess_games', 'tictactoe_games', 'checkers_games', 'carrom_games',
        'tugofwar_games'
    ) THEN
        RAISE EXCEPTION 'Unknown game table: %', p_game_table;
    END IF;

    -- 1. Delete pending invites for this room (stale invites must never
    --    re-open a closed room).
    DELETE FROM public.game_invites
    WHERE "gameTable" = p_game_table AND "gameId" = p_game_id;

    -- 2. Delete all participant rows (realtime fans these DELETEs out to
    --    every connected lobby — player lists empty immediately).
    DELETE FROM public.game_participants
    WHERE "gameTable" = p_game_table AND "gameId" = p_game_id;

    -- 3. Delete all spectator rows.
    DELETE FROM public.game_spectators
    WHERE "gameTable" = p_game_table AND "gameId" = p_game_id;

    -- 4. Delete the room event log (the 'cancel' event inserted by the
    --    caller has already been delivered via realtime WAL).
    DELETE FROM public.game_room_events
    WHERE "gameTable" = p_game_table AND "gameId" = p_game_id;

    -- 5. DELETE the game row itself — all game-specific child tables
    --    (players / moves / cards / turns / tokens / rounds / claims)
    --    cascade via FK ON DELETE CASCADE. After this returns, the room
    --    no longer exists anywhere in the database.
    EXECUTE format('DELETE FROM public.%I WHERE "id" = $1;', p_game_table)
    USING p_game_id;
END;
$function$;


-- ═══ fn_cancel_waiting_room: whitelist += tugofwar_games ═══

CREATE OR REPLACE FUNCTION public.fn_cancel_waiting_room(p_game_table text, p_game_id text, p_user_id text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
    v_host text;
    v_status text;
    v_family_id text;
BEGIN
    IF p_game_table NOT IN (
        'antakshari_games', 'chitmatch_games', 'bingo_games', 'ludo_games',
        'sos_games', 'dotsboxes_games', 'nameplace_games',
        'truthordare_games', 'twotruths_games', 'redlight_rounds',
        'tugofwar_games'
    ) THEN
        RETURN;
    END IF;

    EXECUTE format(
        'SELECT "hostUserId", "status", "familyId" FROM public.%I WHERE "id" = $1;',
        p_game_table
    ) INTO v_host, v_status, v_family_id USING p_game_id;

    IF v_host IS NULL OR v_status IS NULL THEN
        RETURN; -- room already gone — nothing to cancel
    END IF;

    IF v_host = p_user_id THEN
        -- Notify every connected client that the room is closed.
        INSERT INTO "game_room_events"
            ("gameTable", "gameId", "familyId", "userId", "userName", "eventType", "payload")
        VALUES
            (p_game_table, p_game_id, v_family_id, p_user_id, 'Host', 'cancel',
             jsonb_build_object('reason', 'host_cancelled'));

        -- Delete the room immediately from the database.
        PERFORM public.fn__hard_delete_room(p_game_table, p_game_id);
    END IF;
END;
$function$;


-- ═══ fn_end_game: whitelist += tugofwar_games ═══

CREATE OR REPLACE FUNCTION public.fn_end_game(p_game_table text, p_game_id text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
    IF p_game_table NOT IN (
        'antakshari_games', 'chitmatch_games', 'bingo_games', 'ludo_games',
        'sos_games', 'dotsboxes_games', 'nameplace_games',
        'truthordare_games', 'twotruths_games', 'redlight_rounds',
        'chess_games', 'tictactoe_games', 'checkers_games', 'carrom_games',
        'tugofwar_games'
    ) THEN
        RAISE EXCEPTION 'Unknown game table: %', p_game_table;
    END IF;

    -- ── Truth or Dare is an open-ended party game: the match ends when the
    --    host closes the table. Mark it completed FIRST so the archive
    --    records the family moment (participation for everyone) instead of
    --    discarding an "in-progress" row that the hard delete then erases.
    IF p_game_table = 'truthordare_games' THEN
        UPDATE public.truthordare_games
           SET "status" = 'completed',
               "completedAt" = now(),
               "lastActivityAt" = now()
         WHERE "id" = p_game_id
           AND "status" = 'in_progress';
    END IF;

    -- ── Family Gaming Ecosystem: archive completed matches BEFORE the
    --    hard delete (idempotent no-op for cancelled/abandoned rooms).
    BEGIN
        PERFORM public.fn__archive_family_match(p_game_table, p_game_id);
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'ecosystem archive failed for %/%: %', p_game_table, p_game_id, SQLERRM;
    END;

    PERFORM public.fn__hard_delete_room(p_game_table, p_game_id);
END;
$function$;


-- ═══ fn_get_match_ecosystem: whitelist += tugofwar_games ═══

CREATE OR REPLACE FUNCTION public.fn_get_match_ecosystem(p_game_table text, p_game_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_summary jsonb;
  v_meta jsonb;
BEGIN
  IF p_game_table NOT IN (
    'antakshari_games','chitmatch_games','bingo_games','ludo_games',
    'sos_games','dotsboxes_games','nameplace_games','truthordare_games',
    'twotruths_games','redlight_rounds','chess_games','tictactoe_games',
    'checkers_games','carrom_games','ghost_painter_rounds','tugofwar_games'
  ) THEN
    RETURN NULL;
  END IF;

  -- Ensure processing has happened (no-op if already archived or not terminal)
  v_summary := public.fn__archive_family_match(p_game_table, p_game_id);

  -- If this call did the processing, return its rich summary directly
  IF v_summary IS NOT NULL THEN
    RETURN v_summary;
  END IF;

  -- Either already archived, or game row not terminal/gone.
  v_meta := public.fn__game_meta() -> p_game_table;

  SELECT jsonb_build_object(
    'matchId', h."id",
    'gameTable', h."gameTable",
    'gameName', COALESCE(v_meta->>'name', h."gameTable"),
    'gameIcon', COALESCE(v_meta->>'icon', '🎮'),
    'familyId', h."familyId",
    'winners', to_jsonb(h."winnerNames"),
    'playerCount', h."playerCount",
    'durationSeconds', h."durationSeconds",
    'archived', true,
    'newBadges', COALESCE(h."rewardsJson"->'newBadges', '[]'::jsonb),
    'completedChallenges', COALESCE(h."rewardsJson"->'completedChallenges', '[]'::jsonb),
    'milestones', COALESCE(h."rewardsJson"->'milestones', '[]'::jsonb),
    'players', COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
        'userId', p."userId", 'userName', p."userName", 'result', p."result"))
      FROM "game_match_players" p WHERE p."matchId" = h."id"
    ), '[]'::jsonb)
  )
  INTO v_summary
  FROM "game_match_history" h
  WHERE h."gameTable" = p_game_table AND h."gameId" = p_game_id;

  RETURN v_summary;  -- NULL when the room was cancelled (never archived)
END;
$function$;


-- ═══ fn_close_expired_rooms: tables += tugofwar_games ═══

CREATE OR REPLACE FUNCTION public.fn_close_expired_rooms()
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
    DECLARE
        v_closed_count integer := 0;
        t text;
        r record;
    BEGIN
        FOREACH t IN ARRAY ARRAY[
            'bingo_games', 'ludo_games', 'checkers_games', 'carrom_games',
            'chess_games', 'sos_games', 'antakshari_games', 'tictactoe_games',
            'truthordare_games', 'twotruths_games', 'dotsboxes_games',
            'nameplace_games', 'chitmatch_games', 'redlight_rounds',
            'tugofwar_games'
        ] LOOP
            FOR r IN EXECUTE format(
                'SELECT "id" AS game_id, "familyId" AS family_id
                 FROM %I
                 WHERE "autoCloseDeadline" IS NOT NULL
                   AND "autoCloseDeadline" <= now()
                   AND "cancelledAt" IS NULL
                   AND "closedAt" IS NULL
                   AND (
                       "status" IN (''lobby'', ''waiting'')
                       OR "status" IS NULL
                   )',
                t
            ) LOOP
                -- Post the auto_close event FIRST so realtime clients
                -- (waiting rooms, boards) receive it via WAL before the
                -- rows vanish.
                INSERT INTO "game_room_events"
                    ("gameTable", "gameId", "familyId", "userId", "userName", "eventType", "payload")
                VALUES
                    (t, r.game_id, r.family_id, NULL, 'System', 'auto_close',
                     jsonb_build_object('reason', 'auto_close_deadline_passed'));

                -- Remove the room entirely (invites, participants,
                -- spectators, events + game row; children cascade).
                BEGIN
                    PERFORM public.fn__hard_delete_room(t, r.game_id);
                EXCEPTION WHEN OTHERS THEN
                    -- Unknown table whitelist miss — fall back to soft close.
                    EXECUTE format(
                        'UPDATE %I SET "closedAt" = now(), "cancelledAt" = COALESCE("cancelledAt", now()) WHERE "id" = $1',
                        t
                    ) USING r.game_id;
                    DELETE FROM "game_participants"
                    WHERE "gameTable" = t AND "gameId" = r.game_id;
                    DELETE FROM "game_spectators"
                    WHERE "gameTable" = t AND "gameId" = r.game_id;
                END;

                v_closed_count := v_closed_count + 1;
            END LOOP;
        END LOOP;

        RETURN v_closed_count;
    END;
$function$;


-- ═══ fn_cleanup_completed_games: tables += tugofwar_games ═══

CREATE OR REPLACE FUNCTION public.fn_cleanup_completed_games()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
    tbl text;
    completed_tables text[] := ARRAY[
        'antakshari_games', 'chitmatch_games', 'bingo_games', 'ludo_games',
        'dotsboxes_games', 'nameplace_games', 'truthordare_games',
        'twotruths_games', 'chess_games', 'tictactoe_games',
        'checkers_games', 'carrom_games', 'tugofwar_games'
    ];
    finished_tables text[] := ARRAY['sos_games', 'redlight_rounds'];
    gp_round record;
BEGIN
    FOREACH tbl IN ARRAY completed_tables LOOP
        BEGIN
            EXECUTE format(
                'DELETE FROM public.game_invites
                 WHERE "gameTable" = $1
                   AND "gameId" IN (
                     SELECT "id" FROM public.%I
                     WHERE public.fn_is_completed_status("status")
                       AND "completedAt" IS NOT NULL
                       AND "completedAt" < now() - interval ''1 hour''
                   );',
                tbl
            ) USING tbl;
            EXECUTE format(
                'DELETE FROM public.%I
                 WHERE public.fn_is_completed_status("status")
                   AND "completedAt" IS NOT NULL
                   AND "completedAt" < now() - interval ''1 hour'';',
                tbl
            );
        EXCEPTION WHEN OTHERS THEN
            RAISE NOTICE 'fn_cleanup_completed_games: skip %: %', tbl, SQLERRM;
        END;
    END LOOP;

    FOREACH tbl IN ARRAY finished_tables LOOP
        BEGIN
            EXECUTE format(
                'DELETE FROM public.game_invites
                 WHERE "gameTable" = $1
                   AND "gameId" IN (
                     SELECT "id" FROM public.%I
                     WHERE public.fn_is_completed_status("status")
                       AND "finishedAt" IS NOT NULL
                       AND "finishedAt" < now() - interval ''1 hour''
                   );',
                tbl
            ) USING tbl;
            EXECUTE format(
                'DELETE FROM public.%I
                 WHERE public.fn_is_completed_status("status")
                   AND "finishedAt" IS NOT NULL
                   AND "finishedAt" < now() - interval ''1 hour'';',
                tbl
            );
        EXCEPTION WHEN OTHERS THEN
            RAISE NOTICE 'fn_cleanup_completed_games: skip %: %', tbl, SQLERRM;
        END;
    END LOOP;

    -- ── Ghost Painter rounds ──
    -- (a) Retire stale abandoned rounds (stuck in drawing/guessing for > 2h):
    --     flip to completed; the archive trigger then runs (rounds without
    --     any guesses are skipped by the archive guard).
    BEGIN
        UPDATE public.ghost_painter_rounds
           SET "status" = 'completed',
               "endsAt" = COALESCE("endsAt", now())
         WHERE "status" IN ('drawing','guessing')
           AND "startedAt" < now() - interval '2 hours';
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'fn_cleanup_completed_games: gp retire failed: %', SQLERRM;
    END;

    -- (b) Delete completed rounds older than 1 hour. The completion trigger
    --     archived them already; strokes + guesses cascade via FK.
    BEGIN
        DELETE FROM public.game_invites
         WHERE "gameTable" = 'ghost_painter_rounds'
           AND "gameId" IN (
             SELECT "id" FROM public.ghost_painter_rounds
              WHERE "status" = 'completed'
                AND "endsAt" < now() - interval '1 hour'
           );
        DELETE FROM public.ghost_painter_rounds
         WHERE "status" = 'completed'
           AND "endsAt" < now() - interval '1 hour';
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'fn_cleanup_completed_games: gp delete failed: %', SQLERRM;
    END;
END;
$function$;


-- ═══ fn__game_meta: += tugofwar_games ═══

CREATE OR REPLACE FUNCTION public.fn__game_meta()
 RETURNS jsonb
 LANGUAGE sql
 IMMUTABLE
AS $function$
  SELECT jsonb_build_object(
    'sos_games',          jsonb_build_object('id','sos','name','SOS','icon','🎯','accent','#F59E0B'),
    'bingo_games',        jsonb_build_object('id','bingo','name','Bingo','icon','🎟️','accent','#06B6D4'),
    'ludo_games',         jsonb_build_object('id','ludo','name','Ludo','icon','🎲','accent','#E11D48'),
    'antakshari_games',   jsonb_build_object('id','antakshari','name','Antakshari','icon','🎤','accent','#8B5CF6'),
    'chitmatch_games',    jsonb_build_object('id','chitmatch','name','TripleMatch','icon','🃏','accent','#EC4899'),
    'checkers_games',     jsonb_build_object('id','checkers','name','Checkers','icon','🔴','accent','#6366F1'),
    'chess_games',        jsonb_build_object('id','chess','name','Chess','icon','♞','accent','#64748B'),
    'carrom_games',       jsonb_build_object('id','carrom','name','Carrom','icon','⚪','accent','#F59E0B'),
    'tictactoe_games',    jsonb_build_object('id','tictactoe','name','Tic-Tac-Toe','icon','#️⃣','accent','#8B5CF6'),
    'truthordare_games',  jsonb_build_object('id','truthordare','name','Truth or Dare','icon','🎭','accent','#EF4444'),
    'twotruths_games',    jsonb_build_object('id','twotruths','name','Two Truths & a Lie','icon','🕵️','accent','#D946EF'),
    'dotsboxes_games',    jsonb_build_object('id','dotsboxes','name','Dots & Boxes','icon','▪️','accent','#06B6D4'),
    'nameplace_games',    jsonb_build_object('id','nameplace','name','Name Place Animal Thing','icon','📖','accent','#10B981'),
    'redlight_rounds',    jsonb_build_object('id','freeze-dash','name','Freeze & Dash','icon','🏃','accent','#10B981'),
    'ghost_painter_rounds', jsonb_build_object('id','ghost-painter','name','Ghost Painter','icon','👻','accent','#EC4899'),
    'tugofwar_games',       jsonb_build_object('id','tug-of-war','name','Tug of War','icon','🪢','accent','#E8612A')
  );
$function$;


-- ═══ fn__evaluate_game_badges: += tugofwar-titan ═══

CREATE OR REPLACE FUNCTION public.fn__evaluate_game_badges(p_user_id text, p_family_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_overall   record;      -- overall stats row (gameTable='*')
  v_wins      int := 0;
  v_matches   int := 0;
  v_best      int := 0;
  v_spect     int := 0;
  v_given     int := 0;
  v_received  int := 0;
  v_variety   int := 0;
  v_week      int := 0;
  v_weekend   int := 0;
  v_social    int := 0;
  v_early     int := 0;
  v_late      int := 0;
  v_night_reg int := 0;
  v_night_win int := 0;
  v_cup_win   int := 0;
  v_earned    text[] := '{}';
  v_badge     record;
  v_new_badges jsonb := '[]'::jsonb;
  v_user_name text;
BEGIN
  SELECT * INTO v_overall FROM "game_user_stats"
  WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='*';
  IF NOT FOUND THEN RETURN '[]'::jsonb; END IF;

  v_wins := v_overall."wins"; v_matches := v_overall."matches";
  v_best := v_overall."streakBest"; v_spect := v_overall."spectated";
  v_given := v_overall."sportsmanshipGiven"; v_received := v_overall."sportsmanshipReceived";

  SELECT COUNT(DISTINCT "gameTable") INTO v_variety
  FROM "game_match_players"
  WHERE "userId"=p_user_id AND "familyId"=p_family_id;

  SELECT COUNT(*) INTO v_week
  FROM "game_match_players"
  WHERE "userId"=p_user_id AND "familyId"=p_family_id
    AND "finishedAt" >= now() - interval '7 days';

  SELECT COUNT(*) INTO v_weekend
  FROM "game_match_players"
  WHERE "userId"=p_user_id AND "familyId"=p_family_id
    AND EXTRACT(ISODOW FROM "finishedAt") IN (6,7);

  SELECT COUNT(*) INTO v_social
  FROM "game_match_players" gmp
  WHERE gmp."userId"=p_user_id AND gmp."familyId"=p_family_id
    AND (SELECT COUNT(*) FROM "game_match_players" o
         WHERE o."matchId"=gmp."matchId") >= 3;

  SELECT COUNT(*) INTO v_early
  FROM "game_match_players"
  WHERE "userId"=p_user_id AND "familyId"=p_family_id
    AND EXTRACT(HOUR FROM "finishedAt" AT TIME ZONE 'Asia/Kolkata') < 9;

  SELECT COUNT(*) INTO v_late
  FROM "game_match_players"
  WHERE "userId"=p_user_id AND "familyId"=p_family_id
    AND EXTRACT(HOUR FROM "finishedAt" AT TIME ZONE 'Asia/Kolkata') >= 22;

  -- scheduled family game night participations
  SELECT COUNT(*) INTO v_night_reg
  FROM "game_match_players" gmp
  JOIN "scheduled_game_nights" sgn
    ON sgn."familyId" = gmp."familyId"
   AND gmp."finishedAt" BETWEEN COALESCE(sgn."startedAt", sgn."scheduledFor") AND COALESCE(sgn."startedAt", sgn."scheduledFor") + interval '4 hours'
  WHERE gmp."userId"=p_user_id AND gmp."familyId"=p_family_id;

  SELECT COUNT(*) INTO v_night_win
  FROM "game_match_players" gmp
  JOIN "scheduled_game_nights" sgn
    ON sgn."familyId" = gmp."familyId"
   AND gmp."finishedAt" BETWEEN COALESCE(sgn."startedAt", sgn."scheduledFor") AND COALESCE(sgn."startedAt", sgn."scheduledFor") + interval '4 hours'
  WHERE gmp."userId"=p_user_id AND gmp."familyId"=p_family_id AND gmp."result"='win';

  SELECT COUNT(*) INTO v_cup_win
  FROM "game_season_winners"
  WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "rank"=1;

  -- ── Build the earned set ──
  IF v_wins >= 1        THEN v_earned := v_earned || ARRAY['first-game-win']; END IF;
  IF v_wins >= 5        THEN v_earned := v_earned || ARRAY['win-5-games']; END IF;
  IF v_wins >= 25       THEN v_earned := v_earned || ARRAY['win-25-games']; END IF;
  IF v_wins >= 100      THEN v_earned := v_earned || ARRAY['win-100-games']; END IF;
  IF v_wins >= 10       THEN v_earned := v_earned || ARRAY['family-champion']; END IF;
  IF v_best >= 3        THEN v_earned := v_earned || ARRAY['win-streak-3']; END IF;
  IF v_best >= 5        THEN v_earned := v_earned || ARRAY['undefeated-streak-5']; END IF;
  IF v_week >= 5        THEN v_earned := v_earned || ARRAY['played-5-games-week']; END IF;
  IF v_weekend >= 3     THEN v_earned := v_earned || ARRAY['weekend-gamer']; END IF;
  IF v_matches >= 50    THEN v_earned := v_earned || ARRAY['play-50-games']; END IF;
  IF v_matches >= 200   THEN v_earned := v_earned || ARRAY['play-200-games']; END IF;
  IF v_variety >= 8     THEN v_earned := v_earned || ARRAY['family-explorer']; END IF;
  IF v_spect >= 5       THEN v_earned := v_earned || ARRAY['spectator-supporter']; END IF;
  IF v_social >= 10     THEN v_earned := v_earned || ARRAY['social-gamer']; END IF;
  IF v_early >= 1       THEN v_earned := v_earned || ARRAY['early-bird']; END IF;
  IF v_late >= 1        THEN v_earned := v_earned || ARRAY['night-owl']; END IF;
  IF v_given >= 10      THEN v_earned := v_earned || ARRAY['cheering-champion']; END IF;
  IF v_received >= 10   THEN v_earned := v_earned || ARRAY['gracious-player']; END IF;
  IF v_night_reg >= 4   THEN v_earned := v_earned || ARRAY['family-game-night-regular']; END IF;
  IF v_night_win >= 25  THEN v_earned := v_earned || ARRAY['family-night-champion']; END IF;
  IF v_cup_win >= 1     THEN v_earned := v_earned || ARRAY['family-cup-champion']; END IF;

  -- Per-game champion badges (5 wins in that game)
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='bingo_games' AND "wins">=5) THEN v_earned := v_earned || ARRAY['bingo-master']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='sos_games' AND "wins">=5) THEN v_earned := v_earned || ARRAY['sos-strategist']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='ludo_games' AND "wins">=5) THEN v_earned := v_earned || ARRAY['ludo-champion']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='chess_games' AND "wins">=5) THEN v_earned := v_earned || ARRAY['chess-master']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='carrom_games' AND "wins">=5) THEN v_earned := v_earned || ARRAY['carrom-king']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='checkers_games' AND "wins">=5) THEN v_earned := v_earned || ARRAY['checkers-champ']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='tictactoe_games' AND "wins">=5) THEN v_earned := v_earned || ARRAY['tictactoe-tactician']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='dotsboxes_games' AND "wins">=5) THEN v_earned := v_earned || ARRAY['dots-boxer']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='nameplace_games' AND "wins">=5) THEN v_earned := v_earned || ARRAY['nameplace-scholar']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='antakshari_games' AND "wins">=5) THEN v_earned := v_earned || ARRAY['antakshari-star']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='twotruths_games' AND "wins">=5) THEN v_earned := v_earned || ARRAY['twotruths-mastermind']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='chitmatch_games' AND "wins">=5) THEN v_earned := v_earned || ARRAY['chitmatch-collector']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='redlight_rounds' AND "wins">=5) THEN v_earned := v_earned || ARRAY['freeze-dash-sprinter']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='truthordare_games' AND "matches">=10) THEN v_earned := v_earned || ARRAY['truthordare-fearless']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='ghost_painter_rounds' AND "wins">=5) THEN v_earned := v_earned || ARRAY['ghost-painter-virtuoso']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='tugofwar_games' AND "wins">=5) THEN v_earned := v_earned || ARRAY['tugofwar-titan']; END IF;

  IF v_earned = '{}' THEN RETURN '[]'::jsonb; END IF;

  SELECT COALESCE(MAX("userName"), 'Family Member') INTO v_user_name
  FROM "game_match_players" WHERE "userId" = p_user_id LIMIT 1;

  -- Insert only NEW badges; build the returned array from what was inserted
  FOR v_badge IN
    SELECT b."id", b."slug", b."name", b."icon", b."tier"
    FROM "Badge" b
    WHERE b."category" = 'games' AND b."slug" = ANY(v_earned)
      AND NOT EXISTS (
        SELECT 1 FROM "UserBadge" ub
        WHERE ub."badgeId" = b."id"
          AND ub."userId" = p_user_id
          AND COALESCE(ub."familyId", p_family_id) = p_family_id)
  LOOP
    INSERT INTO "UserBadge" ("id","userId","badgeId","familyId","earnedAt")
    VALUES (gen_random_uuid()::text, p_user_id, v_badge."id", p_family_id, now())
    ON CONFLICT DO NOTHING;

    v_new_badges := v_new_badges || jsonb_build_object(
      'slug', v_badge."slug",
      'name', v_badge."name",
      'icon', v_badge."icon",
      'tier', v_badge."tier");

    INSERT INTO "FamilyActivityLog"
      ("id","familyId","actorUserId","actorName","action","description","metadata")
    VALUES (
      gen_random_uuid()::text, p_family_id, p_user_id, v_user_name,
      'game_badge_earned',
      format('%s earned the %s badge', v_user_name, v_badge."name"),
      jsonb_build_object('badgeSlug', v_badge."slug", 'badgeName', v_badge."name",
                         'badgeIcon', v_badge."icon", 'badgeTier', v_badge."tier"));
  END LOOP;

  RETURN v_new_badges;
END;
$function$;


-- ═══ fn__archive_family_match: whitelist + winners + participant
--     fallback + team-battle result semantics += tugofwar_games ═══

CREATE OR REPLACE FUNCTION public.fn__archive_family_match(p_game_table text, p_game_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_family_id      text;
  v_status         text;
  v_created_at     timestamptz;
  v_finished_at    timestamptz;
  v_end_col        text;
  v_finished_status text;
  v_winner_col     text;
  v_winner_name_col text;
  v_winner_ids     text[] := '{}';
  v_winner_names   text[] := '{}';
  v_is_terminal    boolean := false;
  v_player_count   int := 0;
  v_meta           jsonb;
  v_result_kind    text := 'played';
  v_new_badges     jsonb := '[]'::jsonb;
  v_completed      jsonb := '[]'::jsonb;
  v_milestones     jsonb := '[]'::jsonb;
  v_badges_for_p   jsonb;
  v_chal_for_p     jsonb;
  v_participants   jsonb;
  v_p              jsonb;
  v_i              int;
  v_uid            text;
  v_uname          text;
  v_res            text;
  v_streak_before  int;
  v_duration       int;
  v_season_id      text;
  v_season_name    text;
  v_spectator      record;
  v_already        boolean;
  v_summary        jsonb;
BEGIN
  -- Whitelist game tables (security: p_game_table is used in dynamic SQL)
  IF p_game_table NOT IN (
    'antakshari_games','chitmatch_games','bingo_games','ludo_games',
    'sos_games','dotsboxes_games','nameplace_games','truthordare_games',
    'twotruths_games','redlight_rounds','chess_games','tictactoe_games',
    'checkers_games','carrom_games','ghost_painter_rounds','tugofwar_games'
  ) THEN
    RETURN NULL;
  END IF;

  -- Idempotency: already archived → no-op
  SELECT EXISTS (
    SELECT 1 FROM "game_match_history"
    WHERE "gameTable" = p_game_table AND "gameId" = p_game_id
  ) INTO v_already;
  IF v_already THEN
    RETURN NULL;
  END IF;

  v_meta := public.fn__game_meta() -> p_game_table;

  -- ── Read the game row (dynamic: column names differ per table) ──
  -- sos_games + redlight_rounds use finishedAt/'finished';
  -- ghost_painter_rounds uses endsAt/'completed'; all others completedAt/'completed'.
  IF p_game_table IN ('sos_games','redlight_rounds') THEN
    v_end_col := 'finishedAt';
    v_finished_status := 'finished';
  ELSIF p_game_table = 'ghost_painter_rounds' THEN
    v_end_col := 'endsAt';
    v_finished_status := 'completed';
  ELSE
    v_end_col := 'completedAt';
    v_finished_status := 'completed';
  END IF;

  EXECUTE format(
    'SELECT "familyId", "status", "createdAt", COALESCE(%I, now())
       FROM public.%I WHERE "id" = $1', v_end_col, p_game_table)
    INTO v_family_id, v_status, v_created_at, v_finished_at
    USING p_game_id;

  IF v_family_id IS NULL THEN
    RETURN NULL; -- game row already gone (e.g. race with cron)
  END IF;
  v_created_at := COALESCE(v_created_at, now());
  v_finished_at := COALESCE(v_finished_at, now());

  -- Terminal statuses per table (from RoomConfig presets)
  v_is_terminal := v_status IN (v_finished_status, 'ended', 'done');

  -- ── Extract winners (column name differs per table) ──
  IF p_game_table = 'truthordare_games' THEN
    v_winner_ids := '{}';  -- party game: no winners, participation only
  ELSIF p_game_table = 'ghost_painter_rounds' THEN
    -- Winner(s) = the guesser(s) who cracked the drawing
    SELECT ARRAY(SELECT g."userId" FROM "ghost_painter_guesses" g
                 WHERE g."roundId" = p_game_id AND g."isCorrect")
      INTO v_winner_ids;
  ELSIF p_game_table IN ('antakshari_games','chitmatch_games','dotsboxes_games',
                          'nameplace_games','twotruths_games','tugofwar_games') THEN
    -- winnerUserIds is a jsonb array on these tables
    EXECUTE format(
      'SELECT ARRAY(SELECT jsonb_array_elements_text(COALESCE("winnerUserIds", ''[]''::jsonb))) FROM public.%I WHERE "id" = $1',
      p_game_table)
      INTO v_winner_ids USING p_game_id;
  ELSE
    v_winner_col := CASE
      WHEN p_game_table IN ('chess_games','checkers_games','carrom_games','ludo_games') THEN 'winnerId'
      WHEN p_game_table = 'tictactoe_games' THEN 'overallWinnerId'
      WHEN p_game_table = 'bingo_games' THEN 'winnerPlayerId'
      ELSE 'winnerUserId'  -- sos_games, redlight_rounds
    END;
    EXECUTE format(
      'SELECT ARRAY[COALESCE(%I, '''')] FROM public.%I WHERE "id" = $1',
      v_winner_col, p_game_table)
      INTO v_winner_ids USING p_game_id;
  END IF;

  v_winner_ids := COALESCE(v_winner_ids, '{}');
  v_winner_ids := ARRAY(SELECT x FROM unnest(v_winner_ids) AS x WHERE x IS NOT NULL AND x <> '');

  IF array_length(v_winner_ids, 1) IS NULL THEN
    IF NOT v_is_terminal THEN
      RETURN NULL; -- abandoned / cancelled / in-progress → do not archive
    END IF;
    v_result_kind := 'played';   -- finished without winners (party game / draw)
  ELSE
    v_result_kind := 'win';
    -- Winner display names — resolved uniformly from participants
    IF p_game_table = 'ghost_painter_rounds' THEN
      SELECT ARRAY(SELECT g."userName" FROM "ghost_painter_guesses" g
                   WHERE g."roundId" = p_game_id AND g."isCorrect"
                     AND g."userId" = ANY(v_winner_ids))
        INTO v_winner_names;
    ELSE
      SELECT COALESCE(array_agg(gp."userName") FILTER (WHERE gp."userName" IS NOT NULL), '{}')
        INTO v_winner_names
      FROM "game_participants" gp
      WHERE gp."gameTable" = p_game_table
        AND gp."gameId" = p_game_id
        AND gp."userId" = ANY(v_winner_ids);
    END IF;
    IF array_length(v_winner_names, 1) IS NULL AND p_game_table <> 'ghost_painter_rounds' THEN
      -- fallback: the game row's name column (board games)
      v_winner_name_col := CASE
        WHEN p_game_table IN ('chess_games','checkers_games','carrom_games','ludo_games') THEN 'winnerName'
        WHEN p_game_table = 'tictactoe_games' THEN 'overallWinnerName'
        WHEN p_game_table = 'redlight_rounds' THEN 'winnerUserName'
        WHEN p_game_table = 'bingo_games' THEN 'winnerPlayerName'
        ELSE NULL
      END;
      IF v_winner_name_col IS NOT NULL THEN
        EXECUTE format(
          'SELECT ARRAY[COALESCE(%I, '''')] FROM public.%I WHERE "id" = $1',
          v_winner_name_col, p_game_table)
          INTO v_winner_names USING p_game_id;
      ELSE
        v_winner_names := '{}';
      END IF;
      v_winner_names := ARRAY(SELECT x FROM unnest(COALESCE(v_winner_names,'{}')) AS x WHERE x IS NOT NULL AND x <> '');
    END IF;
    v_winner_names := COALESCE(v_winner_names, '{}');
  END IF;

  -- ── Load live participants (rows still exist at this point) ──
  -- role filter includes 'host': the room host IS a player in every game
  -- (RoomController.createRoom records the host with role='host').
  SELECT COALESCE(jsonb_agg(jsonb_build_object(
      'userId', gp."userId",
      'userName', COALESCE(gp."userName",'Family Member'),
      'role', gp."role")), '[]'::jsonb)
  INTO v_participants
  FROM "game_participants" gp
  WHERE gp."gameTable" = p_game_table
    AND gp."gameId" = p_game_id
    AND gp."role" IN ('player','host');

  v_player_count := jsonb_array_length(v_participants);

  -- ── Inline-player games (Pattern A: chess / checkers / carrom / tictactoe)
  --    create rooms via their own providers (ChallengeLobbyScreen), which do
  --    NOT write game_participants. Derive participants from the game row's
  --    player columns so those matches are archived too.
  IF v_player_count = 0 AND p_game_table IN ('chess_games','checkers_games','carrom_games','tictactoe_games') THEN
    DECLARE
      v_p1_id text; v_p1_name text; v_p2_id text; v_p2_name text;
    BEGIN
      IF p_game_table = 'tictactoe_games' THEN
        EXECUTE format('SELECT "playerXId","playerXName","playerOId","playerOName" FROM public.%I WHERE "id" = $1', p_game_table)
            INTO v_p1_id, v_p1_name, v_p2_id, v_p2_name USING p_game_id;
      ELSIF p_game_table = 'chess_games' THEN
        EXECUTE format('SELECT "playerWhiteId","playerWhiteName","playerBlackId","playerBlackName" FROM public.%I WHERE "id" = $1', p_game_table)
            INTO v_p1_id, v_p1_name, v_p2_id, v_p2_name USING p_game_id;
      ELSE -- checkers + carrom
        EXECUTE format('SELECT "playerOneId","playerOneName","playerTwoId","playerTwoName" FROM public.%I WHERE "id" = $1', p_game_table)
            INTO v_p1_id, v_p1_name, v_p2_id, v_p2_name USING p_game_id;
      END IF;

      v_participants := jsonb_build_array(
        jsonb_build_object('userId', v_p1_id, 'userName', COALESCE(v_p1_name,'Player'), 'role', 'player'),
        jsonb_build_object('userId', v_p2_id, 'userName', COALESCE(v_p2_name,'Player'), 'role', 'player'));
      v_player_count := 2;
    END;
  END IF;

  -- ── Ghost Painter: participants are the drawer plus everyone who guessed ──
  IF v_player_count = 0 AND p_game_table = 'ghost_painter_rounds' THEN
    SELECT jsonb_agg(jsonb_build_object(
             'userId', x."userId",
             'userName', COALESCE(x."userName", 'Family Member'),
             'role', x."role"))
    INTO v_participants
    FROM (
      SELECT g."userId" AS "userId", g."userName" AS "userName", 'player' AS "role"
      FROM "ghost_painter_guesses" g
      WHERE g."roundId" = p_game_id
      UNION ALL
      SELECT r."drawerPersonId", r."drawerPersonName", 'host'
      FROM "ghost_painter_rounds" r
      WHERE r."id" = p_game_id
        AND r."drawerPersonId" IS NOT NULL
        AND r."drawerPersonId" NOT IN (
          SELECT g."userId" FROM "ghost_painter_guesses" g WHERE g."roundId" = p_game_id)
    ) x;
    v_player_count := jsonb_array_length(COALESCE(v_participants, '[]'::jsonb));
  END IF;

  -- ── Truth or Dare: its lobby creates rooms via the game's own provider
  --    (todProvider.createGame → truthordare_players only), NOT via the
  --    RoomController — so game_participants stays empty. Derive participants
  --    from truthordare_players so these matches archive too.
  IF v_player_count = 0 AND p_game_table = 'truthordare_games' THEN
    SELECT jsonb_agg(jsonb_build_object(
             'userId', tp."userId",
             'userName', COALESCE(tp."userName", 'Family Member'),
             'role', CASE WHEN tp."userId" = (SELECT g."hostUserId" FROM public.truthordare_games g WHERE g."id" = p_game_id) THEN 'host' ELSE 'player' END))
    INTO v_participants
    FROM public.truthordare_players tp
    WHERE tp."gameId" = p_game_id;
    v_player_count := jsonb_array_length(COALESCE(v_participants, '[]'::jsonb));
  END IF;
  IF v_player_count = 0 AND p_game_table = 'tugofwar_games' THEN
    SELECT jsonb_agg(jsonb_build_object(
             'userId', tp."userId",
             'userName', COALESCE(tp."userName", 'Family Member'),
             'role', CASE WHEN tp."userId" = (SELECT g."hostUserId" FROM public.tugofwar_games g WHERE g."id" = p_game_id) THEN 'host' ELSE 'player' END))
    INTO v_participants
    FROM public.tugofwar_players tp
    WHERE tp."gameId" = p_game_id;
    v_player_count := jsonb_array_length(COALESCE(v_participants, '[]'::jsonb));
  END IF;

  -- Ghost Painter: a round with zero guesses is an abandoned pickup round,
  -- not a family match — never archive it.
  IF p_game_table = 'ghost_painter_rounds' AND NOT EXISTS (
    SELECT 1 FROM "ghost_painter_guesses" WHERE "roundId" = p_game_id) THEN
    RETURN NULL;
  END IF;

  IF v_player_count = 0 THEN
    RETURN NULL; -- nobody recorded → nothing to archive
  END IF;

  v_duration := GREATEST(0, EXTRACT(EPOCH FROM (v_finished_at - v_created_at))::int);

  -- ── 1. Archive the match ──
  INSERT INTO "game_match_history"
    ("id","gameTable","gameId","familyId","playerCount",
     "winnerUserIds","winnerNames","resultKind","finishedAt","startedAt","durationSeconds")
  VALUES
    (p_game_id, p_game_table, p_game_id, v_family_id, v_player_count,
     v_winner_ids, v_winner_names, v_result_kind, v_finished_at, v_created_at, v_duration)
  ON CONFLICT ("gameTable","gameId") DO NOTHING;

  IF NOT EXISTS (SELECT 1 FROM "game_match_history" WHERE "gameTable"=p_game_table AND "gameId"=p_game_id) THEN
    RETURN NULL; -- concurrent call won the race
  END IF;

  -- ── 2. Per-player rows + stats + badges + challenges ──
  FOR v_i IN 0 .. (v_player_count - 1) LOOP
    v_p := v_participants -> v_i;
    v_uid := v_p ->> 'userId';
    v_uname := v_p ->> 'userName';

    -- Result derivation. Party games (Ghost Painter, Truth or Dare): the
    -- correct guesser wins (GP) or nobody wins (ToD); everyone else —
    -- including the drawer/host — is recorded as 'played', never 'loss'.
    IF v_winner_ids @> ARRAY[v_uid] THEN
      v_res := 'win';
    ELSIF array_length(v_winner_ids, 1) IS NULL THEN
      v_res := CASE WHEN p_game_table = 'tugofwar_games' THEN 'draw'
                    WHEN p_game_table IN ('ghost_painter_rounds','truthordare_games') THEN 'played'
                    WHEN v_player_count <= 2 THEN 'draw' ELSE 'played' END;
    ELSE
      v_res := CASE WHEN p_game_table = 'tugofwar_games' THEN 'loss'
                    WHEN p_game_table IN ('ghost_painter_rounds','truthordare_games') THEN 'played'
                    WHEN v_player_count <= 2 THEN 'loss' ELSE 'played' END;
    END IF;

    -- Streak snapshot BEFORE this match (for streak-based challenge checks)
    SELECT COALESCE(MAX("streakCurrent"), 0) INTO v_streak_before
    FROM "game_user_stats"
    WHERE "userId" = v_uid AND "familyId" = v_family_id AND "gameTable" = '*';

    INSERT INTO "game_match_players"
      ("matchId","gameTable","gameId","familyId","userId","userName","result","finishedAt")
    VALUES
      (p_game_id, p_game_table, p_game_id, v_family_id, v_uid, v_uname, v_res, v_finished_at)
    ON CONFLICT ("matchId","userId") DO NOTHING;

    -- game_user_stats: per-game row
    INSERT INTO "game_user_stats"
      ("userId","familyId","gameTable",
       "matches","wins","losses","draws","played","points","lastPlayedAt")
    VALUES
      (v_uid, v_family_id, p_game_table,
       1,
       CASE WHEN v_res='win' THEN 1 ELSE 0 END,
       CASE WHEN v_res='loss' THEN 1 ELSE 0 END,
       CASE WHEN v_res='draw' THEN 1 ELSE 0 END,
       CASE WHEN v_res='played' THEN 1 ELSE 0 END,
       CASE WHEN v_res='win' THEN 3 WHEN v_res IN ('draw','played') THEN 1 ELSE 0 END,
       v_finished_at)
    ON CONFLICT ("userId","familyId","gameTable") DO UPDATE SET
      "matches" = "game_user_stats"."matches" + 1,
      "wins" = "game_user_stats"."wins" + EXCLUDED."wins",
      "losses" = "game_user_stats"."losses" + EXCLUDED."losses",
      "draws" = "game_user_stats"."draws" + EXCLUDED."draws",
      "played" = "game_user_stats"."played" + EXCLUDED."played",
      "points" = "game_user_stats"."points" + EXCLUDED."points",
      "lastPlayedAt" = EXCLUDED."lastPlayedAt",
      "updatedAt" = now();

    -- game_user_stats: overall ('*') row with streak maintenance
    INSERT INTO "game_user_stats"
      ("userId","familyId","gameTable",
       "matches","wins","losses","draws","played","points",
       "streakCurrent","streakBest","lastPlayedAt")
    VALUES
      (v_uid, v_family_id, '*',
       1,
       CASE WHEN v_res='win' THEN 1 ELSE 0 END,
       CASE WHEN v_res='loss' THEN 1 ELSE 0 END,
       CASE WHEN v_res='draw' THEN 1 ELSE 0 END,
       CASE WHEN v_res='played' THEN 1 ELSE 0 END,
       CASE WHEN v_res='win' THEN 3 WHEN v_res IN ('draw','played') THEN 1 ELSE 0 END,
       CASE WHEN v_res='win' THEN 1 ELSE 0 END,
       CASE WHEN v_res='win' THEN 1 ELSE 0 END,
       v_finished_at)
    ON CONFLICT ("userId","familyId","gameTable") DO UPDATE SET
      "matches" = "game_user_stats"."matches" + 1,
      "wins" = "game_user_stats"."wins" + EXCLUDED."wins",
      "losses" = "game_user_stats"."losses" + EXCLUDED."losses",
      "draws" = "game_user_stats"."draws" + EXCLUDED."draws",
      "played" = "game_user_stats"."played" + EXCLUDED."played",
      "points" = "game_user_stats"."points" + EXCLUDED."points",
      "streakCurrent" = CASE
        WHEN EXCLUDED."wins" > 0 THEN "game_user_stats"."streakCurrent" + 1
        ELSE 0 END,
      "streakBest" = CASE
        WHEN EXCLUDED."wins" > 0 THEN GREATEST("game_user_stats"."streakBest", "game_user_stats"."streakCurrent" + 1)
        ELSE "game_user_stats"."streakBest" END,
      "lastPlayedAt" = EXCLUDED."lastPlayedAt",
      "updatedAt" = now();

    -- Badges for this player
    v_badges_for_p := public.fn__evaluate_game_badges(v_uid, v_family_id);
    IF v_badges_for_p IS NOT NULL AND jsonb_array_length(v_badges_for_p) > 0 THEN
      v_new_badges := v_new_badges || jsonb_build_object(
        'userId', v_uid, 'userName', v_uname, 'badges', v_badges_for_p);
    END IF;

    -- Challenges for this player
    v_chal_for_p := public.fn__advance_challenges(v_uid, v_family_id);
    IF v_chal_for_p IS NOT NULL AND jsonb_array_length(v_chal_for_p) > 0 THEN
      v_completed := v_completed || jsonb_build_object(
        'userId', v_uid, 'userName', v_uname, 'challenges', v_chal_for_p);
    END IF;
  END LOOP;

  -- ── 3. Spectator archive (rows still exist pre-delete) ──
  FOR v_spectator IN
    SELECT "userId", "userName" FROM "game_spectators"
    WHERE "gameTable" = p_game_table AND "gameId" = p_game_id
  LOOP
    INSERT INTO "game_user_stats"
      ("userId","familyId","gameTable","spectated")
    VALUES (v_spectator."userId", v_family_id, '*', 1)
    ON CONFLICT ("userId","familyId","gameTable") DO UPDATE SET
      "spectated" = "game_user_stats"."spectated" + 1,
      "updatedAt" = now();
  END LOOP;

  -- ── 4. Family aggregate ──
  INSERT INTO "game_family_stats" ("familyId","totalMatches","firstMatchAt","lastMatchAt")
  VALUES (v_family_id, 1, v_finished_at, v_finished_at)
  ON CONFLICT ("familyId") DO UPDATE SET
    "totalMatches" = "game_family_stats"."totalMatches" + 1,
    "lastMatchAt" = v_finished_at,
    "updatedAt" = now();

  UPDATE "game_family_stats" SET "distinctGames" = (
    SELECT COUNT(DISTINCT "gameTable") FROM "game_match_history" WHERE "familyId" = v_family_id
  ) WHERE "familyId" = v_family_id;

  -- ── 5. Activity feed: match completed ──
  INSERT INTO "FamilyActivityLog"
    ("id","familyId","actorUserId","actorName","action","description","metadata")
  VALUES (
    gen_random_uuid()::text,
    v_family_id,
    COALESCE(v_winner_ids[1], (v_participants->0->>'userId')),
    COALESCE(v_winner_names[1], (v_participants->0->>'userName'), 'Family'),
    'game_match_completed',
    CASE
      WHEN array_length(v_winner_ids,1) IS NULL
        THEN format('%s · %s players · a fun family moment', (v_meta->>'name'), v_player_count::text)
      ELSE format('%s won %s · %s players', array_to_string(v_winner_names, ' & '), (v_meta->>'name'), v_player_count)
    END,
    jsonb_build_object(
      'gameTable', p_game_table,
      'gameId', p_game_id,
      'gameName', v_meta->>'name',
      'gameIcon', v_meta->>'icon',
      'winners', to_jsonb(v_winner_names),
      'playerCount', v_player_count,
      'durationSeconds', v_duration
    )
  );

  -- ── 6. Season / Family Cup standings ──
  IF v_finished_at >= date_trunc('month', now()) THEN
    PERFORM public.fn_get_current_season(NULL);
  END IF;

  SELECT "id","name" INTO v_season_id, v_season_name
  FROM "game_seasons"
  WHERE v_finished_at >= "startsAt" AND v_finished_at < "endsAt"
  LIMIT 1;

  IF v_season_id IS NOT NULL THEN
    FOR v_i IN 0 .. (v_player_count - 1) LOOP
      v_p := v_participants -> v_i;
      v_uid := v_p ->> 'userId';
      IF v_winner_ids @> ARRAY[v_uid] THEN v_res := 'win';
      ELSIF array_length(v_winner_ids,1) IS NULL THEN v_res := CASE WHEN p_game_table = 'tugofwar_games' THEN 'draw' WHEN p_game_table IN ('ghost_painter_rounds','truthordare_games') THEN 'played' WHEN v_player_count <= 2 THEN 'draw' ELSE 'played' END;
      ELSE v_res := CASE WHEN p_game_table = 'tugofwar_games' THEN 'loss' WHEN p_game_table IN ('ghost_painter_rounds','truthordare_games') THEN 'played' WHEN v_player_count <= 2 THEN 'loss' ELSE 'played' END;
      END IF;
      INSERT INTO "game_season_standings"
        ("seasonId","familyId","userId","points","wins","gamesPlayed")
      VALUES
        (v_season_id, v_family_id, v_uid,
         CASE WHEN v_res='win' THEN 3 WHEN v_res IN ('draw','played') THEN 1 ELSE 0 END,
         CASE WHEN v_res='win' THEN 1 ELSE 0 END, 1)
      ON CONFLICT ("seasonId","familyId","userId") DO UPDATE SET
        "points" = "game_season_standings"."points" + EXCLUDED."points",
        "wins" = "game_season_standings"."wins" + EXCLUDED."wins",
        "gamesPlayed" = "game_season_standings"."gamesPlayed" + 1,
        "updatedAt" = now();
    END LOOP;
  END IF;

  -- ── 7. Family milestones ──
  v_milestones := public.fn__check_family_milestones(v_family_id);

  -- ── 8. Persist the rewards payload on the archive so EVERY player's
  --       results screen can celebrate (not just the archiving caller) ──
  v_summary := jsonb_build_object(
    'matchId', p_game_id,
    'gameTable', p_game_table,
    'gameName', v_meta->>'name',
    'gameIcon', v_meta->>'icon',
    'familyId', v_family_id,
    'winners', to_jsonb(v_winner_names),
    'playerCount', v_player_count,
    'durationSeconds', v_duration,
    'newBadges', v_new_badges,
    'completedChallenges', v_completed,
    'milestones', v_milestones,
    'players', COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
        'userId', p."userId", 'userName', p."userName", 'result', p."result"))
      FROM "game_match_players" p WHERE p."matchId" = p_game_id
    ), '[]'::jsonb)
  );

  UPDATE "game_match_history"
    SET "rewardsJson" = v_summary
    WHERE "gameTable" = p_game_table AND "gameId" = p_game_id;

  RETURN v_summary;
END;
$function$;

