-- 20260920180000_code_clues_game.sql
-- Code Clues — Codenames-style word association game. 4–8 players (2 teams).
--
-- Two teams: each has a Spymaster who gives one-word clues + a number,
-- and field agents who guess words on a 5x5 grid. First team to find
-- all their agents wins. Avoid the assassin word!
--
-- Architecture reuses the hidden-submission pattern: the grid (which
-- words belong to which team) is generated by the host and stored in
-- boardState. Spymasters see the full grid; field agents see only the
-- words. Guesses are submitted via RPC and resolved server-side.

CREATE TABLE IF NOT EXISTS "code_clues_games" (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  "familyId" TEXT NOT NULL,
  "hostUserId" TEXT NOT NULL,
  "hostUserName" TEXT NOT NULL DEFAULT 'Host',
  "roomName" TEXT,
  status TEXT NOT NULL DEFAULT 'waiting',
  "maxPlayers" INTEGER NOT NULL DEFAULT 8,
  "playerOrder" JSONB NOT NULL DEFAULT '[]'::jsonb,
  "currentTurnTeam" INTEGER NOT NULL DEFAULT 1,
  "turnEndsAt" TIMESTAMPTZ,
  "boardState" JSONB,
  "winnerUserIds" JSONB NOT NULL DEFAULT '[]'::jsonb,
  "winningTeam" INTEGER,
  "endReason" TEXT,
  "startedAt" TIMESTAMPTZ,
  "completedAt" TIMESTAMPTZ,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "autoCloseDeadline" TIMESTAMPTZ,
  "cancelledAt" TIMESTAMPTZ,
  "closedAt" TIMESTAMPTZ,
  "hostReady" BOOLEAN DEFAULT true,
  "spectatorsEnabled" BOOLEAN NOT NULL DEFAULT true,
  "lastActivityAt" TIMESTAMPTZ DEFAULT now(),
  "clueSeconds" INTEGER NOT NULL DEFAULT 60,
  "guessSeconds" INTEGER NOT NULL DEFAULT 90
);
CREATE INDEX IF NOT EXISTS idx_ccg_family ON "code_clues_games" ("familyId", "createdAt" DESC);

CREATE TABLE IF NOT EXISTS "code_clues_players" (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  "gameId" TEXT NOT NULL REFERENCES "code_clues_games"(id) ON DELETE CASCADE,
  "userId" TEXT NOT NULL,
  "userName" TEXT NOT NULL,
  "team" INTEGER NOT NULL DEFAULT 1,
  "isSpymaster" BOOLEAN NOT NULL DEFAULT false,
  "isReady" BOOLEAN NOT NULL DEFAULT false,
  "joinedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "lastActivityAt" TIMESTAMPTZ DEFAULT now(),
  "leftAt" TIMESTAMPTZ,
  UNIQUE ("gameId", "userId")
);
CREATE INDEX IF NOT EXISTS idx_ccp_game ON "code_clues_players" ("gameId", "joinedAt");

CREATE TABLE IF NOT EXISTS "code_clues_words" (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  word TEXT NOT NULL UNIQUE,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ccw_word ON "code_clues_words" (word);

ALTER TABLE "code_clues_games" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "code_clues_games_select_family" ON "code_clues_games" FOR SELECT TO authenticated USING (public.fn_user_is_family_member("familyId"));
CREATE POLICY "code_clues_games_insert_host" ON "code_clues_games" FOR INSERT TO authenticated WITH CHECK ("hostUserId" = auth.uid()::text AND public.fn_user_is_family_member("familyId"));
CREATE POLICY "code_clues_games_update_family" ON "code_clues_games" FOR UPDATE TO authenticated USING (public.fn_user_is_family_member("familyId"));

ALTER TABLE "code_clues_players" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "code_clues_players_select_family" ON "code_clues_players" FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM "code_clues_games" g WHERE g.id = "code_clues_players"."gameId" AND public.fn_user_is_family_member(g."familyId")));
CREATE POLICY "code_clues_players_insert_self_or_host" ON "code_clues_players" FOR INSERT TO authenticated WITH CHECK ("userId" = auth.uid()::text OR EXISTS (SELECT 1 FROM "code_clues_games" g WHERE g.id = "code_clues_players"."gameId" AND g."hostUserId" = auth.uid()::text));
CREATE POLICY "code_clues_players_update_self" ON "code_clues_players" FOR UPDATE TO authenticated USING ("userId" = auth.uid()::text);
CREATE POLICY "code_clues_players_delete_self" ON "code_clues_players" FOR DELETE TO authenticated USING ("userId" = auth.uid()::text);

ALTER TABLE "code_clues_words" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "code_clues_words_select_all" ON "code_clues_words" FOR SELECT TO authenticated USING (true);

ALTER PUBLICATION supabase_realtime ADD TABLE "code_clues_games";
ALTER PUBLICATION supabase_realtime ADD TABLE "code_clues_players";
ALTER TABLE "code_clues_games" REPLICA IDENTITY FULL;
ALTER TABLE "code_clues_players" REPLICA IDENTITY FULL;

-- fn_codeclues_start
CREATE OR REPLACE FUNCTION public.fn_codeclues_start(p_game_id text) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_game record; v_players jsonb; v_count int; v_order text[]; v_i int;
  v_board jsonb; v_players_arr jsonb; v_words text[]; v_word record;
  v_assignments int[]; v_j int; v_temp int;
BEGIN
  SELECT * INTO v_game FROM "code_clues_games" WHERE id = p_game_id;
  IF NOT FOUND THEN RETURN jsonb_build_object('ok', false, 'reason', 'not_found'); END IF;
  IF v_game."hostUserId" <> auth.uid()::text THEN RETURN jsonb_build_object('ok', false, 'reason', 'not_host'); END IF;
  IF v_game.status <> 'waiting' THEN RETURN jsonb_build_object('ok', false, 'reason', 'already_started'); END IF;
  SELECT COALESCE(jsonb_agg(jsonb_build_object('userId', p."userId", 'userName', p."userName", 'team', p."team", 'isSpymaster', p."isSpymaster") ORDER BY p."joinedAt"), '[]'::jsonb) INTO v_players
  FROM "code_clues_players" p WHERE p."gameId" = p_game_id AND p."leftAt" IS NULL;
  v_count := jsonb_array_length(v_players);
  IF v_count < 4 THEN RETURN jsonb_build_object('ok', false, 'reason', 'not_enough_players'); END IF;
  FOR v_i IN 0..v_count - 1 LOOP v_order := array_append(v_order, v_players->v_i->>'userId'); END LOOP;
  -- Pick 25 random words
  v_words := ARRAY[]::text[];
  FOR v_word IN SELECT word FROM code_clues_words ORDER BY random() LIMIT 25 LOOP
    v_words := array_append(v_words, v_word.word);
  END LOOP;
  IF array_length(v_words, 1) < 25 THEN RETURN jsonb_build_object('ok', false, 'reason', 'not_enough_words'); END IF;
  -- Assign: 9 team1, 8 team2, 7 neutral, 1 assassin (shuffled)
  v_assignments := ARRAY[1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,0,0,0,0,0,0,0,-1];
  -- Fisher-Yates shuffle
  FOR v_i IN REVERSE 24..1 LOOP
    v_j := floor(random() * (v_i + 1))::int;
    v_temp := v_assignments[v_i + 1]; v_assignments[v_i + 1] := v_assignments[v_j + 1]; v_assignments[v_j + 1] := v_temp;
  END LOOP;
  -- Build grid
  v_board := jsonb_build_object(
    'playerCount', v_count,
    'clueSeconds', v_game."clueSeconds",
    'guessSeconds', v_game."guessSeconds",
    'currentTurnTeam', 1,
    'phase', 'clueing',
    'words', to_jsonb(v_words),
    'assignments', to_jsonb(v_assignments),
    'revealed', jsonb_build_array(false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false),
    'clue', null,
    'clueNumber', null,
    'clueGiverId', null,
    'clueGiverName', null,
    'guessesLeft', 0,
    'team1Found', 0, 'team2Found', 0,
    'team1Total', 9, 'team2Total', 8,
    'log', '[]'::jsonb,
    'status', 'in_progress',
    'winner', -1
  );
  v_players_arr := '[]'::jsonb;
  FOR v_i IN 0..v_count - 1 LOOP
    v_players_arr := v_players_arr || jsonb_build_object(
      'idx', v_i, 'userId', v_players->v_i->>'userId',
      'name', v_players->v_i->>'userName',
      'team', (v_players->v_i->>'team')::int,
      'isSpymaster', (v_players->v_i->>'isSpymaster')::boolean,
      'score', 0
    );
  END LOOP;
  v_board := jsonb_set(v_board, '{players}', v_players_arr);
  UPDATE "code_clues_games" SET status = 'in_progress', "playerOrder" = to_jsonb(v_order),
    "boardState" = v_board, "startedAt" = now(),
    "turnEndsAt" = now() + (v_game."clueSeconds" || ' seconds')::interval,
    "lastActivityAt" = now() WHERE id = p_game_id;
  RETURN jsonb_build_object('ok', true);
END;
$$;
GRANT EXECUTE ON FUNCTION public.fn_codeclues_start(text) TO authenticated;

-- fn_codeclues_give_clue
CREATE OR REPLACE FUNCTION public.fn_codeclues_give_clue(p_game_id text, p_clue text, p_number int) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_game record; v_board jsonb; v_team int; v_spymaster record;
BEGIN
  SELECT * INTO v_game FROM "code_clues_games" WHERE id = p_game_id;
  IF NOT FOUND OR v_game.status <> 'in_progress' THEN RETURN jsonb_build_object('ok', false, 'reason', 'not_in_progress'); END IF;
  v_board := v_game."boardState";
  IF v_board->>'phase' <> 'clueing' THEN RETURN jsonb_build_object('ok', false, 'reason', 'not_clueing_phase'); END IF;
  v_team := (v_board->>'currentTurnTeam')::int;
  SELECT * INTO v_spymaster FROM "code_clues_players" WHERE "gameId" = p_game_id AND "userId" = auth.uid()::text AND "leftAt" IS NULL;
  IF v_spymaster."userId" IS NULL THEN RETURN jsonb_build_object('ok', false, 'reason', 'not_in_game'); END IF;
  IF v_spymaster."team" <> v_team OR NOT v_spymaster."isSpymaster" THEN RETURN jsonb_build_object('ok', false, 'reason', 'not_your_turn'); END IF;
  IF btrim(p_clue) = '' THEN RETURN jsonb_build_object('ok', false, 'reason', 'empty_clue'); END IF;
  IF p_number < 0 OR p_number > 9 THEN RETURN jsonb_build_object('ok', false, 'reason', 'invalid_number'); END IF;
  v_board := jsonb_set(v_board, '{clue}', to_jsonb(btrim(p_clue)));
  v_board := jsonb_set(v_board, '{clueNumber}', p_number::text::jsonb);
  v_board := jsonb_set(v_board, '{clueGiverId}', to_jsonb(auth.uid()::text));
  v_board := jsonb_set(v_board, '{clueGiverName}', to_jsonb(v_spymaster."userName"));
  v_board := jsonb_set(v_board, '{phase}', '"guessing"');
  v_board := jsonb_set(v_board, '{guessesLeft}', CASE WHEN p_number = 0 THEN '1' ELSE (p_number + 1)::text END::jsonb);
  v_board := jsonb_set(v_board, '{log}', (v_board->'log') || jsonb_build_object('type','clue','team',v_team,'clue',btrim(p_clue),'number',p_number,'user',v_spymaster."userName")));
  UPDATE "code_clues_games" SET "boardState" = v_board,
    "turnEndsAt" = now() + ((v_board->>'guessSeconds') || ' seconds')::interval,
    "lastActivityAt" = now() WHERE id = p_game_id;
  RETURN jsonb_build_object('ok', true);
END;
$$;
GRANT EXECUTE ON FUNCTION public.fn_codeclues_give_clue(text, text, int) TO authenticated;

-- fn_codeclues_guess
CREATE OR REPLACE FUNCTION public.fn_codeclues_guess(p_game_id text, p_word_index int) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_game record; v_board jsonb; v_team int; v_player record;
  v_assignment int; v_revealed jsonb; v_log jsonb;
  v_team1_found int; v_team2_found int; v_guesses_left int;
  v_game_over boolean := false; v_winning_team int;
BEGIN
  SELECT * INTO v_game FROM "code_clues_games" WHERE id = p_game_id;
  IF NOT FOUND OR v_game.status <> 'in_progress' THEN RETURN jsonb_build_object('ok', false, 'reason', 'not_in_progress'); END IF;
  v_board := v_game."boardState";
  IF v_board->>'phase' <> 'guessing' THEN RETURN jsonb_build_object('ok', false, 'reason', 'not_guessing_phase'); END IF;
  v_team := (v_board->>'currentTurnTeam')::int;
  SELECT * INTO v_player FROM "code_clues_players" WHERE "gameId" = p_game_id AND "userId" = auth.uid()::text AND "leftAt" IS NULL;
  IF v_player."userId" IS NULL THEN RETURN jsonb_build_object('ok', false, 'reason', 'not_in_game'); END IF;
  IF v_player."team" <> v_team THEN RETURN jsonb_build_object('ok', false, 'reason', 'not_your_turn'); END IF;
  IF v_player."isSpymaster" THEN RETURN jsonb_build_object('ok', false, 'reason', 'spymaster_cannot_guess'); END IF;
  IF p_word_index < 0 OR p_word_index > 24 THEN RETURN jsonb_build_object('ok', false, 'reason', 'invalid_index'); END IF;
  v_revealed := v_board->'revealed';
  IF (v_revealed->p_word_index)::boolean THEN RETURN jsonb_build_object('ok', false, 'reason', 'already_revealed'); END IF;

  v_assignment := (v_board->'assignments'->p_word_index)::int;
  v_revealed := jsonb_set(v_revealed, ARRAY[p_word_index::text], 'true');
  v_board := jsonb_set(v_board, '{revealed}', v_revealed);

  v_team1_found := (v_board->>'team1Found')::int;
  v_team2_found := (v_board->>'team2Found')::int;
  v_guesses_left := (v_board->>'guessesLeft')::int;

  v_log := v_board->'log' || jsonb_build_object('type','guess','team',v_team,'wordIndex',p_word_index,'word',v_board->'words'->p_word_index,'assignment',v_assignment,'user',v_player."userName"));
  v_board := jsonb_set(v_board, '{log}', v_log);

  IF v_assignment = -1 THEN
    -- Assassin! Other team wins
    v_game_over := true; v_winning_team := CASE WHEN v_team = 1 THEN 2 ELSE 1 END;
    v_log := v_log || jsonb_build_object('type','assassin','team',v_team);
    v_board := jsonb_set(v_board, '{log}', v_log);
  ELSIF v_assignment = v_team THEN
    -- Correct guess
    IF v_team = 1 THEN v_team1_found := v_team1_found + 1; ELSE v_team2_found := v_team2_found + 1; END IF;
    v_guesses_left := v_guesses_left - 1;
    IF v_team1_found >= 9 THEN v_game_over := true; v_winning_team := 1;
    ELSIF v_team2_found >= 8 THEN v_game_over := true; v_winning_team := 2; END IF;
  ELSIF v_assignment = 0 THEN
    -- Neutral — turn ends
    v_guesses_left := 0;
  ELSE
    -- Opponent's word — turn ends, and they get a free point
    IF v_assignment = 1 THEN v_team1_found := v_team1_found + 1; IF v_team1_found >= 9 THEN v_game_over := true; v_winning_team := 1; END IF;
    ELSIF v_assignment = 2 THEN v_team2_found := v_team2_found + 1; IF v_team2_found >= 8 THEN v_game_over := true; v_winning_team := 2; END IF; END IF;
    v_guesses_left := 0;
  END IF;

  v_board := jsonb_set(v_board, '{team1Found}', v_team1_found::text::jsonb);
  v_board := jsonb_set(v_board, '{team2Found}', v_team2_found::text::jsonb);
  v_board := jsonb_set(v_board, '{guessesLeft}', v_guesses_left::text::jsonb);

  IF v_game_over THEN
    v_board := jsonb_set(v_board, '{phase}', '"finished"');
    v_board := jsonb_set(v_board, '{status}', '"completed"');
    v_board := jsonb_set(v_board, '{winner}', v_winning_team::text::jsonb);
    UPDATE "code_clues_games" SET "boardState" = v_board, status = 'completed', "completedAt" = now(),
      "winningTeam" = v_winning_team,
      "winnerUserIds" = COALESCE((SELECT jsonb_agg("userId") FROM "code_clues_players" WHERE "gameId" = p_game_id AND "team" = v_winning_team AND "leftAt" IS NULL), '[]'::jsonb),
      "endReason" = CASE WHEN v_assignment = -1 THEN 'assassin' ELSE 'all_found' END,
      "lastActivityAt" = now() WHERE id = p_game_id;
    RETURN jsonb_build_object('ok', true, 'gameOver', true, 'winningTeam', v_winning_team);
  ELSIF v_guesses_left <= 0 THEN
    -- Turn passes to other team
    v_board := jsonb_set(v_board, '{phase}', '"clueing"');
    v_board := jsonb_set(v_board, '{currentTurnTeam}', CASE WHEN v_team = 1 THEN '2' ELSE '1' END::jsonb);
    v_board := jsonb_set(v_board, '{clue}', 'null');
    v_board := jsonb_set(v_board, '{clueNumber}', 'null');
    v_board := jsonb_set(v_board, '{clueGiverId}', 'null');
    v_board := jsonb_set(v_board, '{clueGiverName}', 'null');
    UPDATE "code_clues_games" SET "boardState" = v_board,
      "turnEndsAt" = now() + ((v_board->>'clueSeconds') || ' seconds')::interval,
      "currentTurnTeam" = CASE WHEN v_team = 1 THEN 2 ELSE 1 END,
      "lastActivityAt" = now() WHERE id = p_game_id;
    RETURN jsonb_build_object('ok', true, 'turnEnd', true);
  ELSE
    UPDATE "code_clues_games" SET "boardState" = v_board, "lastActivityAt" = now() WHERE id = p_game_id;
    RETURN jsonb_build_object('ok', true, 'assignment', v_assignment);
  END IF;
END;
$$;
GRANT EXECUTE ON FUNCTION public.fn_codeclues_guess(text, int) TO authenticated;

-- fn_codeclues_pass — end turn early (give up remaining guesses)
CREATE OR REPLACE FUNCTION public.fn_codeclues_pass(p_game_id text) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_game record; v_board jsonb; v_team int; v_player record;
BEGIN
  SELECT * INTO v_game FROM "code_clues_games" WHERE id = p_game_id;
  IF NOT FOUND OR v_game.status <> 'in_progress' THEN RETURN jsonb_build_object('ok', false, 'reason', 'not_in_progress'); END IF;
  v_board := v_game."boardState";
  IF v_board->>'phase' <> 'guessing' THEN RETURN jsonb_build_object('ok', false, 'reason', 'not_guessing_phase'); END IF;
  v_team := (v_board->>'currentTurnTeam')::int;
  SELECT * INTO v_player FROM "code_clues_players" WHERE "gameId" = p_game_id AND "userId" = auth.uid()::text AND "leftAt" IS NULL;
  IF v_player."userId" IS NULL THEN RETURN jsonb_build_object('ok', false, 'reason', 'not_in_game'); END IF;
  IF v_player."team" <> v_team THEN RETURN jsonb_build_object('ok', false, 'reason', 'not_your_turn'); END IF;
  v_board := jsonb_set(v_board, '{phase}', '"clueing"');
  v_board := jsonb_set(v_board, '{currentTurnTeam}', CASE WHEN v_team = 1 THEN '2' ELSE '1' END::jsonb);
  v_board := jsonb_set(v_board, '{clue}', 'null');
  v_board := jsonb_set(v_board, '{clueNumber}', 'null');
  v_board := jsonb_set(v_board, '{clueGiverId}', 'null');
  v_board := jsonb_set(v_board, '{clueGiverName}', 'null');
  v_board := jsonb_set(v_board, '{guessesLeft}', '0');
  v_board := jsonb_set(v_board, '{log}', (v_board->'log') || jsonb_build_object('type','pass','team',v_team)));
  UPDATE "code_clues_games" SET "boardState" = v_board,
    "turnEndsAt" = now() + ((v_board->>'clueSeconds') || ' seconds')::interval,
    "currentTurnTeam" = CASE WHEN v_team = 1 THEN 2 ELSE 1 END,
    "lastActivityAt" = now() WHERE id = p_game_id;
  RETURN jsonb_build_object('ok', true);
END;
$$;
GRANT EXECUTE ON FUNCTION public.fn_codeclues_pass(text) TO authenticated;

-- fn_codeclues_tick
CREATE OR REPLACE FUNCTION public.fn_codeclues_tick(p_game_id text) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_game record; v_board jsonb; v_team int;
BEGIN
  SELECT * INTO v_game FROM "code_clues_games" WHERE id = p_game_id;
  IF NOT FOUND OR v_game.status <> 'in_progress' THEN RETURN; END IF;
  UPDATE "code_clues_players" SET "lastActivityAt" = now() WHERE "gameId" = p_game_id AND "userId" = auth.uid()::text;
  IF v_game."turnEndsAt" IS NOT NULL AND v_game."turnEndsAt" < now() THEN
    v_board := v_game."boardState";
    IF v_board->>'phase' = 'clueing' THEN
      -- Spymaster didn't give clue in time — turn passes
      v_team := (v_board->>'currentTurnTeam')::int;
      v_board := jsonb_set(v_board, '{phase}', '"clueing"');
      v_board := jsonb_set(v_board, '{currentTurnTeam}', CASE WHEN v_team = 1 THEN '2' ELSE '1' END::jsonb);
      v_board := jsonb_set(v_board, '{log}', (v_board->'log') || jsonb_build_object('type','timeout','team',v_team,'phase','clueing')));
      UPDATE "code_clues_games" SET "boardState" = v_board,
        "turnEndsAt" = now() + ((v_board->>'clueSeconds') || ' seconds')::interval,
        "currentTurnTeam" = CASE WHEN v_team = 1 THEN 2 ELSE 1 END,
        "lastActivityAt" = now() WHERE id = p_game_id;
    ELSIF v_board->>'phase' = 'guessing' THEN
      -- Field agents didn't guess in time — turn passes
      v_team := (v_board->>'currentTurnTeam')::int;
      v_board := jsonb_set(v_board, '{phase}', '"clueing"');
      v_board := jsonb_set(v_board, '{currentTurnTeam}', CASE WHEN v_team = 1 THEN '2' ELSE '1' END::jsonb);
      v_board := jsonb_set(v_board, '{clue}', 'null');
      v_board := jsonb_set(v_board, '{clueNumber}', 'null');
      v_board := jsonb_set(v_board, '{clueGiverId}', 'null');
      v_board := jsonb_set(v_board, '{clueGiverName}', 'null');
      v_board := jsonb_set(v_board, '{guessesLeft}', '0');
      v_board := jsonb_set(v_board, '{log}', (v_board->'log') || jsonb_build_object('type','timeout','team',v_team,'phase','guessing')));
      UPDATE "code_clues_games" SET "boardState" = v_board,
        "turnEndsAt" = now() + ((v_board->>'clueSeconds') || ' seconds')::interval,
        "currentTurnTeam" = CASE WHEN v_team = 1 THEN 2 ELSE 1 END,
        "lastActivityAt" = now() WHERE id = p_game_id;
    END IF;
  END IF;
END;
$$;
GRANT EXECUTE ON FUNCTION public.fn_codeclues_tick(text) TO authenticated;

-- fn_codeclues_leave
CREATE OR REPLACE FUNCTION public.fn_codeclues_leave(p_game_id text) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_game record; v_active int;
BEGIN
  SELECT * INTO v_game FROM "code_clues_games" WHERE id = p_game_id;
  IF NOT FOUND THEN RETURN; END IF;
  UPDATE "code_clues_players" SET "leftAt" = now() WHERE "gameId" = p_game_id AND "userId" = auth.uid()::text;
  SELECT count(*) INTO v_active FROM "code_clues_players" WHERE "gameId" = p_game_id AND "leftAt" IS NULL;
  IF v_active < 4 AND v_game.status = 'in_progress' THEN
    UPDATE "code_clues_games" SET status = 'completed', "completedAt" = now(), "endReason" = 'walkover',
      "winnerUserIds" = COALESCE((SELECT jsonb_agg("userId") FROM "code_clues_players" WHERE "gameId" = p_game_id AND "leftAt" IS NULL), '[]'::jsonb),
      "lastActivityAt" = now() WHERE id = p_game_id;
  END IF;
END;
$$;
GRANT EXECUTE ON FUNCTION public.fn_codeclues_leave(text) TO authenticated;

-- Archive trigger
CREATE OR REPLACE FUNCTION public.fn__codeclues_on_complete() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF NEW."status" = 'completed' AND COALESCE(OLD."status", '') <> 'completed' THEN
    BEGIN PERFORM public.fn__archive_family_match('code_clues_games', NEW."id"); EXCEPTION WHEN OTHERS THEN RAISE NOTICE 'codeclues archive failed: %', SQLERRM; END;
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_codeclues_archive ON "code_clues_games";
CREATE TRIGGER trg_codeclues_archive AFTER UPDATE ON "code_clues_games"
  FOR EACH ROW EXECUTE FUNCTION public.fn__codeclues_on_complete();

CREATE OR REPLACE FUNCTION public.fn_touch_game_activity(p_game_table text, p_game_id text) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF p_game_table NOT IN (
    'antakshari_games','chitmatch_games','bingo_games','ludo_games','sos_games',
    'dotsboxes_games','nameplace_games','truthordare_games','twotruths_games',
    'redlight_rounds','chess_games','tictactoe_games','checkers_games','carrom_games',
    'tugofwar_games','memorymatch_games','ashta_chamma_games','ghost_painter_rounds',
    'connect4_games','impostor_games','color_trap_games','freeze_auction_games',
    'flick_arena_games','secret_heist_games','mind_match_games','code_clues_games'
  ) THEN RAISE EXCEPTION 'Unknown game table: %', p_game_table; END IF;
  EXECUTE format('UPDATE public.%I SET "lastActivityAt" = now() WHERE "id" = $1;', p_game_table) USING p_game_id;
END;
$$;
GRANT EXECUTE ON FUNCTION public.fn_touch_game_activity(text, text) TO authenticated;

CREATE OR REPLACE FUNCTION public.fn__game_meta() RETURNS jsonb
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT jsonb_build_object(
    'tictactoe_games', jsonb_build_object('id','tictactoe','name','Tic-Tac-Toe','icon','#️⃣','accent','#8B5CF6'),
    'chess_games', jsonb_build_object('id','chess','name','Chess','icon','♟️','accent','#64748B'),
    'checkers_games', jsonb_build_object('id','checkers','name','Checkers','icon','🔴','accent','#6366F1'),
    'carrom_games', jsonb_build_object('id','carrom','name','Carrom','icon','⚪','accent','#F59E0B'),
    'ludo_games', jsonb_build_object('id','ludo','name','Ludo','icon','🎲','accent','#E11D48'),
    'bingo_games', jsonb_build_object('id','bingo','name','Bingo','icon','🎰','accent','#06B6D4'),
    'dotsboxes_games', jsonb_build_object('id','dotsboxes','name','Dots and Boxes','icon','📐','accent','#06B6D4'),
    'truthordare_games', jsonb_build_object('id','truthordare','name','Truth or Dare','icon','🎲','accent','#EF4444'),
    'twotruths_games', jsonb_build_object('id','twotruths','name','Two Truths and a Lie','icon','🤥','accent','#D946EF'),
    'chitmatch_games', jsonb_build_object('id','chitmatch','name','TripleMatch','icon','🎫','accent','#EC4899'),
    'redlight_rounds', jsonb_build_object('id','freeze-dash','name','Freeze & Dash','icon','🚦','accent','#10B981'),
    'ghost_painter_rounds', jsonb_build_object('id','ghost-painter','name','Ghost Painter','icon','👻','accent','#EC4899'),
    'antakshari_games', jsonb_build_object('id','antakshari','name','Antakshari','icon','🎵','accent','#8B5CF6'),
    'nameplace_games', jsonb_build_object('id','nameplace','name','Name, Place, Animal, Thing','icon','📝','accent','#10B981'),
    'sos_games', jsonb_build_object('id','sos','name','SOS','icon','🔤','accent','#F59E0B'),
    'tugofwar_games', jsonb_build_object('id','tug-of-war','name','Tug of War','icon','💪','accent','#E8612A'),
    'memorymatch_games', jsonb_build_object('id','memory-match','name','Memory Match','icon','🧠','accent','#A855F7'),
    'ashta_chamma_games', jsonb_build_object('id','ashta-chamma','name','Ashta Chamma','icon','🐚','accent','#E11D48'),
    'connect4_games', jsonb_build_object('id','connect4','name','Connect 4','icon','🔴','accent','#0EA5E9'),
    'impostor_games', jsonb_build_object('id','impostor','name','Who''s the Impostor?','icon','🕵️','accent','#8B5CF6'),
    'color_trap_games', jsonb_build_object('id','color-trap','name','Color Trap','icon','🎨','accent','#F59E0B'),
    'freeze_auction_games', jsonb_build_object('id','freeze-auction','name','Freeze Auction','icon','📦','accent','#F59E0B'),
    'flick_arena_games', jsonb_build_object('id','flick-arena','name','Flick Arena','icon','🎯','accent','#22D3EE'),
    'secret_heist_games', jsonb_build_object('id','secret-heist','name','Secret Heist','icon','💰','accent','#10B981'),
    'mind_match_games', jsonb_build_object('id','mind-match','name','Mind Match','icon','🧠','accent','#F472B6'),
    'code_clues_games', jsonb_build_object('id','code-clues','name','Code Clues','icon','🔐','accent','#F59E0B')
  );
$$;

INSERT INTO "Badge" ("id","slug","name","nameHi","description","icon","category","tier","threshold","isSecret","createdAt") VALUES
  (gen_random_uuid()::text,'codebreaker','Codebreaker','कोडब्रेकर','Win 5 Code Clues games','🔐','games','gold',5,false,now())
ON CONFLICT ("slug") DO NOTHING;

-- Seed word pool (100 words)
INSERT INTO "code_clues_words" (word) VALUES
('Apple'),('Bread'),('Clock'),('Dance'),('Eagle'),('Fire'),('Gold'),('Heart'),('Iron'),('Jazz'),
('King'),('Lemon'),('Moon'),('Night'),('Ocean'),('Piano'),('Queen'),('River'),('Star'),('Tiger'),
('Tree'),('Umbrella'),('Voice'),('Water'),('Yellow'),('Zone'),('Angel'),('Bee'),('Castle'),('Dream'),
('Eye'),('Forest'),('Ghost'),('Hand'),('Ice'),('Joker'),('Knight'),('Light'),('Mountain'),('Needle'),
('Opera'),('Penguin'),('Quill'),('Rose'),('Shadow'),('Tower'),('Unicorn'),('Volcano'),('Wind'),('Zero'),
('Berry'),('Crown'),('Dragon'),('Engine'),('Feather'),('Garden'),('Helmet'),('India'),('Jewel'),('Kite'),
('Ladder'),('Mango'),('Net'),('Orange'),('Pilot'),('Rabbit'),('Snake'),('Train'),('Village'),('Whale'),
('Arrow'),('Bridge'),('Cloud'),('Desert'),('Egg'),('Finger'),('Glass'),('Hat'),('Igloo'),('Juice'),
('Key'),('Lamp'),('Mirror'),('Nest'),('Paint'),('Queen'),('Ring'),('Ship'),('Tent'),('Wolf'),
('Book'),('Chair'),('Door'),('Earth'),('Flag'),('Gun'),('Horse'),('Ink'),('Jam'),('King'),
('Leaf'),('Milk'),('Nose'),('Pen'),('Rope'),('Salt'),('Toy'),('Wall'),('Box'),('Cup')
ON CONFLICT (word) DO NOTHING;
