-- Migration: 20260917100000_memorymatch_game.sql
-- Generated by scripts/memorymatch/build_migration.py (anchors verified
-- against the LIVE function definitions).

-- ============================================================================
-- Memory Match — individual multiplayer memory game (game #17)
--
-- 2–4 players compete SOLO (no teams, no shared score). Players take turns
-- flipping two cards; a match earns 1 pair (+1 point) and another turn, a
-- miss flips the cards back and passes the turn. Matched cards are marked
-- with the winner's color/avatar instead of being removed, so everyone can
-- see who is leading. Game ends when all pairs are found.
--
-- DYNAMIC DIFFICULTY (auto mode, default):
--   2 players → 16 cards (4×4,  8 pairs)   ~1–2 min
--   3 players → 20 cards (5×4, 10 pairs)   ~2–3 min
--   4 players → 24 cards (6×4, 12 pairs)   ~3–5 min
-- Custom: easy 16 / medium 20 / hard 24 / expert 36 (6×6).
--
-- SERVER-AUTHORITATIVE (never trust the client):
--   • fn_memorymatch_flip validates: game running, caller IS the current
--     player, turn not expired, card in range, unmatched, unflipped, and
--     at most 2 flips per turn. FOR UPDATE row lock serializes flips.
--   • Match evaluation happens ONLY server-side (pair ids never leave the
--     server until both cards are revealed).
--   • fn_memorymatch_advance applies the reveal outcome only after the
--     timed reveal window; turns pass automatically when the 15 s timer
--     expires (fn_memorymatch_tick watchdog, run by every client).
--
-- TIE RULES (equal pairs): (1) found pairs faster (lower cumulative match
-- offset), (2) fewer wrong attempts, (3) earlier join.
-- ============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- 1) Tables
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "memorymatch_games" (
  id                  TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  "familyId"          TEXT NOT NULL,
  "hostUserId"        TEXT NOT NULL,
  "hostUserName"      TEXT NOT NULL DEFAULT 'Host',
  "roomName"          TEXT,
  status              TEXT NOT NULL DEFAULT 'waiting',  -- waiting|in_progress|completed|cancelled
  "difficulty"        TEXT NOT NULL DEFAULT 'auto',     -- auto|easy|medium|hard|expert
  "cardPack"          TEXT,                             -- classic|family|food|animals (picked at start)
  "turnSeconds"       INTEGER NOT NULL DEFAULT 15,      -- per-turn timer
  "maxPlayers"        INTEGER NOT NULL DEFAULT 4,
  cards               JSONB NOT NULL DEFAULT '[]'::jsonb,
  -- card = {"p": pairId, "k": symbolKey, "o": ownerUserId|null} (array index = card id)
  "playerOrder"       JSONB NOT NULL DEFAULT '[]'::jsonb,   -- userIds in seat order
  "currentPlayerId"   TEXT,
  "currentTurnIndex"  INTEGER NOT NULL DEFAULT 0,
  "turnEndsAt"        TIMESTAMPTZ,
  phase               TEXT NOT NULL DEFAULT 'turn',     -- turn|reveal
  "flippedCardIds"    JSONB NOT NULL DEFAULT '[]'::jsonb,  -- indices flipped this turn
  "revealEndsAt"      TIMESTAMPTZ,
  "pendingResult"     JSONB,                            -- {ids:[a,b], isMatch:bool}
  "scores"            JSONB NOT NULL DEFAULT '{}'::jsonb,  -- userId → pairs owned
  "stats"             JSONB NOT NULL DEFAULT '{}'::jsonb,  -- userId → {flips, misses, matchMs}
  "placements"        JSONB NOT NULL DEFAULT '[]'::jsonb,  -- final ranking
  "winnerUserIds"     JSONB NOT NULL DEFAULT '[]'::jsonb,
  "endReason"         TEXT,                             -- all_found|walkover
  "startedAt"         TIMESTAMPTZ,
  "completedAt"       TIMESTAMPTZ,
  "createdAt"         TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- shared temporary-room lifecycle columns (see 20260913120000)
  "autoCloseDeadline" TIMESTAMPTZ,
  "cancelledAt"       TIMESTAMPTZ,
  "closedAt"          TIMESTAMPTZ,
  "hostReady"         BOOLEAN DEFAULT true,
  "spectatorsEnabled" BOOLEAN DEFAULT true,
  "lastActivityAt"    TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "memorymatch_players" (
  id                TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  "gameId"          TEXT NOT NULL REFERENCES "memorymatch_games"(id) ON DELETE CASCADE,
  "userId"          TEXT NOT NULL,
  "userName"        TEXT NOT NULL,
  "isReady"         BOOLEAN NOT NULL DEFAULT false,
  "readyAt"         TIMESTAMPTZ,
  "joinedAt"        TIMESTAMPTZ NOT NULL DEFAULT now(),
  "lastActivityAt"  TIMESTAMPTZ DEFAULT now(),
  "leftAt"          TIMESTAMPTZ,                        -- mid-game departure (row kept for archive)
  UNIQUE ("gameId", "userId")
);

CREATE INDEX IF NOT EXISTS idx_memorymatch_players_game ON "memorymatch_players" ("gameId");
CREATE INDEX IF NOT EXISTS idx_memorymatch_games_family_status ON "memorymatch_games" ("familyId", "status");

-- ─────────────────────────────────────────────────────────────────────────────
-- 2) RLS (family-scoped, same shape as every other game table)
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE "memorymatch_games" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "memorymatch_players" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "memorymatch_games_select" ON "memorymatch_games";
CREATE POLICY "memorymatch_games_select" ON "memorymatch_games" FOR SELECT TO authenticated USING (
  EXISTS (SELECT 1 FROM "FamilyMember" fm
          WHERE fm."familyId" = "memorymatch_games"."familyId"
            AND fm."userId" = auth.uid()::text));

DROP POLICY IF EXISTS "memorymatch_games_insert" ON "memorymatch_games";
CREATE POLICY "memorymatch_games_insert" ON "memorymatch_games" FOR INSERT TO authenticated WITH CHECK (
  EXISTS (SELECT 1 FROM "FamilyMember" fm
          WHERE fm."familyId" = "memorymatch_games"."familyId"
            AND fm."userId" = auth.uid()::text)
  AND "hostUserId" = auth.uid()::text);

DROP POLICY IF EXISTS "memorymatch_games_update" ON "memorymatch_games";
CREATE POLICY "memorymatch_games_update" ON "memorymatch_games" FOR UPDATE TO authenticated USING (
  EXISTS (SELECT 1 FROM "FamilyMember" fm
          WHERE fm."familyId" = "memorymatch_games"."familyId"
            AND fm."userId" = auth.uid()::text));

DROP POLICY IF EXISTS "memorymatch_players_select" ON "memorymatch_players";
CREATE POLICY "memorymatch_players_select" ON "memorymatch_players" FOR SELECT TO authenticated USING (
  EXISTS (SELECT 1 FROM "memorymatch_games" g
          JOIN "FamilyMember" fm ON fm."familyId" = g."familyId"
          WHERE g."id" = "memorymatch_players"."gameId"
            AND fm."userId" = auth.uid()::text));

DROP POLICY IF EXISTS "memorymatch_players_insert" ON "memorymatch_players";
CREATE POLICY "memorymatch_players_insert" ON "memorymatch_players" FOR INSERT TO authenticated WITH CHECK (
  (
    -- Joining a room: your own row.
    "userId" = auth.uid()::text
    OR
    -- Host copying a rematch roster: any family member's row, but only
    -- into a game this user hosts.
    EXISTS (
      SELECT 1 FROM "memorymatch_games" g
      WHERE g."id" = "memorymatch_players"."gameId"
        AND g."hostUserId" = auth.uid()::text
        AND EXISTS (
          SELECT 1 FROM "FamilyMember" fm
          WHERE fm."familyId" = g."familyId"
            AND fm."userId" = auth.uid()::text)
    )
  )
  AND EXISTS (
    SELECT 1 FROM "memorymatch_games" g
    JOIN "FamilyMember" fm ON fm."familyId" = g."familyId"
    WHERE g."id" = "memorymatch_players"."gameId"
      AND fm."userId" = auth.uid()::text));

DROP POLICY IF EXISTS "memorymatch_players_update" ON "memorymatch_players";
CREATE POLICY "memorymatch_players_update" ON "memorymatch_players" FOR UPDATE TO authenticated USING (
  "userId" = auth.uid()::text)
WITH CHECK (
  "userId" = auth.uid()::text);

DROP POLICY IF EXISTS "memorymatch_players_delete_self" ON "memorymatch_players";
CREATE POLICY "memorymatch_players_delete_self" ON "memorymatch_players" FOR DELETE TO authenticated USING (
  "userId" = auth.uid()::text);

-- ─────────────────────────────────────────────────────────────────────────────
-- 3) Realtime (REPLICA IDENTITY FULL so UPDATE payloads carry the whole row)
-- ─────────────────────────────────────────────────────────────────────────────

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables
                 WHERE pubname = 'supabase_realtime' AND tablename = 'memorymatch_games') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE "memorymatch_games";
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables
                 WHERE pubname = 'supabase_realtime' AND tablename = 'memorymatch_players') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE "memorymatch_players";
  END IF;
END
$$;

ALTER TABLE "memorymatch_games" REPLICA IDENTITY FULL;
ALTER TABLE "memorymatch_players" REPLICA IDENTITY FULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- 4) Game RPCs
-- ─────────────────────────────────────────────────────────────────────────────

-- Next still-connected player after seat p_from_index (cyclic). Returns
-- {index, userId} or NULL when every other player has left.
CREATE OR REPLACE FUNCTION fn_memorymatch_next_turn(p_game_id text, p_from_index int)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_order jsonb;
  v_n int;
  v_j int;
  v_idx int;
  v_cand text;
BEGIN
  SELECT "playerOrder" INTO v_order FROM "memorymatch_games" WHERE "id" = p_game_id;
  v_order := COALESCE(v_order, '[]'::jsonb);
  v_n := jsonb_array_length(v_order);
  IF v_n = 0 THEN
    RETURN NULL;
  END IF;
  FOR v_j IN 1 .. v_n LOOP
    v_idx := (COALESCE(p_from_index, 0) + v_j) % v_n;
    v_cand := v_order ->> v_idx;
    IF NOT EXISTS (SELECT 1 FROM "memorymatch_players" mp
                    WHERE mp."gameId" = p_game_id
                      AND mp."userId" = v_cand
                      AND mp."leftAt" IS NOT NULL) THEN
      RETURN jsonb_build_object('index', v_idx, 'userId', v_cand);
    END IF;
  END LOOP;
  RETURN NULL;
END;
$$;
GRANT EXECUTE ON FUNCTION fn_memorymatch_next_turn(text, int) TO authenticated;

-- Host starts the match: builds the deck for the chosen difficulty (auto
-- scales with player count), picks a random card pack, fixes seat order.
CREATE OR REPLACE FUNCTION fn_memorymatch_start(p_game_id text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  g record;
  v_players jsonb;
  v_count int;
  v_deck_size int;
  v_pairs int;
  v_packs jsonb;
  v_pack text;
  v_shuffled jsonb;
  v_chosen jsonb;
  v_cards jsonb;
  v_order jsonb;
BEGIN
  SELECT * INTO g FROM "memorymatch_games" WHERE "id" = p_game_id;
  IF g.id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_found');
  END IF;
  IF g."hostUserId" <> auth.uid()::text THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_host');
  END IF;
  IF g.status <> 'waiting' THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'already_started');
  END IF;

  SELECT jsonb_agg(jsonb_build_object('userId', p."userId", 'userName', p."userName")
                   ORDER BY p."joinedAt", p."id")
    INTO v_players
    FROM "memorymatch_players" p
    WHERE p."gameId" = p_game_id AND p."leftAt" IS NULL;
  v_count := jsonb_array_length(COALESCE(v_players, '[]'::jsonb));
  IF v_count < 2 THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_enough_players');
  END IF;
  IF v_count > 4 THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'too_many_players');
  END IF;

  -- Dynamic difficulty: auto mode scales the deck with player count.
  v_deck_size := CASE g."difficulty"
    WHEN 'easy'   THEN 16
    WHEN 'medium' THEN 20
    WHEN 'hard'   THEN 24
    WHEN 'expert' THEN 36
    ELSE CASE v_count WHEN 2 THEN 16 WHEN 3 THEN 20 ELSE 24 END
  END;
  v_pairs := v_deck_size / 2;

  -- Random card pack, then a random symbol subset (keys only — clients map
  -- keys to emoji; the pair ids live exclusively server-side).
  v_packs := '{
    "classic":  ["star","heart","moon","sun","crown","gem","rocket","balloon","rainbow","bolt","flame","snow","target","gift","puzzle","sparkle","crystal","butterfly"],
    "family":   ["mom","dad","brother","sister","grandmother","grandfather","cousin","uncle","aunt","baby","elder","bigfamily","hug","home","petdog","homefood","picnic","storytime"],
    "food":     ["pizza","burger","icecream","cake","apple","fish","coffee","donut","banana","grapes","taco","noodles","sushi","cookie","cupcake","strawberry","avocado","popcorn"],
    "animals":  ["dog","cat","lion","tiger","elephant","rabbit","panda","bear","fox","koala","cow","pig","monkey","hen","unicorn","turtle","frog","owl"]
  }'::jsonb;
  v_pack := (ARRAY['classic','family','food','animals'])[1 + floor(random() * 4)::int];
  SELECT jsonb_agg(sym ORDER BY random()) INTO v_shuffled
    FROM jsonb_array_elements(v_packs -> v_pack) AS t(sym);
  SELECT jsonb_agg(sym) INTO v_chosen
    FROM (SELECT sym FROM jsonb_array_elements(v_shuffled) AS t(sym) LIMIT v_pairs) s;

  -- Deal + shuffle the deck. Card = {"p": pairId, "k": symbol, "o": owner}.
  WITH chosen AS (
    SELECT row_number() OVER () - 1 AS pair_id, sym #>> '{}' AS sym
    FROM jsonb_array_elements(v_chosen) AS t(sym)
  )
  SELECT jsonb_agg(jsonb_build_object('p', d.pair_id, 'k', d.sym, 'o', NULL) ORDER BY random())
    INTO v_cards
    FROM (
      SELECT pair_id, sym FROM chosen
      UNION ALL
      SELECT pair_id, sym FROM chosen
    ) d;

  v_order := (SELECT jsonb_agg(x ->> 'userId') FROM jsonb_array_elements(v_players) x);

  UPDATE "memorymatch_games"
     SET status = 'in_progress',
         "cardPack" = v_pack,
         cards = v_cards,
         "playerOrder" = v_order,
         "currentTurnIndex" = 0,
         "currentPlayerId" = v_order ->> 0,
         phase = 'turn',
         "flippedCardIds" = '[]'::jsonb,
         "pendingResult" = NULL,
         "turnEndsAt" = now() + make_interval(secs => g."turnSeconds"),
         "scores" = (SELECT COALESCE(jsonb_object_agg(x ->> 'userId', 0), '{}'::jsonb)
                     FROM jsonb_array_elements(v_players) x),
         "stats" = (SELECT COALESCE(jsonb_object_agg(x ->> 'userId',
                          jsonb_build_object('flips', 0, 'misses', 0, 'matchMs', 0)), '{}'::jsonb)
                    FROM jsonb_array_elements(v_players) x),
         "startedAt" = now(),
         "lastActivityAt" = now()
   WHERE "id" = p_game_id;

  PERFORM fn_touch_game_activity('memorymatch_games', p_game_id);
  RETURN jsonb_build_object('ok', true, 'deckSize', v_deck_size,
                            'pairs', v_pairs, 'pack', v_pack);
END;
$$;
GRANT EXECUTE ON FUNCTION fn_memorymatch_start(text) TO authenticated;

-- The ONLY way a card gets flipped. Full server-side validation; the row
-- lock (FOR UPDATE) serializes the two flips of a turn.
CREATE OR REPLACE FUNCTION fn_memorymatch_flip(p_game_id text, p_card_index int)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  g record;
  v_uid text := auth.uid()::text;
  v_card jsonb;
  v_flipped jsonb;
  v_is_match boolean;
  v_stats jsonb;
BEGIN
  SELECT * INTO g FROM "memorymatch_games" WHERE "id" = p_game_id FOR UPDATE;
  IF g.id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_found');
  END IF;
  IF g.status <> 'in_progress' THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_running');
  END IF;
  IF g.phase <> 'turn' THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'reveal_in_progress');
  END IF;
  IF g."currentPlayerId" <> v_uid THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_your_turn');
  END IF;
  IF g."turnEndsAt" IS NOT NULL AND now() > g."turnEndsAt" THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'turn_expired');
  END IF;
  IF p_card_index IS NULL OR p_card_index < 0 OR p_card_index >= jsonb_array_length(g.cards) THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'bad_card');
  END IF;
  v_card := g.cards -> p_card_index;
  IF COALESCE(v_card ->> 'o', '') <> '' THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'already_matched');
  END IF;
  IF EXISTS (SELECT 1 FROM jsonb_array_elements_text(g."flippedCardIds") AS t(x)
             WHERE x::int = p_card_index) THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'already_flipped');
  END IF;
  IF jsonb_array_length(g."flippedCardIds") >= 2 THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'too_many_flips');
  END IF;

  v_flipped := g."flippedCardIds" || to_jsonb(p_card_index);
  v_stats := COALESCE(g."stats" -> v_uid, '{"flips":0,"misses":0,"matchMs":0}'::jsonb);
  v_stats := jsonb_set(v_stats, '{flips}', to_jsonb(COALESCE((v_stats ->> 'flips')::int, 0) + 1));

  IF jsonb_array_length(v_flipped) = 2 THEN
    -- Second card: evaluate the pair SERVER-SIDE and open the timed reveal
    -- window (clients animate; the outcome is applied by fn_memorymatch_advance).
    -- NOTE: the array-index operands MUST be ints — `-> '12'` (text) would be
    -- an object-key lookup and silently yield NULL on an array.
    v_is_match := (g.cards -> ((v_flipped ->> 0)::int) ->> 'p')
                  = (g.cards -> ((v_flipped ->> 1)::int) ->> 'p');
    UPDATE "memorymatch_games"
       SET "flippedCardIds" = v_flipped,
           "stats" = jsonb_set(g."stats", ARRAY[v_uid], v_stats),
           phase = 'reveal',
           "pendingResult" = jsonb_build_object('ids', v_flipped, 'isMatch', v_is_match),
           "revealEndsAt" = now() + CASE WHEN v_is_match
                                         THEN interval '1.2 seconds'
                                         ELSE interval '1.6 seconds' END,
           "lastActivityAt" = now()
     WHERE "id" = p_game_id;
    RETURN jsonb_build_object('ok', true, 'isMatch', v_is_match, 'cardKey', v_card ->> 'k');
  END IF;

  UPDATE "memorymatch_games"
     SET "flippedCardIds" = v_flipped,
         "stats" = jsonb_set(g."stats", ARRAY[v_uid], v_stats),
         "lastActivityAt" = now()
   WHERE "id" = p_game_id;
  RETURN jsonb_build_object('ok', true, 'isMatch', NULL, 'cardKey', v_card ->> 'k');
END;
$$;
GRANT EXECUTE ON FUNCTION fn_memorymatch_flip(text, int) TO authenticated;

-- Applies the reveal outcome (after the timed window) and turn timeouts.
-- Idempotent: safe to call from every client + the tick watchdog.
CREATE OR REPLACE FUNCTION fn_memorymatch_advance(p_game_id text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  g record;
  v_uid text;
  v_ids jsonb;
  v_is_match boolean;
  v_cards jsonb;
  v_scores jsonb;
  v_stats jsonb;
  v_ps jsonb;
  v_ms bigint;
  v_i int;
  v_idx int;
  v_matched int;
  v_next jsonb;
BEGIN
  SELECT * INTO g FROM "memorymatch_games" WHERE "id" = p_game_id FOR UPDATE;
  IF g.id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_found');
  END IF;
  IF g.status <> 'in_progress' THEN
    RETURN jsonb_build_object('ok', true, 'status', 'completed');
  END IF;

  -- ── Reveal resolution (only after the reveal window elapsed) ──
  IF g.phase = 'reveal' AND (g."revealEndsAt" IS NULL OR now() >= g."revealEndsAt") THEN
    v_uid := g."currentPlayerId";
    v_ids := COALESCE(g."pendingResult" -> 'ids', '[]'::jsonb);
    v_is_match := COALESCE((g."pendingResult" ->> 'isMatch')::boolean, false);
    v_cards := g.cards;
    v_scores := COALESCE(g."scores", '{}'::jsonb);
    v_stats := COALESCE(g."stats", '{}'::jsonb);

    IF v_is_match AND jsonb_array_length(v_ids) = 2 THEN
      -- Pair found: mark both cards with the owner, +1 point, same player
      -- keeps the turn. Cards STAY on the board wearing the winner's color.
      FOR v_i IN 0 .. jsonb_array_length(v_ids) - 1 LOOP
        v_idx := (v_ids ->> v_i)::int;
        v_cards := jsonb_set(v_cards, ARRAY[v_idx::text],
                  COALESCE(v_cards -> v_idx, '{}'::jsonb) || jsonb_build_object('o', v_uid));
      END LOOP;
      v_scores := jsonb_set(v_scores, ARRAY[v_uid],
                 to_jsonb(COALESCE((v_scores ->> v_uid)::int, 0) + 1));
      v_ps := COALESCE(v_stats -> v_uid, '{"flips":0,"misses":0,"matchMs":0}'::jsonb);
      v_ms := ((EXTRACT(EPOCH FROM now()) - EXTRACT(EPOCH FROM g."startedAt")) * 1000)::bigint;
      v_ps := jsonb_set(v_ps, '{matchMs}',
               to_jsonb(COALESCE((v_ps ->> 'matchMs')::bigint, 0) + v_ms));
      v_stats := jsonb_set(v_stats, ARRAY[v_uid], v_ps);

      SELECT COUNT(*) INTO v_matched
        FROM jsonb_array_elements(v_cards) c
        WHERE COALESCE(c ->> 'o', '') <> '';
      IF v_matched >= jsonb_array_length(v_cards) THEN
        UPDATE "memorymatch_games"
           SET cards = v_cards, "scores" = v_scores, "stats" = v_stats,
               "flippedCardIds" = '[]'::jsonb, "pendingResult" = NULL, phase = 'turn',
               "lastActivityAt" = now()
         WHERE "id" = p_game_id;
        PERFORM fn_memorymatch_finish(p_game_id, 'all_found');
        RETURN jsonb_build_object('ok', true, 'matched', true, 'completed', true);
      END IF;

      UPDATE "memorymatch_games"
         SET cards = v_cards, "scores" = v_scores, "stats" = v_stats,
             "flippedCardIds" = '[]'::jsonb, "pendingResult" = NULL, phase = 'turn',
             "turnEndsAt" = now() + make_interval(secs => g."turnSeconds"),
             "lastActivityAt" = now()
       WHERE "id" = p_game_id;
      RETURN jsonb_build_object('ok', true, 'matched', true, 'completed', false);
    ELSE
      -- Miss: flip the cards back, turn passes to the next player.
      v_ps := COALESCE(v_stats -> v_uid, '{"flips":0,"misses":0,"matchMs":0}'::jsonb);
      v_ps := jsonb_set(v_ps, '{misses}',
               to_jsonb(COALESCE((v_ps ->> 'misses')::int, 0) + 1));
      v_stats := jsonb_set(v_stats, ARRAY[v_uid], v_ps);

      v_next := fn_memorymatch_next_turn(p_game_id, g."currentTurnIndex");
      IF v_next IS NULL THEN
        UPDATE "memorymatch_games"
           SET "stats" = v_stats, "flippedCardIds" = '[]'::jsonb,
               "pendingResult" = NULL, phase = 'turn', "lastActivityAt" = now()
         WHERE "id" = p_game_id;
        PERFORM fn_memorymatch_finish(p_game_id, 'walkover');
        RETURN jsonb_build_object('ok', true, 'matched', false, 'completed', true);
      END IF;
      UPDATE "memorymatch_games"
         SET "stats" = v_stats, "flippedCardIds" = '[]'::jsonb, "pendingResult" = NULL,
             phase = 'turn', "currentPlayerId" = v_next ->> 'userId',
             "currentTurnIndex" = (v_next ->> 'index')::int,
             "turnEndsAt" = now() + make_interval(secs => g."turnSeconds"),
             "lastActivityAt" = now()
       WHERE "id" = p_game_id;
      RETURN jsonb_build_object('ok', true, 'matched', false, 'completed', false);
    END IF;
  END IF;

  -- ── Turn timeout: 15 s elapsed without a completed pair → skip ──
  IF g.phase = 'turn' AND g."turnEndsAt" IS NOT NULL AND now() >= g."turnEndsAt" THEN
    v_next := fn_memorymatch_next_turn(p_game_id, g."currentTurnIndex");
    IF v_next IS NULL THEN
      UPDATE "memorymatch_games"
         SET "flippedCardIds" = '[]'::jsonb, phase = 'turn', "lastActivityAt" = now()
       WHERE "id" = p_game_id;
      PERFORM fn_memorymatch_finish(p_game_id, 'walkover');
      RETURN jsonb_build_object('ok', true, 'skipped', true, 'completed', true);
    END IF;
    UPDATE "memorymatch_games"
       SET "flippedCardIds" = '[]'::jsonb, "pendingResult" = NULL, phase = 'turn',
           "currentPlayerId" = v_next ->> 'userId',
           "currentTurnIndex" = (v_next ->> 'index')::int,
           "turnEndsAt" = now() + make_interval(secs => g."turnSeconds"),
           "lastActivityAt" = now()
     WHERE "id" = p_game_id;
    RETURN jsonb_build_object('ok', true, 'skipped', true, 'completed', false);
  END IF;

  RETURN jsonb_build_object('ok', true, 'noop', true);
END;
$$;
GRANT EXECUTE ON FUNCTION fn_memorymatch_advance(text) TO authenticated;

-- Watchdog every client runs every 2 s: resolves stale reveals, expires
-- timed-out turns, ends the game by walkover when players drop out. Also
-- refreshes the caller's participant heartbeat so the shared reaper
-- (fn_reap_disconnected_players) never kills a live room out from under
-- connected players.
CREATE OR REPLACE FUNCTION fn_memorymatch_tick(p_game_id text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  g record;
  v_active int;
BEGIN
  SELECT status INTO g FROM "memorymatch_games" WHERE "id" = p_game_id;
  IF g.status IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_found');
  END IF;

  -- Heartbeat: keep the caller's participant row fresh (no insert — pure
  -- refresh, spectators/non-participants are untouched).
  UPDATE "game_participants"
     SET "lastSeenAt" = now(), "connectionState" = 'online'
   WHERE "gameTable" = 'memorymatch_games' AND "gameId" = p_game_id
     AND "userId" = auth.uid()::text;

  IF g.status <> 'in_progress' THEN
    RETURN jsonb_build_object('ok', true, 'status', g.status);
  END IF;

  SELECT COUNT(*) INTO v_active FROM "memorymatch_players"
   WHERE "gameId" = p_game_id AND "leftAt" IS NULL;
  IF v_active <= 1 THEN
    PERFORM fn_memorymatch_finish(p_game_id, 'walkover');
    RETURN jsonb_build_object('ok', true, 'status', 'completed');
  END IF;

  PERFORM fn_memorymatch_advance(p_game_id);
  RETURN jsonb_build_object('ok', true, 'status', 'in_progress');
END;
$$;
GRANT EXECUTE ON FUNCTION fn_memorymatch_tick(text) TO authenticated;

-- Leave at any phase. Mid-game leavers keep their matched cards (and their
-- pairs) but are skipped in the turn rotation; when a single active player
-- remains the game completes by walkover with the current ranking.
CREATE OR REPLACE FUNCTION fn_memorymatch_leave(p_game_id text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  g record;
  me record;
  v_family_id text;
  v_user_name text;
  v_next jsonb;
  v_active int;
BEGIN
  SELECT * INTO g FROM "memorymatch_games" WHERE "id" = p_game_id;
  IF g.id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_found');
  END IF;

  SELECT * INTO me FROM "memorymatch_players"
   WHERE "gameId" = p_game_id AND "userId" = auth.uid()::text;
  IF me.id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_player');
  END IF;

  SELECT "userName", "familyId" INTO v_user_name, v_family_id
    FROM "game_participants"
   WHERE "gameTable" = 'memorymatch_games' AND "gameId" = p_game_id
     AND "userId" = auth.uid()::text;
  IF v_user_name IS NOT NULL THEN
    UPDATE "game_participants"
       SET "leftAt" = now(), "connectionState" = 'offline'
     WHERE "gameTable" = 'memorymatch_games' AND "gameId" = p_game_id
       AND "userId" = auth.uid()::text;
    INSERT INTO "game_room_events"
      ("gameTable","gameId","familyId","userId","userName","eventType","payload")
    VALUES
      ('memorymatch_games', p_game_id, v_family_id, auth.uid()::text, v_user_name,
       'leave', jsonb_build_object('reason', 'left'));
  END IF;

  IF g.status = 'waiting' THEN
    DELETE FROM "memorymatch_players" WHERE id = me.id;
    RETURN jsonb_build_object('ok', true);
  END IF;

  IF g.status = 'in_progress' THEN
    UPDATE "memorymatch_players"
       SET "leftAt" = now(), "lastActivityAt" = now()
     WHERE id = me.id;

    SELECT COUNT(*) INTO v_active FROM "memorymatch_players"
     WHERE "gameId" = p_game_id AND "leftAt" IS NULL;

    IF v_active <= 1 THEN
      PERFORM fn_memorymatch_finish(p_game_id, 'walkover');
      RETURN jsonb_build_object('ok', true, 'completed', true);
    END IF;

    IF g."currentPlayerId" = auth.uid()::text THEN
      -- The leaver held the turn (maybe mid-reveal) — clean and pass it on.
      v_next := fn_memorymatch_next_turn(p_game_id, g."currentTurnIndex");
      IF v_next IS NOT NULL THEN
        UPDATE "memorymatch_games"
           SET "flippedCardIds" = '[]'::jsonb, "pendingResult" = NULL, phase = 'turn',
               "currentPlayerId" = v_next ->> 'userId',
               "currentTurnIndex" = (v_next ->> 'index')::int,
               "turnEndsAt" = now() + make_interval(secs => g."turnSeconds"),
               "lastActivityAt" = now()
         WHERE "id" = p_game_id AND status = 'in_progress';
      END IF;
    END IF;
  END IF;

  RETURN jsonb_build_object('ok', true);
END;
$$;
GRANT EXECUTE ON FUNCTION fn_memorymatch_leave(text) TO authenticated;

-- Final ranking. Winner = most pairs; ties: (1) found pairs faster
-- (lower cumulative match offset), (2) fewer wrong attempts, (3) earlier join.
CREATE OR REPLACE FUNCTION fn_memorymatch_finish(p_game_id text, p_reason text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  g record;
  v_placements jsonb;
  v_winners jsonb;
BEGIN
  SELECT * INTO g FROM "memorymatch_games" WHERE "id" = p_game_id FOR UPDATE;
  IF g.id IS NULL OR g.status <> 'in_progress' THEN
    RETURN NULL;
  END IF;

  WITH ranked AS (
    SELECT
      mp."userId",
      COALESCE(mp."userName", 'Player') AS user_name,
      COALESCE((g."scores" ->> mp."userId")::int, 0) AS pairs,
      COALESCE((g."stats" -> mp."userId" ->> 'flips')::int, 0) AS flips,
      COALESCE((g."stats" -> mp."userId" ->> 'misses')::int, 0) AS misses,
      COALESCE((g."stats" -> mp."userId" ->> 'matchMs')::bigint, 0) AS match_ms,
      mp."joinedAt" AS joined
    FROM "memorymatch_players" mp
    WHERE mp."gameId" = p_game_id
  ), placed AS (
    SELECT r.*, ROW_NUMBER() OVER (
             ORDER BY r.pairs DESC, r.match_ms ASC, r.misses ASC, r.joined ASC
           ) AS place
    FROM ranked r
  )
  SELECT jsonb_agg(jsonb_build_object(
           'userId', p."userId",
           'userName', p.user_name,
           'place', p.place,
           'pairs', p.pairs,
           'flips', p.flips,
           'misses', p.misses,
           'accuracy', ROUND(COALESCE(p.pairs::numeric / NULLIF(p.pairs + p.misses, 0) * 100, 0), 1),
           'avgMatchMs', CASE WHEN p.pairs > 0
                              THEN ROUND(p.match_ms::numeric / p.pairs)
                              ELSE NULL END
         ) ORDER BY p.place)
    INTO v_placements
    FROM placed p;

  -- Winners = every player on place 1 (dense ranking via the placements we
  -- just built — CTEs can't span statements, so derive from v_placements).
  SELECT COALESCE(jsonb_agg(x ->> 'userId')
                   FILTER (WHERE (x ->> 'place')::int = 1), '[]'::jsonb)
    INTO v_winners
    FROM jsonb_array_elements(COALESCE(v_placements, '[]'::jsonb)) AS t(x);

  UPDATE "memorymatch_games"
     SET status = 'completed',
         "completedAt" = now(),
         "endReason" = p_reason,
         "placements" = COALESCE(v_placements, '[]'::jsonb),
         "winnerUserIds" = COALESCE(v_winners, '[]'::jsonb),
         phase = 'turn',
         "pendingResult" = NULL,
         "flippedCardIds" = '[]'::jsonb,
         "lastActivityAt" = now()
   WHERE "id" = p_game_id AND status = 'in_progress';

  RETURN COALESCE(v_placements, '[]'::jsonb);
END;
$$;

-- ─────────────────────────────────────────────────────────────────────────────
-- 5) Archive-on-complete trigger (Ghost Painter / Tug of War pattern)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION fn__memorymatch_on_complete()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW."status" = 'completed' AND COALESCE(OLD."status", '') <> 'completed' THEN
    BEGIN
      PERFORM public.fn__archive_family_match('memorymatch_games', NEW."id");
    EXCEPTION WHEN OTHERS THEN
      RAISE NOTICE 'memory match archive failed for %: %', NEW."id", SQLERRM;
    END;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_memorymatch_archive ON "memorymatch_games";
CREATE TRIGGER trg_memorymatch_archive
AFTER UPDATE ON "memorymatch_games"
FOR EACH ROW EXECUTE FUNCTION public.fn__memorymatch_on_complete();

-- ─────────────────────────────────────────────────────────────────────────────
-- 6) Champion badge seed (idempotent)
-- ─────────────────────────────────────────────────────────────────────────────

INSERT INTO "Badge" ("id","slug","name","nameHi","description","icon","category","tier","threshold","isSecret","createdAt")
VALUES
  (gen_random_uuid()::text,'memory-match-master','Memory Match Master','मेमोरी मैच मास्टर','Win 5 Memory Match games','🧠','games','gold',5,false,now())
ON CONFLICT ("slug") DO NOTHING;


-- ═══ fn_touch_game_activity: whitelist += memorymatch_games ═══

CREATE OR REPLACE FUNCTION public.fn_touch_game_activity(p_game_table text, p_game_id text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
    IF p_game_table NOT IN (
        'antakshari_games', 'chitmatch_games', 'bingo_games', 'ludo_games',
        'sos_games', 'dotsboxes_games', 'nameplace_games',
        'truthordare_games', 'twotruths_games', 'redlight_rounds',
        'chess_games', 'tictactoe_games', 'checkers_games', 'carrom_games',
        'tugofwar_games', 'memorymatch_games'
    ) THEN
        RAISE EXCEPTION 'Unknown game table: %', p_game_table;
    END IF;
    EXECUTE format(
        'UPDATE public.%I SET "lastActivityAt" = now() WHERE "id" = $1;',
        p_game_table
    ) USING p_game_id;
END;
$function$;


-- ═══ fn__hard_delete_room: whitelist += memorymatch_games ═══

CREATE OR REPLACE FUNCTION public.fn__hard_delete_room(p_game_table text, p_game_id text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
    IF p_game_table NOT IN (
        'antakshari_games', 'chitmatch_games', 'bingo_games', 'ludo_games',
        'sos_games', 'dotsboxes_games', 'nameplace_games',
        'truthordare_games', 'twotruths_games', 'redlight_rounds',
        'chess_games', 'tictactoe_games', 'checkers_games', 'carrom_games',
        'tugofwar_games', 'memorymatch_games'
    ) THEN
        RAISE EXCEPTION 'Unknown game table: %', p_game_table;
    END IF;

    -- 1. Delete pending invites for this room (stale invites must never
    --    re-open a closed room).
    DELETE FROM public.game_invites
    WHERE "gameTable" = p_game_table AND "gameId" = p_game_id;

    -- 2. Delete all participant rows (realtime fans these DELETEs out to
    --    every connected lobby — player lists empty immediately).
    DELETE FROM public.game_participants
    WHERE "gameTable" = p_game_table AND "gameId" = p_game_id;

    -- 3. Delete all spectator rows.
    DELETE FROM public.game_spectators
    WHERE "gameTable" = p_game_table AND "gameId" = p_game_id;

    -- 4. Delete the room event log (the 'cancel' event inserted by the
    --    caller has already been delivered via realtime WAL).
    DELETE FROM public.game_room_events
    WHERE "gameTable" = p_game_table AND "gameId" = p_game_id;

    -- 5. DELETE the game row itself — all game-specific child tables
    --    (players / moves / cards / turns / tokens / rounds / claims)
    --    cascade via FK ON DELETE CASCADE. After this returns, the room
    --    no longer exists anywhere in the database.
    EXECUTE format('DELETE FROM public.%I WHERE "id" = $1;', p_game_table)
    USING p_game_id;
END;
$function$;


-- ═══ fn_cancel_waiting_room: whitelist += memorymatch_games ═══

CREATE OR REPLACE FUNCTION public.fn_cancel_waiting_room(p_game_table text, p_game_id text, p_user_id text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
    v_host text;
    v_status text;
    v_family_id text;
BEGIN
    IF p_game_table NOT IN (
        'antakshari_games', 'chitmatch_games', 'bingo_games', 'ludo_games',
        'sos_games', 'dotsboxes_games', 'nameplace_games',
        'truthordare_games', 'twotruths_games', 'redlight_rounds',
        'tugofwar_games', 'memorymatch_games'
    ) THEN
        RETURN;
    END IF;

    EXECUTE format(
        'SELECT "hostUserId", "status", "familyId" FROM public.%I WHERE "id" = $1;',
        p_game_table
    ) INTO v_host, v_status, v_family_id USING p_game_id;

    IF v_host IS NULL OR v_status IS NULL THEN
        RETURN; -- room already gone — nothing to cancel
    END IF;

    IF v_host = p_user_id THEN
        -- Notify every connected client that the room is closed.
        INSERT INTO "game_room_events"
            ("gameTable", "gameId", "familyId", "userId", "userName", "eventType", "payload")
        VALUES
            (p_game_table, p_game_id, v_family_id, p_user_id, 'Host', 'cancel',
             jsonb_build_object('reason', 'host_cancelled'));

        -- Delete the room immediately from the database.
        PERFORM public.fn__hard_delete_room(p_game_table, p_game_id);
    END IF;
END;
$function$;


-- ═══ fn_end_game: whitelist += memorymatch_games ═══

CREATE OR REPLACE FUNCTION public.fn_end_game(p_game_table text, p_game_id text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
    IF p_game_table NOT IN (
        'antakshari_games', 'chitmatch_games', 'bingo_games', 'ludo_games',
        'sos_games', 'dotsboxes_games', 'nameplace_games',
        'truthordare_games', 'twotruths_games', 'redlight_rounds',
        'chess_games', 'tictactoe_games', 'checkers_games', 'carrom_games',
        'tugofwar_games', 'memorymatch_games'
    ) THEN
        RAISE EXCEPTION 'Unknown game table: %', p_game_table;
    END IF;

    -- ── Truth or Dare is an open-ended party game: the match ends when the
    --    host closes the table. Mark it completed FIRST so the archive
    --    records the family moment (participation for everyone) instead of
    --    discarding an "in-progress" row that the hard delete then erases.
    IF p_game_table = 'truthordare_games' THEN
        UPDATE public.truthordare_games
           SET "status" = 'completed',
               "completedAt" = now(),
               "lastActivityAt" = now()
         WHERE "id" = p_game_id
           AND "status" = 'in_progress';
    END IF;

    -- ── Family Gaming Ecosystem: archive completed matches BEFORE the
    --    hard delete (idempotent no-op for cancelled/abandoned rooms).
    BEGIN
        PERFORM public.fn__archive_family_match(p_game_table, p_game_id);
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'ecosystem archive failed for %/%: %', p_game_table, p_game_id, SQLERRM;
    END;

    PERFORM public.fn__hard_delete_room(p_game_table, p_game_id);
END;
$function$;


-- ═══ fn_get_match_ecosystem: whitelist += memorymatch_games ═══

CREATE OR REPLACE FUNCTION public.fn_get_match_ecosystem(p_game_table text, p_game_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_summary jsonb;
  v_meta jsonb;
BEGIN
  IF p_game_table NOT IN (
    'antakshari_games','chitmatch_games','bingo_games','ludo_games',
    'sos_games','dotsboxes_games','nameplace_games','truthordare_games',
    'twotruths_games','redlight_rounds','chess_games','tictactoe_games',
    'checkers_games','carrom_games','ghost_painter_rounds','tugofwar_games',
    'memorymatch_games'
  ) THEN
    RETURN NULL;
  END IF;

  -- Ensure processing has happened (no-op if already archived or not terminal)
  v_summary := public.fn__archive_family_match(p_game_table, p_game_id);

  -- If this call did the processing, return its rich summary directly
  IF v_summary IS NOT NULL THEN
    RETURN v_summary;
  END IF;

  -- Either already archived, or game row not terminal/gone.
  v_meta := public.fn__game_meta() -> p_game_table;

  SELECT jsonb_build_object(
    'matchId', h."id",
    'gameTable', h."gameTable",
    'gameName', COALESCE(v_meta->>'name', h."gameTable"),
    'gameIcon', COALESCE(v_meta->>'icon', '🎮'),
    'familyId', h."familyId",
    'winners', to_jsonb(h."winnerNames"),
    'playerCount', h."playerCount",
    'durationSeconds', h."durationSeconds",
    'archived', true,
    'newBadges', COALESCE(h."rewardsJson"->'newBadges', '[]'::jsonb),
    'completedChallenges', COALESCE(h."rewardsJson"->'completedChallenges', '[]'::jsonb),
    'milestones', COALESCE(h."rewardsJson"->'milestones', '[]'::jsonb),
    'players', COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
        'userId', p."userId", 'userName', p."userName", 'result', p."result"))
      FROM "game_match_players" p WHERE p."matchId" = h."id"
    ), '[]'::jsonb)
  )
  INTO v_summary
  FROM "game_match_history" h
  WHERE h."gameTable" = p_game_table AND h."gameId" = p_game_id;

  RETURN v_summary;  -- NULL when the room was cancelled (never archived)
END;
$function$;


-- ═══ fn_close_expired_rooms: tables += memorymatch_games ═══

CREATE OR REPLACE FUNCTION public.fn_close_expired_rooms()
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
    DECLARE
        v_closed_count integer := 0;
        t text;
        r record;
    BEGIN
        FOREACH t IN ARRAY ARRAY[
            'bingo_games', 'ludo_games', 'checkers_games', 'carrom_games',
            'chess_games', 'sos_games', 'antakshari_games', 'tictactoe_games',
            'truthordare_games', 'twotruths_games', 'dotsboxes_games',
            'nameplace_games', 'chitmatch_games', 'redlight_rounds',
            'tugofwar_games', 'memorymatch_games'
        ] LOOP
            FOR r IN EXECUTE format(
                'SELECT "id" AS game_id, "familyId" AS family_id
                 FROM %I
                 WHERE "autoCloseDeadline" IS NOT NULL
                   AND "autoCloseDeadline" <= now()
                   AND "cancelledAt" IS NULL
                   AND "closedAt" IS NULL
                   AND (
                       "status" IN (''lobby'', ''waiting'')
                       OR "status" IS NULL
                   )',
                t
            ) LOOP
                -- Post the auto_close event FIRST so realtime clients
                -- (waiting rooms, boards) receive it via WAL before the
                -- rows vanish.
                INSERT INTO "game_room_events"
                    ("gameTable", "gameId", "familyId", "userId", "userName", "eventType", "payload")
                VALUES
                    (t, r.game_id, r.family_id, NULL, 'System', 'auto_close',
                     jsonb_build_object('reason', 'auto_close_deadline_passed'));

                -- Remove the room entirely (invites, participants,
                -- spectators, events + game row; children cascade).
                BEGIN
                    PERFORM public.fn__hard_delete_room(t, r.game_id);
                EXCEPTION WHEN OTHERS THEN
                    -- Unknown table whitelist miss — fall back to soft close.
                    EXECUTE format(
                        'UPDATE %I SET "closedAt" = now(), "cancelledAt" = COALESCE("cancelledAt", now()) WHERE "id" = $1',
                        t
                    ) USING r.game_id;
                    DELETE FROM "game_participants"
                    WHERE "gameTable" = t AND "gameId" = r.game_id;
                    DELETE FROM "game_spectators"
                    WHERE "gameTable" = t AND "gameId" = r.game_id;
                END;

                v_closed_count := v_closed_count + 1;
            END LOOP;
        END LOOP;

        RETURN v_closed_count;
    END;
$function$;


-- ═══ fn_cleanup_completed_games: tables += memorymatch_games ═══

CREATE OR REPLACE FUNCTION public.fn_cleanup_completed_games()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
    tbl text;
    completed_tables text[] := ARRAY[
        'antakshari_games', 'chitmatch_games', 'bingo_games', 'ludo_games',
        'dotsboxes_games', 'nameplace_games', 'truthordare_games',
        'twotruths_games', 'chess_games', 'tictactoe_games',
        'checkers_games', 'carrom_games', 'tugofwar_games', 'memorymatch_games'
    ];
    finished_tables text[] := ARRAY['sos_games', 'redlight_rounds'];
    gp_round record;
BEGIN
    FOREACH tbl IN ARRAY completed_tables LOOP
        BEGIN
            EXECUTE format(
                'DELETE FROM public.game_invites
                 WHERE "gameTable" = $1
                   AND "gameId" IN (
                     SELECT "id" FROM public.%I
                     WHERE public.fn_is_completed_status("status")
                       AND "completedAt" IS NOT NULL
                       AND "completedAt" < now() - interval ''1 hour''
                   );',
                tbl
            ) USING tbl;
            EXECUTE format(
                'DELETE FROM public.%I
                 WHERE public.fn_is_completed_status("status")
                   AND "completedAt" IS NOT NULL
                   AND "completedAt" < now() - interval ''1 hour'';',
                tbl
            );
        EXCEPTION WHEN OTHERS THEN
            RAISE NOTICE 'fn_cleanup_completed_games: skip %: %', tbl, SQLERRM;
        END;
    END LOOP;

    FOREACH tbl IN ARRAY finished_tables LOOP
        BEGIN
            EXECUTE format(
                'DELETE FROM public.game_invites
                 WHERE "gameTable" = $1
                   AND "gameId" IN (
                     SELECT "id" FROM public.%I
                     WHERE public.fn_is_completed_status("status")
                       AND "finishedAt" IS NOT NULL
                       AND "finishedAt" < now() - interval ''1 hour''
                   );',
                tbl
            ) USING tbl;
            EXECUTE format(
                'DELETE FROM public.%I
                 WHERE public.fn_is_completed_status("status")
                   AND "finishedAt" IS NOT NULL
                   AND "finishedAt" < now() - interval ''1 hour'';',
                tbl
            );
        EXCEPTION WHEN OTHERS THEN
            RAISE NOTICE 'fn_cleanup_completed_games: skip %: %', tbl, SQLERRM;
        END;
    END LOOP;

    -- ── Ghost Painter rounds ──
    -- (a) Retire stale abandoned rounds (stuck in drawing/guessing for > 2h):
    --     flip to completed; the archive trigger then runs (rounds without
    --     any guesses are skipped by the archive guard).
    BEGIN
        UPDATE public.ghost_painter_rounds
           SET "status" = 'completed',
               "endsAt" = COALESCE("endsAt", now())
         WHERE "status" IN ('drawing','guessing')
           AND "startedAt" < now() - interval '2 hours';
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'fn_cleanup_completed_games: gp retire failed: %', SQLERRM;
    END;

    -- (b) Delete completed rounds older than 1 hour. The completion trigger
    --     archived them already; strokes + guesses cascade via FK.
    BEGIN
        DELETE FROM public.game_invites
         WHERE "gameTable" = 'ghost_painter_rounds'
           AND "gameId" IN (
             SELECT "id" FROM public.ghost_painter_rounds
              WHERE "status" = 'completed'
                AND "endsAt" < now() - interval '1 hour'
           );
        DELETE FROM public.ghost_painter_rounds
         WHERE "status" = 'completed'
           AND "endsAt" < now() - interval '1 hour';
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'fn_cleanup_completed_games: gp delete failed: %', SQLERRM;
    END;
END;
$function$;


-- ═══ fn__game_meta: += memorymatch_games ═══

CREATE OR REPLACE FUNCTION public.fn__game_meta()
 RETURNS jsonb
 LANGUAGE sql
 IMMUTABLE
AS $function$
  SELECT jsonb_build_object(
    'sos_games',          jsonb_build_object('id','sos','name','SOS','icon','🎯','accent','#F59E0B'),
    'bingo_games',        jsonb_build_object('id','bingo','name','Bingo','icon','🎟️','accent','#06B6D4'),
    'ludo_games',         jsonb_build_object('id','ludo','name','Ludo','icon','🎲','accent','#E11D48'),
    'antakshari_games',   jsonb_build_object('id','antakshari','name','Antakshari','icon','🎤','accent','#8B5CF6'),
    'chitmatch_games',    jsonb_build_object('id','chitmatch','name','TripleMatch','icon','🃏','accent','#EC4899'),
    'checkers_games',     jsonb_build_object('id','checkers','name','Checkers','icon','🔴','accent','#6366F1'),
    'chess_games',        jsonb_build_object('id','chess','name','Chess','icon','♞','accent','#64748B'),
    'carrom_games',       jsonb_build_object('id','carrom','name','Carrom','icon','⚪','accent','#F59E0B'),
    'tictactoe_games',    jsonb_build_object('id','tictactoe','name','Tic-Tac-Toe','icon','#️⃣','accent','#8B5CF6'),
    'truthordare_games',  jsonb_build_object('id','truthordare','name','Truth or Dare','icon','🎭','accent','#EF4444'),
    'twotruths_games',    jsonb_build_object('id','twotruths','name','Two Truths & a Lie','icon','🕵️','accent','#D946EF'),
    'dotsboxes_games',    jsonb_build_object('id','dotsboxes','name','Dots & Boxes','icon','▪️','accent','#06B6D4'),
    'nameplace_games',    jsonb_build_object('id','nameplace','name','Name Place Animal Thing','icon','📖','accent','#10B981'),
    'redlight_rounds',    jsonb_build_object('id','freeze-dash','name','Freeze & Dash','icon','🏃','accent','#10B981'),
    'ghost_painter_rounds', jsonb_build_object('id','ghost-painter','name','Ghost Painter','icon','👻','accent','#EC4899'),
    'tugofwar_games',       jsonb_build_object('id','tug-of-war','name','Tug of War','icon','🪢','accent','#E8612A'),
    'memorymatch_games',    jsonb_build_object('id','memory-match','name','Memory Match','icon','🧠','accent','#A855F7')
  );
$function$;


-- ═══ fn__evaluate_game_badges: += memory-match-master ═══

CREATE OR REPLACE FUNCTION public.fn__evaluate_game_badges(p_user_id text, p_family_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_overall   record;      -- overall stats row (gameTable='*')
  v_wins      int := 0;
  v_matches   int := 0;
  v_best      int := 0;
  v_spect     int := 0;
  v_given     int := 0;
  v_received  int := 0;
  v_variety   int := 0;
  v_week      int := 0;
  v_weekend   int := 0;
  v_social    int := 0;
  v_early     int := 0;
  v_late      int := 0;
  v_night_reg int := 0;
  v_night_win int := 0;
  v_cup_win   int := 0;
  v_earned    text[] := '{}';
  v_badge     record;
  v_new_badges jsonb := '[]'::jsonb;
  v_user_name text;
BEGIN
  SELECT * INTO v_overall FROM "game_user_stats"
  WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='*';
  IF NOT FOUND THEN RETURN '[]'::jsonb; END IF;

  v_wins := v_overall."wins"; v_matches := v_overall."matches";
  v_best := v_overall."streakBest"; v_spect := v_overall."spectated";
  v_given := v_overall."sportsmanshipGiven"; v_received := v_overall."sportsmanshipReceived";

  SELECT COUNT(DISTINCT "gameTable") INTO v_variety
  FROM "game_match_players"
  WHERE "userId"=p_user_id AND "familyId"=p_family_id;

  SELECT COUNT(*) INTO v_week
  FROM "game_match_players"
  WHERE "userId"=p_user_id AND "familyId"=p_family_id
    AND "finishedAt" >= now() - interval '7 days';

  SELECT COUNT(*) INTO v_weekend
  FROM "game_match_players"
  WHERE "userId"=p_user_id AND "familyId"=p_family_id
    AND EXTRACT(ISODOW FROM "finishedAt") IN (6,7);

  SELECT COUNT(*) INTO v_social
  FROM "game_match_players" gmp
  WHERE gmp."userId"=p_user_id AND gmp."familyId"=p_family_id
    AND (SELECT COUNT(*) FROM "game_match_players" o
         WHERE o."matchId"=gmp."matchId") >= 3;

  SELECT COUNT(*) INTO v_early
  FROM "game_match_players"
  WHERE "userId"=p_user_id AND "familyId"=p_family_id
    AND EXTRACT(HOUR FROM "finishedAt" AT TIME ZONE 'Asia/Kolkata') < 9;

  SELECT COUNT(*) INTO v_late
  FROM "game_match_players"
  WHERE "userId"=p_user_id AND "familyId"=p_family_id
    AND EXTRACT(HOUR FROM "finishedAt" AT TIME ZONE 'Asia/Kolkata') >= 22;

  -- scheduled family game night participations
  SELECT COUNT(*) INTO v_night_reg
  FROM "game_match_players" gmp
  JOIN "scheduled_game_nights" sgn
    ON sgn."familyId" = gmp."familyId"
   AND gmp."finishedAt" BETWEEN COALESCE(sgn."startedAt", sgn."scheduledFor") AND COALESCE(sgn."startedAt", sgn."scheduledFor") + interval '4 hours'
  WHERE gmp."userId"=p_user_id AND gmp."familyId"=p_family_id;

  SELECT COUNT(*) INTO v_night_win
  FROM "game_match_players" gmp
  JOIN "scheduled_game_nights" sgn
    ON sgn."familyId" = gmp."familyId"
   AND gmp."finishedAt" BETWEEN COALESCE(sgn."startedAt", sgn."scheduledFor") AND COALESCE(sgn."startedAt", sgn."scheduledFor") + interval '4 hours'
  WHERE gmp."userId"=p_user_id AND gmp."familyId"=p_family_id AND gmp."result"='win';

  SELECT COUNT(*) INTO v_cup_win
  FROM "game_season_winners"
  WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "rank"=1;

  -- ── Build the earned set ──
  IF v_wins >= 1        THEN v_earned := v_earned || ARRAY['first-game-win']; END IF;
  IF v_wins >= 5        THEN v_earned := v_earned || ARRAY['win-5-games']; END IF;
  IF v_wins >= 25       THEN v_earned := v_earned || ARRAY['win-25-games']; END IF;
  IF v_wins >= 100      THEN v_earned := v_earned || ARRAY['win-100-games']; END IF;
  IF v_wins >= 10       THEN v_earned := v_earned || ARRAY['family-champion']; END IF;
  IF v_best >= 3        THEN v_earned := v_earned || ARRAY['win-streak-3']; END IF;
  IF v_best >= 5        THEN v_earned := v_earned || ARRAY['undefeated-streak-5']; END IF;
  IF v_week >= 5        THEN v_earned := v_earned || ARRAY['played-5-games-week']; END IF;
  IF v_weekend >= 3     THEN v_earned := v_earned || ARRAY['weekend-gamer']; END IF;
  IF v_matches >= 50    THEN v_earned := v_earned || ARRAY['play-50-games']; END IF;
  IF v_matches >= 200   THEN v_earned := v_earned || ARRAY['play-200-games']; END IF;
  IF v_variety >= 8     THEN v_earned := v_earned || ARRAY['family-explorer']; END IF;
  IF v_spect >= 5       THEN v_earned := v_earned || ARRAY['spectator-supporter']; END IF;
  IF v_social >= 10     THEN v_earned := v_earned || ARRAY['social-gamer']; END IF;
  IF v_early >= 1       THEN v_earned := v_earned || ARRAY['early-bird']; END IF;
  IF v_late >= 1        THEN v_earned := v_earned || ARRAY['night-owl']; END IF;
  IF v_given >= 10      THEN v_earned := v_earned || ARRAY['cheering-champion']; END IF;
  IF v_received >= 10   THEN v_earned := v_earned || ARRAY['gracious-player']; END IF;
  IF v_night_reg >= 4   THEN v_earned := v_earned || ARRAY['family-game-night-regular']; END IF;
  IF v_night_win >= 25  THEN v_earned := v_earned || ARRAY['family-night-champion']; END IF;
  IF v_cup_win >= 1     THEN v_earned := v_earned || ARRAY['family-cup-champion']; END IF;

  -- Per-game champion badges (5 wins in that game)
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='bingo_games' AND "wins">=5) THEN v_earned := v_earned || ARRAY['bingo-master']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='sos_games' AND "wins">=5) THEN v_earned := v_earned || ARRAY['sos-strategist']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='ludo_games' AND "wins">=5) THEN v_earned := v_earned || ARRAY['ludo-champion']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='chess_games' AND "wins">=5) THEN v_earned := v_earned || ARRAY['chess-master']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='carrom_games' AND "wins">=5) THEN v_earned := v_earned || ARRAY['carrom-king']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='checkers_games' AND "wins">=5) THEN v_earned := v_earned || ARRAY['checkers-champ']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='tictactoe_games' AND "wins">=5) THEN v_earned := v_earned || ARRAY['tictactoe-tactician']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='dotsboxes_games' AND "wins">=5) THEN v_earned := v_earned || ARRAY['dots-boxer']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='nameplace_games' AND "wins">=5) THEN v_earned := v_earned || ARRAY['nameplace-scholar']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='antakshari_games' AND "wins">=5) THEN v_earned := v_earned || ARRAY['antakshari-star']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='twotruths_games' AND "wins">=5) THEN v_earned := v_earned || ARRAY['twotruths-mastermind']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='chitmatch_games' AND "wins">=5) THEN v_earned := v_earned || ARRAY['chitmatch-collector']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='redlight_rounds' AND "wins">=5) THEN v_earned := v_earned || ARRAY['freeze-dash-sprinter']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='truthordare_games' AND "matches">=10) THEN v_earned := v_earned || ARRAY['truthordare-fearless']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='ghost_painter_rounds' AND "wins">=5) THEN v_earned := v_earned || ARRAY['ghost-painter-virtuoso']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='tugofwar_games' AND "wins">=5) THEN v_earned := v_earned || ARRAY['tugofwar-titan']; END IF;
  IF EXISTS (SELECT 1 FROM "game_user_stats" WHERE "userId"=p_user_id AND "familyId"=p_family_id AND "gameTable"='memorymatch_games' AND "wins">=5) THEN v_earned := v_earned || ARRAY['memory-match-master']; END IF;

  IF v_earned = '{}' THEN RETURN '[]'::jsonb; END IF;

  SELECT COALESCE(MAX("userName"), 'Family Member') INTO v_user_name
  FROM "game_match_players" WHERE "userId" = p_user_id LIMIT 1;

  -- Insert only NEW badges; build the returned array from what was inserted
  FOR v_badge IN
    SELECT b."id", b."slug", b."name", b."icon", b."tier"
    FROM "Badge" b
    WHERE b."category" = 'games' AND b."slug" = ANY(v_earned)
      AND NOT EXISTS (
        SELECT 1 FROM "UserBadge" ub
        WHERE ub."badgeId" = b."id"
          AND ub."userId" = p_user_id
          AND COALESCE(ub."familyId", p_family_id) = p_family_id)
  LOOP
    INSERT INTO "UserBadge" ("id","userId","badgeId","familyId","earnedAt")
    VALUES (gen_random_uuid()::text, p_user_id, v_badge."id", p_family_id, now())
    ON CONFLICT DO NOTHING;

    v_new_badges := v_new_badges || jsonb_build_object(
      'slug', v_badge."slug",
      'name', v_badge."name",
      'icon', v_badge."icon",
      'tier', v_badge."tier");

    INSERT INTO "FamilyActivityLog"
      ("id","familyId","actorUserId","actorName","action","description","metadata")
    VALUES (
      gen_random_uuid()::text, p_family_id, p_user_id, v_user_name,
      'game_badge_earned',
      format('%s earned the %s badge', v_user_name, v_badge."name"),
      jsonb_build_object('badgeSlug', v_badge."slug", 'badgeName', v_badge."name",
                         'badgeIcon', v_badge."icon", 'badgeTier', v_badge."tier"));
  END LOOP;

  RETURN v_new_badges;
END;
$function$;


-- ═══ fn_set_player_ready: whitelist += tugofwar_players/games (bug fix)
--     and memorymatch_players/games ═══

CREATE OR REPLACE FUNCTION public.fn_set_player_ready(p_player_table text, p_game_table text, p_game_id text, p_user_id text, p_is_ready boolean)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
    IF p_player_table NOT IN (
        'antakshari_players', 'chitmatch_players', 'ludo_players',
        'sos_players', 'dotsboxes_players', 'nameplace_players',
        'truthordare_players', 'twotruths_players', 'redlight_players',
        'bingo_players', 'tugofwar_players', 'memorymatch_players'
    ) THEN
        RAISE EXCEPTION 'Unknown player table: %', p_player_table;
    END IF;
    IF p_game_table NOT IN (
        'antakshari_games', 'chitmatch_games', 'bingo_games', 'ludo_games',
        'sos_games', 'dotsboxes_games', 'nameplace_games',
        'truthordare_games', 'twotruths_games', 'redlight_rounds',
        'tugofwar_games', 'memorymatch_games'
    ) THEN
        RAISE EXCEPTION 'Unknown game table: %', p_game_table;
    END IF;

    IF p_player_table = 'redlight_players' THEN
        EXECUTE format(
            'UPDATE public.%I SET "isReady" = $1, "readyAt" = CASE WHEN $1 THEN now() ELSE NULL END
             WHERE "roundId" = $2 AND "userId" = $3;',
            p_player_table
        ) USING p_is_ready, p_game_id, p_user_id;
    ELSE
        EXECUTE format(
            'UPDATE public.%I SET "isReady" = $1, "readyAt" = CASE WHEN $1 THEN now() ELSE NULL END
             WHERE "gameId" = $2 AND "userId" = $3;',
            p_player_table
        ) USING p_is_ready, p_game_id, p_user_id;
    END IF;

    PERFORM public.fn_touch_game_activity(p_game_table, p_game_id);
END;
$function$;


-- ═══ fn__archive_family_match: whitelist + winners + participant
--     fallback + competitive result semantics += memorymatch_games,
--     rewardsJson carries the final placements ═══

CREATE OR REPLACE FUNCTION public.fn__archive_family_match(p_game_table text, p_game_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_family_id      text;
  v_status         text;
  v_created_at     timestamptz;
  v_finished_at    timestamptz;
  v_end_col        text;
  v_finished_status text;
  v_winner_col     text;
  v_winner_name_col text;
  v_winner_ids     text[] := '{}';
  v_winner_names   text[] := '{}';
  v_is_terminal    boolean := false;
  v_player_count   int := 0;
  v_meta           jsonb;
  v_result_kind    text := 'played';
  v_new_badges     jsonb := '[]'::jsonb;
  v_completed      jsonb := '[]'::jsonb;
  v_milestones     jsonb := '[]'::jsonb;
  v_badges_for_p   jsonb;
  v_chal_for_p     jsonb;
  v_participants   jsonb;
  v_p              jsonb;
  v_i              int;
  v_uid            text;
  v_uname          text;
  v_res            text;
  v_streak_before  int;
  v_duration       int;
  v_season_id      text;
  v_season_name    text;
  v_spectator      record;
  v_already        boolean;
  v_summary        jsonb;
BEGIN
  -- Whitelist game tables (security: p_game_table is used in dynamic SQL)
  IF p_game_table NOT IN (
    'antakshari_games','chitmatch_games','bingo_games','ludo_games',
    'sos_games','dotsboxes_games','nameplace_games','truthordare_games',
    'twotruths_games','redlight_rounds','chess_games','tictactoe_games',
    'checkers_games','carrom_games','ghost_painter_rounds','tugofwar_games',
    'memorymatch_games'
  ) THEN
    RETURN NULL;
  END IF;

  -- Idempotency: already archived → no-op
  SELECT EXISTS (
    SELECT 1 FROM "game_match_history"
    WHERE "gameTable" = p_game_table AND "gameId" = p_game_id
  ) INTO v_already;
  IF v_already THEN
    RETURN NULL;
  END IF;

  v_meta := public.fn__game_meta() -> p_game_table;

  -- ── Read the game row (dynamic: column names differ per table) ──
  -- sos_games + redlight_rounds use finishedAt/'finished';
  -- ghost_painter_rounds uses endsAt/'completed'; all others completedAt/'completed'.
  IF p_game_table IN ('sos_games','redlight_rounds') THEN
    v_end_col := 'finishedAt';
    v_finished_status := 'finished';
  ELSIF p_game_table = 'ghost_painter_rounds' THEN
    v_end_col := 'endsAt';
    v_finished_status := 'completed';
  ELSE
    v_end_col := 'completedAt';
    v_finished_status := 'completed';
  END IF;

  EXECUTE format(
    'SELECT "familyId", "status", "createdAt", COALESCE(%I, now())
       FROM public.%I WHERE "id" = $1', v_end_col, p_game_table)
    INTO v_family_id, v_status, v_created_at, v_finished_at
    USING p_game_id;

  IF v_family_id IS NULL THEN
    RETURN NULL; -- game row already gone (e.g. race with cron)
  END IF;
  v_created_at := COALESCE(v_created_at, now());
  v_finished_at := COALESCE(v_finished_at, now());

  -- Terminal statuses per table (from RoomConfig presets)
  v_is_terminal := v_status IN (v_finished_status, 'ended', 'done');

  -- ── Extract winners (column name differs per table) ──
  IF p_game_table = 'truthordare_games' THEN
    v_winner_ids := '{}';  -- party game: no winners, participation only
  ELSIF p_game_table = 'ghost_painter_rounds' THEN
    -- Winner(s) = the guesser(s) who cracked the drawing
    SELECT ARRAY(SELECT g."userId" FROM "ghost_painter_guesses" g
                 WHERE g."roundId" = p_game_id AND g."isCorrect")
      INTO v_winner_ids;
  ELSIF p_game_table IN ('antakshari_games','chitmatch_games','dotsboxes_games',
                          'nameplace_games','twotruths_games','tugofwar_games',
                          'memorymatch_games') THEN
    -- winnerUserIds is a jsonb array on these tables
    EXECUTE format(
      'SELECT ARRAY(SELECT jsonb_array_elements_text(COALESCE("winnerUserIds", ''[]''::jsonb))) FROM public.%I WHERE "id" = $1',
      p_game_table)
      INTO v_winner_ids USING p_game_id;
  ELSE
    v_winner_col := CASE
      WHEN p_game_table IN ('chess_games','checkers_games','carrom_games','ludo_games') THEN 'winnerId'
      WHEN p_game_table = 'tictactoe_games' THEN 'overallWinnerId'
      WHEN p_game_table = 'bingo_games' THEN 'winnerPlayerId'
      ELSE 'winnerUserId'  -- sos_games, redlight_rounds
    END;
    EXECUTE format(
      'SELECT ARRAY[COALESCE(%I, '''')] FROM public.%I WHERE "id" = $1',
      v_winner_col, p_game_table)
      INTO v_winner_ids USING p_game_id;
  END IF;

  v_winner_ids := COALESCE(v_winner_ids, '{}');
  v_winner_ids := ARRAY(SELECT x FROM unnest(v_winner_ids) AS x WHERE x IS NOT NULL AND x <> '');

  IF array_length(v_winner_ids, 1) IS NULL THEN
    IF NOT v_is_terminal THEN
      RETURN NULL; -- abandoned / cancelled / in-progress → do not archive
    END IF;
    v_result_kind := 'played';   -- finished without winners (party game / draw)
  ELSE
    v_result_kind := 'win';
    -- Winner display names — resolved uniformly from participants
    IF p_game_table = 'ghost_painter_rounds' THEN
      SELECT ARRAY(SELECT g."userName" FROM "ghost_painter_guesses" g
                   WHERE g."roundId" = p_game_id AND g."isCorrect"
                     AND g."userId" = ANY(v_winner_ids))
        INTO v_winner_names;
    ELSE
      SELECT COALESCE(array_agg(gp."userName") FILTER (WHERE gp."userName" IS NOT NULL), '{}')
        INTO v_winner_names
      FROM "game_participants" gp
      WHERE gp."gameTable" = p_game_table
        AND gp."gameId" = p_game_id
        AND gp."userId" = ANY(v_winner_ids);
    END IF;
    IF array_length(v_winner_names, 1) IS NULL AND p_game_table <> 'ghost_painter_rounds' THEN
      -- fallback: the game row's name column (board games)
      v_winner_name_col := CASE
        WHEN p_game_table IN ('chess_games','checkers_games','carrom_games','ludo_games') THEN 'winnerName'
        WHEN p_game_table = 'tictactoe_games' THEN 'overallWinnerName'
        WHEN p_game_table = 'redlight_rounds' THEN 'winnerUserName'
        WHEN p_game_table = 'bingo_games' THEN 'winnerPlayerName'
        ELSE NULL
      END;
      IF v_winner_name_col IS NOT NULL THEN
        EXECUTE format(
          'SELECT ARRAY[COALESCE(%I, '''')] FROM public.%I WHERE "id" = $1',
          v_winner_name_col, p_game_table)
          INTO v_winner_names USING p_game_id;
      ELSE
        v_winner_names := '{}';
      END IF;
      v_winner_names := ARRAY(SELECT x FROM unnest(COALESCE(v_winner_names,'{}')) AS x WHERE x IS NOT NULL AND x <> '');
    END IF;
    v_winner_names := COALESCE(v_winner_names, '{}');
  END IF;

  -- ── Load live participants (rows still exist at this point) ──
  -- role filter includes 'host': the room host IS a player in every game
  -- (RoomController.createRoom records the host with role='host').
  SELECT COALESCE(jsonb_agg(jsonb_build_object(
      'userId', gp."userId",
      'userName', COALESCE(gp."userName",'Family Member'),
      'role', gp."role")), '[]'::jsonb)
  INTO v_participants
  FROM "game_participants" gp
  WHERE gp."gameTable" = p_game_table
    AND gp."gameId" = p_game_id
    AND gp."role" IN ('player','host');

  v_player_count := jsonb_array_length(v_participants);

  -- ── Inline-player games (Pattern A: chess / checkers / carrom / tictactoe)
  --    create rooms via their own providers (ChallengeLobbyScreen), which do
  --    NOT write game_participants. Derive participants from the game row's
  --    player columns so those matches are archived too.
  IF v_player_count = 0 AND p_game_table IN ('chess_games','checkers_games','carrom_games','tictactoe_games') THEN
    DECLARE
      v_p1_id text; v_p1_name text; v_p2_id text; v_p2_name text;
    BEGIN
      IF p_game_table = 'tictactoe_games' THEN
        EXECUTE format('SELECT "playerXId","playerXName","playerOId","playerOName" FROM public.%I WHERE "id" = $1', p_game_table)
            INTO v_p1_id, v_p1_name, v_p2_id, v_p2_name USING p_game_id;
      ELSIF p_game_table = 'chess_games' THEN
        EXECUTE format('SELECT "playerWhiteId","playerWhiteName","playerBlackId","playerBlackName" FROM public.%I WHERE "id" = $1', p_game_table)
            INTO v_p1_id, v_p1_name, v_p2_id, v_p2_name USING p_game_id;
      ELSE -- checkers + carrom
        EXECUTE format('SELECT "playerOneId","playerOneName","playerTwoId","playerTwoName" FROM public.%I WHERE "id" = $1', p_game_table)
            INTO v_p1_id, v_p1_name, v_p2_id, v_p2_name USING p_game_id;
      END IF;

      v_participants := jsonb_build_array(
        jsonb_build_object('userId', v_p1_id, 'userName', COALESCE(v_p1_name,'Player'), 'role', 'player'),
        jsonb_build_object('userId', v_p2_id, 'userName', COALESCE(v_p2_name,'Player'), 'role', 'player'));
      v_player_count := 2;
    END;
  END IF;

  -- ── Ghost Painter: participants are the drawer plus everyone who guessed ──
  IF v_player_count = 0 AND p_game_table = 'ghost_painter_rounds' THEN
    SELECT jsonb_agg(jsonb_build_object(
             'userId', x."userId",
             'userName', COALESCE(x."userName", 'Family Member'),
             'role', x."role"))
    INTO v_participants
    FROM (
      SELECT g."userId" AS "userId", g."userName" AS "userName", 'player' AS "role"
      FROM "ghost_painter_guesses" g
      WHERE g."roundId" = p_game_id
      UNION ALL
      SELECT r."drawerPersonId", r."drawerPersonName", 'host'
      FROM "ghost_painter_rounds" r
      WHERE r."id" = p_game_id
        AND r."drawerPersonId" IS NOT NULL
        AND r."drawerPersonId" NOT IN (
          SELECT g."userId" FROM "ghost_painter_guesses" g WHERE g."roundId" = p_game_id)
    ) x;
    v_player_count := jsonb_array_length(COALESCE(v_participants, '[]'::jsonb));
  END IF;

  -- ── Truth or Dare: its lobby creates rooms via the game's own provider
  --    (todProvider.createGame → truthordare_players only), NOT via the
  --    RoomController — so game_participants stays empty. Derive participants
  --    from truthordare_players so these matches archive too.
  IF v_player_count = 0 AND p_game_table = 'truthordare_games' THEN
    SELECT jsonb_agg(jsonb_build_object(
             'userId', tp."userId",
             'userName', COALESCE(tp."userName", 'Family Member'),
             'role', CASE WHEN tp."userId" = (SELECT g."hostUserId" FROM public.truthordare_games g WHERE g."id" = p_game_id) THEN 'host' ELSE 'player' END))
    INTO v_participants
    FROM public.truthordare_players tp
    WHERE tp."gameId" = p_game_id;
    v_player_count := jsonb_array_length(COALESCE(v_participants, '[]'::jsonb));
  END IF;
  IF v_player_count = 0 AND p_game_table = 'tugofwar_games' THEN
    SELECT jsonb_agg(jsonb_build_object(
             'userId', tp."userId",
             'userName', COALESCE(tp."userName", 'Family Member'),
             'role', CASE WHEN tp."userId" = (SELECT g."hostUserId" FROM public.tugofwar_games g WHERE g."id" = p_game_id) THEN 'host' ELSE 'player' END))
    INTO v_participants
    FROM public.tugofwar_players tp
    WHERE tp."gameId" = p_game_id;
    v_player_count := jsonb_array_length(COALESCE(v_participants, '[]'::jsonb));
  END IF;
  IF v_player_count = 0 AND p_game_table = 'memorymatch_games' THEN
    SELECT jsonb_agg(jsonb_build_object(
             'userId', tp."userId",
             'userName', COALESCE(tp."userName", 'Family Member'),
             'role', CASE WHEN tp."userId" = (SELECT g."hostUserId" FROM public.memorymatch_games g WHERE g."id" = p_game_id) THEN 'host' ELSE 'player' END))
    INTO v_participants
    FROM public.memorymatch_players tp
    WHERE tp."gameId" = p_game_id;
    v_player_count := jsonb_array_length(COALESCE(v_participants, '[]'::jsonb));
  END IF;

  -- Ghost Painter: a round with zero guesses is an abandoned pickup round,
  -- not a family match — never archive it.
  IF p_game_table = 'ghost_painter_rounds' AND NOT EXISTS (
    SELECT 1 FROM "ghost_painter_guesses" WHERE "roundId" = p_game_id) THEN
    RETURN NULL;
  END IF;

  IF v_player_count = 0 THEN
    RETURN NULL; -- nobody recorded → nothing to archive
  END IF;

  v_duration := GREATEST(0, EXTRACT(EPOCH FROM (v_finished_at - v_created_at))::int);

  -- ── 1. Archive the match ──
  INSERT INTO "game_match_history"
    ("id","gameTable","gameId","familyId","playerCount",
     "winnerUserIds","winnerNames","resultKind","finishedAt","startedAt","durationSeconds")
  VALUES
    (p_game_id, p_game_table, p_game_id, v_family_id, v_player_count,
     v_winner_ids, v_winner_names, v_result_kind, v_finished_at, v_created_at, v_duration)
  ON CONFLICT ("gameTable","gameId") DO NOTHING;

  IF NOT EXISTS (SELECT 1 FROM "game_match_history" WHERE "gameTable"=p_game_table AND "gameId"=p_game_id) THEN
    RETURN NULL; -- concurrent call won the race
  END IF;

  -- ── 2. Per-player rows + stats + badges + challenges ──
  FOR v_i IN 0 .. (v_player_count - 1) LOOP
    v_p := v_participants -> v_i;
    v_uid := v_p ->> 'userId';
    v_uname := v_p ->> 'userName';

    -- Result derivation. Party games (Ghost Painter, Truth or Dare): the
    -- correct guesser wins (GP) or nobody wins (ToD); everyone else —
    -- including the drawer/host — is recorded as 'played', never 'loss'.
    IF v_winner_ids @> ARRAY[v_uid] THEN
      v_res := 'win';
    ELSIF array_length(v_winner_ids, 1) IS NULL THEN
      v_res := CASE WHEN p_game_table IN ('tugofwar_games','memorymatch_games') THEN 'draw'
                    WHEN p_game_table IN ('ghost_painter_rounds','truthordare_games') THEN 'played'
                    WHEN v_player_count <= 2 THEN 'draw' ELSE 'played' END;
    ELSE
      v_res := CASE WHEN p_game_table IN ('tugofwar_games','memorymatch_games') THEN 'loss'
                    WHEN p_game_table IN ('ghost_painter_rounds','truthordare_games') THEN 'played'
                    WHEN v_player_count <= 2 THEN 'loss' ELSE 'played' END;
    END IF;

    -- Streak snapshot BEFORE this match (for streak-based challenge checks)
    SELECT COALESCE(MAX("streakCurrent"), 0) INTO v_streak_before
    FROM "game_user_stats"
    WHERE "userId" = v_uid AND "familyId" = v_family_id AND "gameTable" = '*';

    INSERT INTO "game_match_players"
      ("matchId","gameTable","gameId","familyId","userId","userName","result","finishedAt")
    VALUES
      (p_game_id, p_game_table, p_game_id, v_family_id, v_uid, v_uname, v_res, v_finished_at)
    ON CONFLICT ("matchId","userId") DO NOTHING;

    -- game_user_stats: per-game row
    INSERT INTO "game_user_stats"
      ("userId","familyId","gameTable",
       "matches","wins","losses","draws","played","points","lastPlayedAt")
    VALUES
      (v_uid, v_family_id, p_game_table,
       1,
       CASE WHEN v_res='win' THEN 1 ELSE 0 END,
       CASE WHEN v_res='loss' THEN 1 ELSE 0 END,
       CASE WHEN v_res='draw' THEN 1 ELSE 0 END,
       CASE WHEN v_res='played' THEN 1 ELSE 0 END,
       CASE WHEN v_res='win' THEN 3 WHEN v_res IN ('draw','played') THEN 1 ELSE 0 END,
       v_finished_at)
    ON CONFLICT ("userId","familyId","gameTable") DO UPDATE SET
      "matches" = "game_user_stats"."matches" + 1,
      "wins" = "game_user_stats"."wins" + EXCLUDED."wins",
      "losses" = "game_user_stats"."losses" + EXCLUDED."losses",
      "draws" = "game_user_stats"."draws" + EXCLUDED."draws",
      "played" = "game_user_stats"."played" + EXCLUDED."played",
      "points" = "game_user_stats"."points" + EXCLUDED."points",
      "lastPlayedAt" = EXCLUDED."lastPlayedAt",
      "updatedAt" = now();

    -- game_user_stats: overall ('*') row with streak maintenance
    INSERT INTO "game_user_stats"
      ("userId","familyId","gameTable",
       "matches","wins","losses","draws","played","points",
       "streakCurrent","streakBest","lastPlayedAt")
    VALUES
      (v_uid, v_family_id, '*',
       1,
       CASE WHEN v_res='win' THEN 1 ELSE 0 END,
       CASE WHEN v_res='loss' THEN 1 ELSE 0 END,
       CASE WHEN v_res='draw' THEN 1 ELSE 0 END,
       CASE WHEN v_res='played' THEN 1 ELSE 0 END,
       CASE WHEN v_res='win' THEN 3 WHEN v_res IN ('draw','played') THEN 1 ELSE 0 END,
       CASE WHEN v_res='win' THEN 1 ELSE 0 END,
       CASE WHEN v_res='win' THEN 1 ELSE 0 END,
       v_finished_at)
    ON CONFLICT ("userId","familyId","gameTable") DO UPDATE SET
      "matches" = "game_user_stats"."matches" + 1,
      "wins" = "game_user_stats"."wins" + EXCLUDED."wins",
      "losses" = "game_user_stats"."losses" + EXCLUDED."losses",
      "draws" = "game_user_stats"."draws" + EXCLUDED."draws",
      "played" = "game_user_stats"."played" + EXCLUDED."played",
      "points" = "game_user_stats"."points" + EXCLUDED."points",
      "streakCurrent" = CASE
        WHEN EXCLUDED."wins" > 0 THEN "game_user_stats"."streakCurrent" + 1
        ELSE 0 END,
      "streakBest" = CASE
        WHEN EXCLUDED."wins" > 0 THEN GREATEST("game_user_stats"."streakBest", "game_user_stats"."streakCurrent" + 1)
        ELSE "game_user_stats"."streakBest" END,
      "lastPlayedAt" = EXCLUDED."lastPlayedAt",
      "updatedAt" = now();

    -- Badges for this player
    v_badges_for_p := public.fn__evaluate_game_badges(v_uid, v_family_id);
    IF v_badges_for_p IS NOT NULL AND jsonb_array_length(v_badges_for_p) > 0 THEN
      v_new_badges := v_new_badges || jsonb_build_object(
        'userId', v_uid, 'userName', v_uname, 'badges', v_badges_for_p);
    END IF;

    -- Challenges for this player
    v_chal_for_p := public.fn__advance_challenges(v_uid, v_family_id);
    IF v_chal_for_p IS NOT NULL AND jsonb_array_length(v_chal_for_p) > 0 THEN
      v_completed := v_completed || jsonb_build_object(
        'userId', v_uid, 'userName', v_uname, 'challenges', v_chal_for_p);
    END IF;
  END LOOP;

  -- ── 3. Spectator archive (rows still exist pre-delete) ──
  FOR v_spectator IN
    SELECT "userId", "userName" FROM "game_spectators"
    WHERE "gameTable" = p_game_table AND "gameId" = p_game_id
  LOOP
    INSERT INTO "game_user_stats"
      ("userId","familyId","gameTable","spectated")
    VALUES (v_spectator."userId", v_family_id, '*', 1)
    ON CONFLICT ("userId","familyId","gameTable") DO UPDATE SET
      "spectated" = "game_user_stats"."spectated" + 1,
      "updatedAt" = now();
  END LOOP;

  -- ── 4. Family aggregate ──
  INSERT INTO "game_family_stats" ("familyId","totalMatches","firstMatchAt","lastMatchAt")
  VALUES (v_family_id, 1, v_finished_at, v_finished_at)
  ON CONFLICT ("familyId") DO UPDATE SET
    "totalMatches" = "game_family_stats"."totalMatches" + 1,
    "lastMatchAt" = v_finished_at,
    "updatedAt" = now();

  UPDATE "game_family_stats" SET "distinctGames" = (
    SELECT COUNT(DISTINCT "gameTable") FROM "game_match_history" WHERE "familyId" = v_family_id
  ) WHERE "familyId" = v_family_id;

  -- ── 5. Activity feed: match completed ──
  INSERT INTO "FamilyActivityLog"
    ("id","familyId","actorUserId","actorName","action","description","metadata")
  VALUES (
    gen_random_uuid()::text,
    v_family_id,
    COALESCE(v_winner_ids[1], (v_participants->0->>'userId')),
    COALESCE(v_winner_names[1], (v_participants->0->>'userName'), 'Family'),
    'game_match_completed',
    CASE
      WHEN array_length(v_winner_ids,1) IS NULL
        THEN format('%s · %s players · a fun family moment', (v_meta->>'name'), v_player_count::text)
      ELSE format('%s won %s · %s players', array_to_string(v_winner_names, ' & '), (v_meta->>'name'), v_player_count)
    END,
    jsonb_build_object(
      'gameTable', p_game_table,
      'gameId', p_game_id,
      'gameName', v_meta->>'name',
      'gameIcon', v_meta->>'icon',
      'winners', to_jsonb(v_winner_names),
      'playerCount', v_player_count,
      'durationSeconds', v_duration
    )
  );

  -- ── 6. Season / Family Cup standings ──
  IF v_finished_at >= date_trunc('month', now()) THEN
    PERFORM public.fn_get_current_season(NULL);
  END IF;

  SELECT "id","name" INTO v_season_id, v_season_name
  FROM "game_seasons"
  WHERE v_finished_at >= "startsAt" AND v_finished_at < "endsAt"
  LIMIT 1;

  IF v_season_id IS NOT NULL THEN
    FOR v_i IN 0 .. (v_player_count - 1) LOOP
      v_p := v_participants -> v_i;
      v_uid := v_p ->> 'userId';
      IF v_winner_ids @> ARRAY[v_uid] THEN v_res := 'win';
      ELSIF array_length(v_winner_ids,1) IS NULL THEN v_res := CASE WHEN p_game_table IN ('tugofwar_games','memorymatch_games') THEN 'draw' WHEN p_game_table IN ('ghost_painter_rounds','truthordare_games') THEN 'played' WHEN v_player_count <= 2 THEN 'draw' ELSE 'played' END;
      ELSE v_res := CASE WHEN p_game_table IN ('tugofwar_games','memorymatch_games') THEN 'loss' WHEN p_game_table IN ('ghost_painter_rounds','truthordare_games') THEN 'played' WHEN v_player_count <= 2 THEN 'loss' ELSE 'played' END;
      END IF;
      INSERT INTO "game_season_standings"
        ("seasonId","familyId","userId","points","wins","gamesPlayed")
      VALUES
        (v_season_id, v_family_id, v_uid,
         CASE WHEN v_res='win' THEN 3 WHEN v_res IN ('draw','played') THEN 1 ELSE 0 END,
         CASE WHEN v_res='win' THEN 1 ELSE 0 END, 1)
      ON CONFLICT ("seasonId","familyId","userId") DO UPDATE SET
        "points" = "game_season_standings"."points" + EXCLUDED."points",
        "wins" = "game_season_standings"."wins" + EXCLUDED."wins",
        "gamesPlayed" = "game_season_standings"."gamesPlayed" + 1,
        "updatedAt" = now();
    END LOOP;
  END IF;

  -- ── 7. Family milestones ──
  v_milestones := public.fn__check_family_milestones(v_family_id);

  -- ── 8. Persist the rewards payload on the archive so EVERY player's
  --       results screen can celebrate (not just the archiving caller) ──
  v_summary := jsonb_build_object(
    'matchId', p_game_id,
    'gameTable', p_game_table,
    'gameName', v_meta->>'name',
    'gameIcon', v_meta->>'icon',
    'familyId', v_family_id,
    'winners', to_jsonb(v_winner_names),
    'playerCount', v_player_count,
    'durationSeconds', v_duration,
    'newBadges', v_new_badges,
    'completedChallenges', v_completed,
    'milestones', v_milestones,
    'players', COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
        'userId', p."userId", 'userName', p."userName", 'result', p."result"))
      FROM "game_match_players" p WHERE p."matchId" = p_game_id
    ), '[]'::jsonb)
  );

  UPDATE "game_match_history"
    SET "rewardsJson" = v_summary
    WHERE "gameTable" = p_game_table AND "gameId" = p_game_id;

  IF p_game_table = 'memorymatch_games' THEN
    UPDATE "game_match_history" h
       SET "rewardsJson" = h."rewardsJson" || jsonb_build_object(
             'placements', COALESCE((SELECT m."placements" FROM public.memorymatch_games m WHERE m."id" = p_game_id), '[]'::jsonb),
             'cardPack', (SELECT m."cardPack" FROM public.memorymatch_games m WHERE m."id" = p_game_id))
     WHERE h."gameTable" = 'memorymatch_games' AND h."gameId" = p_game_id;
  END IF;

  RETURN v_summary;
END;
$function$;

